"""
CORTEX Story Enhancement - Module 9A: DALL-E Prompt Generator (Pre-Phase)

PURPOSE:
Generate structured DALL-E prompts BEFORE story content updates, ensuring all
image filenames are known upfront. No backtracking needed.

WORKFLOW:
1. Analyze existing THE-AWAKENING-OF-CORTEX-MASTER.md structure
2. Identify narrative beats for illustration (20-30 key moments)
3. Generate structured prompts with consistent filename conventions
4. Output to docs/story/illustrations/prompts/ with metadata

FILENAME CONVENTION:
cortex-awakening-{chapter}-{sequence}.png
Examples:
  - cortex-awakening-prologue-01.png (Basement laboratory)
  - cortex-awakening-ch01-01.png (Coffee mug timeline)
  - cortex-awakening-ch02-01.png (SKULL rules whiteboard)

Author: Asif Hussain
Copyright © 2025 Asif Hussain. All rights reserved.
"""

import re
from dataclasses import dataclass
from pathlib import Path
from typing import List, Dict, Optional
from enum import Enum


class PlacementType(Enum):
    """Where the illustration appears in narrative."""
    CHAPTER_OPENING = "chapter_opening"  # Opening scene, sets mood
    KEY_MOMENT = "key_moment"  # Pivotal narrative beat
    CHARACTER_INTRO = "character_intro"  # Character first appearance
    COMEDIC_SCENE = "comedic_scene"  # Visual humor opportunity
    TECHNICAL_DIAGRAM = "technical_diagram"  # Architecture/concept illustration


@dataclass
class NarrativeBeat:
    """A moment in the story worthy of illustration."""
    chapter: str  # "prologue", "ch01", "ch02", etc.
    title: str  # Human-readable title
    narrative_anchor: str  # Text phrase for finding injection point
    scene_description: str  # What happens in this scene
    visual_elements: List[str]  # Key visual components
    mood: str  # Emotional tone (comedic, tense, triumphant, etc.)
    placement_type: PlacementType
    sequence: int  # 1, 2, 3 within chapter


@dataclass
class DALLEPrompt:
    """Structured DALL-E prompt with metadata."""
    filename: str  # cortex-awakening-{chapter}-{sequence}.png
    beat: NarrativeBeat
    prompt_text: str  # Full DALL-E 3 prompt
    style_guide: str  # Consistent artistic style
    technical_notes: str  # Resolution, aspect ratio, etc.
    
    def to_file_content(self) -> str:
        """Format as saveable text file."""
        return f"""CORTEX Story Illustration Prompt
=====================================

FILENAME: {self.filename}
CHAPTER: {self.beat.chapter}
TITLE: {self.beat.title}
PLACEMENT: {self.beat.placement_type.value}
MOOD: {self.beat.mood}

NARRATIVE ANCHOR:
{self.beat.narrative_anchor}

SCENE DESCRIPTION:
{self.beat.scene_description}

VISUAL ELEMENTS:
{chr(10).join(f"  - {elem}" for elem in self.beat.visual_elements)}

---

DALL-E 3 PROMPT:
{self.prompt_text}

---

STYLE GUIDE:
{self.style_guide}

TECHNICAL NOTES:
{self.technical_notes}

---
Generated by CORTEX Story Enhancement Orchestrator
"""


class DALLEPromptGenerator:
    """
    Analyzes existing story and generates DALL-E prompts for 20-30 illustrations.
    
    RUNS BEFORE PHASE 2 CONTENT GENERATION.
    Ensures all image filenames known upfront - no backtracking.
    """
    
    # Consistent artistic style across all illustrations
    STYLE_GUIDE = """
Digital illustration, tech comedy aesthetic. Warm lighting from multiple monitors 
casting blue-purple glow. Slightly exaggerated proportions for comedic effect. 
Rich color palette (deep blues, warm oranges from coffee, cool whites from screens).
Cluttered but organized chaos - visible coffee mugs, cables, whiteboards with diagrams.
Character style: expressive, slightly cartoon-like but grounded in reality.
Environment: Basement laboratory feel, lots of technical equipment, lived-in space.
"""
    
    TECHNICAL_NOTES = """
Resolution: 1024x1024 (DALL-E 3 standard)
Aspect Ratio: 1:1 (square format for flexible placement)
Style: Digital illustration, detailed but not photorealistic
Color: RGB, vibrant but not oversaturated
Focus: Clear subject, detailed background, depth of field
"""
    
    def __init__(self, master_file_path: Path, output_dir: Path):
        """
        Initialize prompt generator.
        
        Args:
            master_file_path: Path to THE-AWAKENING-OF-CORTEX-MASTER.md
            output_dir: Where to save prompts (docs/story/illustrations/prompts/)
        """
        self.master_file = master_file_path
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        # Create subdirectories
        (self.output_dir / "metadata").mkdir(exist_ok=True)
        (self.output_dir.parent / "images").mkdir(exist_ok=True)
    
    def analyze_story_structure(self) -> List[NarrativeBeat]:
        """
        Extract narrative beats from existing master file.
        
        Returns:
            20-30 narrative beats worthy of illustration
        """
        content = self.master_file.read_text(encoding='utf-8')
        beats = []
        
        # PROLOGUE: The Basement Laboratory
        beats.append(NarrativeBeat(
            chapter="prologue",
            title="The Basement Laboratory",
            narrative_anchor="The basement had become a laboratory.",
            scene_description="Mr. Codenstein's basement workspace: three monitors in semicircle, seventeen coffee mugs forming a timeline, whiteboards covered in frantic diagrams with 'TIER ARCHITECTURE' and neural network sticky notes, organized chaos everywhere.",
            visual_elements=[
                "Three monitors arranged in semicircle with code displays",
                "Seventeen coffee mugs at various stages of decay",
                "Whiteboards with 'TIER ARCHITECTURE' and sticky note neural network",
                "Mr. Codenstein hunched over keyboard, chaotic hair",
                "Basement lighting - warm monitor glow, technical equipment",
                "Half-eaten bagel on stack of technical books"
            ],
            mood="Comedic chaos, creative obsession",
            placement_type=PlacementType.CHAPTER_OPENING,
            sequence=1
        ))
        
        beats.append(NarrativeBeat(
            chapter="prologue",
            title="G Appears",
            narrative_anchor="And then she appeared.",
            scene_description="G's apparition manifests beside the whiteboard - ethereal but solid-looking, arms crossed, one eyebrow raised. Visual representation of Mr. Codenstein's conscience taking form. She's part mentor, part skeptic, standing in the chaotic lab surveying the organized madness.",
            visual_elements=[
                "G as translucent/ethereal figure beside whiteboard",
                "Arms crossed, skeptical expression, one raised eyebrow",
                "Whiteboard behind her with tier architecture diagrams",
                "Contrast: her calm presence vs chaotic lab environment",
                "Subtle glow/aura suggesting she's imaginary manifestation",
                "Mr. Codenstein at keyboard, not looking at her (yet aware)"
            ],
            mood="Mystical meets comedy, imaginary girlfriend energy",
            placement_type=PlacementType.CHARACTER_INTRO,
            sequence=2
        ))
        
        # CHAPTER 1: The Amnesia Crisis
        beats.append(NarrativeBeat(
            chapter="ch01",
            title="Coffee Mug Timeline",
            narrative_anchor="Coffee mug seventeen sat on top of a stack of papers titled",
            scene_description="Close-up on the seventeen coffee mugs arranged like an archaeological dig. Each mug represents a different stage: fresh coffee near keyboard (Tier 1), stale coffee mid-desk (Tier 2), fossilized ecosystem coffee by wall (Tier 3). Visual metaphor for memory tiers.",
            visual_elements=[
                "Seventeen coffee mugs in gradient from fresh to moldy",
                "Mug #1-5 near keyboard: fresh, steam rising (Tier 1)",
                "Mug #6-12 mid-desk: lukewarm, stale (Tier 2)",
                "Mug #13-17 by wall: mold, ecosystem, forgotten (Tier 3)",
                "Labels/sticky notes indicating tier system",
                "Papers underneath: 'Conversation Context Persistence Strategies'"
            ],
            mood="Absurd visual comedy, organizational chaos",
            placement_type=PlacementType.COMEDIC_SCENE,
            sequence=1
        ))
        
        beats.append(NarrativeBeat(
            chapter="ch01",
            title="Copilot Amnesia",
            narrative_anchor="The GitHub Copilot Chat window stared back at him, pristine and empty.",
            scene_description="Split screen showing the contrast: left side has Mr. Codenstein's detailed notes and git history from 2-hour conversation, right side shows blank Copilot chat with cheerful 'I'd be happy to help!' response that has zero memory of previous discussion.",
            visual_elements=[
                "Split monitor view: notes vs chat",
                "Left: git commits with desperate messages, detailed architecture notes",
                "Right: empty Copilot chat, cheerful but clueless",
                "Mr. Codenstein's frustrated face reflected in screen",
                "Eye twitch visible, cold coffee mug in hand",
                "Visual disconnect between human memory vs AI amnesia"
            ],
            mood="Frustration meets comedy, technology irony",
            placement_type=PlacementType.KEY_MOMENT,
            sequence=2
        ))
        
        beats.append(NarrativeBeat(
            chapter="ch01",
            title="The Goldfish Theory Whiteboard",
            narrative_anchor="'THE GOLDFISH THEORY' appeared on the whiteboard in large letters",
            scene_description="Whiteboard covered in frantic marker work: 'THE GOLDFISH THEORY' in huge letters at top, goldfish drawing, arrows connecting 'decent memory' to 'terrible context switching', comparison diagram showing Copilot's conversation buffer as circular fish bowl.",
            visual_elements=[
                "Whiteboard with 'THE GOLDFISH THEORY' title",
                "Cartoon goldfish drawing in fishbowl labeled 'Context Buffer'",
                "Arrows connecting concepts: memory vs context switching",
                "5-10 message buffer diagram (circular, first-in-first-out)",
                "Mr. Codenstein holding marker, manic energy visible",
                "G's apparition in corner, amused expression",
                "Scattered sticky notes with observations"
            ],
            mood="Breakthrough moment, caffeinated insight",
            placement_type=PlacementType.TECHNICAL_DIAGRAM,
            sequence=3
        ))
        
        # CHAPTER 2: Tier 0 - The Gatekeeper Incident
        beats.append(NarrativeBeat(
            chapter="ch02",
            title="The Almost-Disaster",
            narrative_anchor="His hand moved away from the keyboard.",
            scene_description="Dramatic close-up: Mr. Codenstein's finger hovering millimeters above Enter key, frozen mid-keystroke. Screen shows dangerous database initialization code with no safety checks. Tension of almost-disaster, moment of recognition before catastrophe.",
            visual_elements=[
                "Extreme close-up: finger hovering over Enter key",
                "Monitor reflection in glasses: dangerous code visible",
                "Sweat bead on forehead suggesting tension",
                "Code on screen: database init, no validation, destructive",
                "Background: previous project failures (smart mirror, garden) as faded photos",
                "Clock showing 2:17 AM adding to exhaustion drama"
            ],
            mood="Tense, suspenseful, narrowly-avoided disaster",
            placement_type=PlacementType.KEY_MOMENT,
            sequence=1
        ))
        
        beats.append(NarrativeBeat(
            chapter="ch02",
            title="SKULL Rules Whiteboard",
            narrative_anchor="'SKULL rules. Six layers of skull protection before anything reaches the brain.'",
            scene_description="Whiteboard transformation: neat diagram of six concentric circles labeled as skull protection layers surrounding brain core. Each layer labeled with protection type (Validation, Confirmation, Protection, Logging, Monitoring, Recovery). Mr. Codenstein drawing it while G watches approvingly.",
            visual_elements=[
                "Whiteboard: six concentric circles (skull layers)",
                "Center: 'BRAIN (Tier 1-3)' protected core",
                "Layers labeled: Validation, Confirmation, Protection, Logging, Monitoring, Recovery",
                "Arrows showing threats blocked at each layer",
                "G's apparition beside whiteboard, approving pose",
                "Mr. Codenstein drawing final layer, satisfied expression",
                "Brain protection = skull protection visual metaphor"
            ],
            mood="Triumphant, architectural breakthrough, protective",
            placement_type=PlacementType.TECHNICAL_DIAGRAM,
            sequence=2
        ))
        
        beats.append(NarrativeBeat(
            chapter="ch02",
            title="G Manifested in the Thinking Chair",
            narrative_anchor="The vision settled into the thinking chair",
            scene_description="G's apparition sitting in the 'thinking chair' (actually folding chair supporting second monitor). She's translucent but solid-looking, reviewing brain protection rules with that knowing expression. Comedic contrast: ethereal being in mundane basement furniture.",
            visual_elements=[
                "G sitting in makeshift thinking chair (folding chair + monitor)",
                "Translucent/ghostly appearance but clearly present",
                "Arms crossed, reviewing brain protection rules on screen",
                "Amused but approving expression",
                "Basement clutter around her: cables, equipment, coffee mugs",
                "Mr. Codenstein at desk, having conversation with empty chair",
                "Visual comedy: imaginary girlfriend very clearly manifested"
            ],
            mood="Comedic, surreal, warm relationship dynamic",
            placement_type=PlacementType.CHARACTER_INTRO,
            sequence=3
        ))
        
        # CHAPTER 3: Tier 1 - The SQLite Intervention
        beats.append(NarrativeBeat(
            chapter="ch03",
            title="The Laptop Crash",
            narrative_anchor="The laptop crashed at 2:17 AM on Thursday.",
            scene_description="Blue screen of death moment. Mr. Codenstein's face illuminated by error screen, three hours of work vanishing. Scattered around: forty-seven backup files with desperate filenames like 'working_memory_I_MEAN_IT_THIS_TIME.db'. Visual representation of volatility vs persistence.",
            visual_elements=[
                "Blue screen of death on monitor, progress bar mocking",
                "Mr. Codenstein's shocked/defeated expression",
                "File explorer showing 47 backup files with frantic names",
                "Clock showing 2:17 AM (recurring time)",
                "In-memory architecture diagram on whiteboard behind him",
                "Coffee mug #18 knocked over from shock"
            ],
            mood="Disaster, comedy through desperation, technical failure",
            placement_type=PlacementType.KEY_MOMENT,
            sequence=1
        ))
        
        beats.append(NarrativeBeat(
            chapter="ch03",
            title="SQLite Decision",
            narrative_anchor="'SQLite,' he said to the empty basement. 'Now. I'm doing this right.'",
            scene_description="Mr. Codenstein at keyboard with renewed determination, deleting in-memory code and starting fresh with SQLite. G's apparition fading after delivering wisdom about 'elegance without reliability is just technical debt.' Whiteboard showing transition from volatile to persistent storage.",
            visual_elements=[
                "Mr. Codenstein typing with determination",
                "Screen showing SQLite import statements replacing in-memory code",
                "G's translucent apparition fading in background, job done",
                "Whiteboard diagram: IN-MEMORY (crossed out) → SQLite (circled)",
                "Satisfied expression replacing earlier defeat",
                "Phone showing text: 'Demo in 6 hours. Ready?'"
            ],
            mood="Determination, lesson learned, technical redemption",
            placement_type=PlacementType.TECHNICAL_DIAGRAM,
            sequence=2
        ))
        
        # CHAPTER 4: Agent Coordination
        beats.append(NarrativeBeat(
            chapter="ch04",
            title="Seven Agents Chaos",
            narrative_anchor="Seven agents. Seven specialists.",
            scene_description="Visualization of seven CORTEX agents as overlapping circles on whiteboard, each labeled (Memory Manager, Code Analyzer, Test Generator, Documentation Writer, Git Coordinator, Error Handler, Conversation Tracker). Arrows crisscrossing everywhere showing coordination complexity. Mr. Codenstein looks overwhelmed.",
            visual_elements=[
                "Whiteboard with seven overlapping agent circles",
                "Messy arrows showing inter-agent communication",
                "Labels: Memory, Code, Test, Docs, Git, Error, Conversation",
                "Mr. Codenstein scratching head, overwhelmed expression",
                "Multiple monitors showing different agent outputs simultaneously",
                "Chaos of coordination attempts visible in terminal logs"
            ],
            mood="Overwhelming complexity, organized chaos",
            placement_type=PlacementType.TECHNICAL_DIAGRAM,
            sequence=1
        ))
        
        # CHAPTER 5: Knowledge Graph
        beats.append(NarrativeBeat(
            chapter="ch05",
            title="The 2AM Knowledge Graph Epiphany",
            narrative_anchor="At 2:17 AM on a Tuesday (they were becoming a pattern), Codenstein had his knowledge graph breakthrough.",
            scene_description="Miss G's apparition floating cross-legged in mid-air beside monitor at 2:17 AM, teaching moment. Screen shows simple knowledge graph with three edge types: REFERENCES, INFLUENCES, CONFLICTS_WITH. Visual 'aha' moment as simplicity replaces complexity.",
            visual_elements=[
                "Miss G floating cross-legged, ethereal meditation pose",
                "Clock showing 2:17 AM (pattern recognition moment)",
                "Screen displaying simple three-edge knowledge graph",
                "Code: 'class KnowledgeRelationship' with three types",
                "Mr. Codenstein's face: realization dawning",
                "Coffee mug #19, still steaming (fresh insight energy)",
                "Whiteboard behind: complex graph crossed out, simple graph circled"
            ],
            mood="Epiphany, zen simplicity, teaching moment",
            placement_type=PlacementType.KEY_MOMENT,
            sequence=1
        ))
        
        beats.append(NarrativeBeat(
            chapter="ch05",
            title="G's Journal Inspiration",
            narrative_anchor="'Based on your notebooks. You're credited in the code comments.'",
            scene_description="Real G (not apparition) in doorway at 2:34 AM with chamomile tea (wind-down signal). Mr. Codenstein showing her the conversation capture feature inspired by her journals. Split screen: her physical journals beside CORTEX's digital capture interface. Collaborative design moment.",
            visual_elements=[
                "Real G in doorway, backlit, holding chamomile tea mug",
                "Split screen: physical journal vs CORTEX capture UI",
                "Her journals with colored tabs, annotations visible",
                "CORTEX interface: tags, notes, context preservation",
                "Mr. Codenstein gesturing proudly at implementation",
                "Clock: 2:34 AM (later than usual, progress)",
                "Warm domestic moment vs technical achievement"
            ],
            mood="Collaborative, warmth, partnership, inspiration",
            placement_type=PlacementType.CHARACTER_INTRO,
            sequence=2
        ))
        
        # CHAPTER 6: Token Optimization
        beats.append(NarrativeBeat(
            chapter="ch06",
            title="Token Mountain",
            narrative_anchor="The token counter hit 127,000 and kept climbing.",
            scene_description="Monitor showing massive token count climbing exponentially. Mr. Codenstein's horrified expression as context bloats out of control. Visualization: mountain of text/tokens cascading down screen like avalanche. Performance graph showing latency spike from milliseconds to seconds.",
            visual_elements=[
                "Token counter: 127,000+ in alarming red",
                "Performance graph: latency spike visual",
                "Cascading text/tokens flooding down screen (avalanche metaphor)",
                "Mr. Codenstein's face: shock and horror",
                "Monitor glow reflecting off glasses showing massive context",
                "Error messages: 'CONTEXT TOO LARGE', 'RATE LIMIT EXCEEDED'"
            ],
            mood="Technical disaster, exponential growth horror",
            placement_type=PlacementType.KEY_MOMENT,
            sequence=1
        ))
        
        # CHAPTER 7: TDD Mastery (MAJOR NEW FEATURE)
        beats.append(NarrativeBeat(
            chapter="ch07",
            title="RED-GREEN-REFACTOR Whiteboard",
            narrative_anchor="'RED, GREEN, REFACTOR. In that order. Always.'",
            scene_description="Whiteboard diagram: TDD cycle as traffic light (RED test fails → GREEN implementation → REFACTOR cleanup). Mr. Codenstein explaining to himself (G watching). Visual emphasis on MANDATORY order, no skipping phases. Brain protection integrated with testing workflow.",
            visual_elements=[
                "Whiteboard with traffic light TDD cycle diagram",
                "RED circle: failing test (must fail first)",
                "GREEN circle: minimal implementation (make it pass)",
                "REFACTOR circle: cleanup (maintain quality)",
                "Arrows showing mandatory sequence, no shortcuts",
                "G's apparition nodding approval in background",
                "Code example showing test-first development",
                "SKULL rules integrated with TDD enforcement"
            ],
            mood="Educational, disciplined, systematic approach",
            placement_type=PlacementType.TECHNICAL_DIAGRAM,
            sequence=1
        ))
        
        beats.append(NarrativeBeat(
            chapter="ch07",
            title="Test Coverage Validation",
            narrative_anchor="'Every. Single. Module. Tested.'",
            scene_description="Screen showing test coverage report: 81.4% coverage with per-layer breakdown. Mr. Codenstein pointing at metrics with satisfaction. Visual: color-coded coverage map (green=covered, red=gaps), testing pyramid showing unit/integration/e2e distribution.",
            visual_elements=[
                "Coverage report: 81.4% overall, per-layer breakdown visible",
                "Color-coded file coverage map (green high, yellow medium, red gaps)",
                "Testing pyramid diagram: unit > integration > e2e",
                "Mr. Codenstein pointing at metrics, proud expression",
                "Terminal showing pytest output: all tests passing",
                "Brain protection rule: TDD_ENFORCEMENT highlighted"
            ],
            mood="Achievement, validation, quality metrics",
            placement_type=PlacementType.KEY_MOMENT,
            sequence=2
        ))
        
        # CHAPTER 8: Cross-Platform Nightmare
        beats.append(NarrativeBeat(
            chapter="ch08",
            title="Windows vs Mac Path Chaos",
            narrative_anchor="'Path separators are broken. Windows uses backslashes, Mac uses forward slashes.'",
            scene_description="Split screen showing same code failing on Mac vs working on Windows. Visual representation of path separator chaos: backslashes and forward slashes tangled like spaghetti. Mr. Codenstein facepalming at obvious oversight.",
            visual_elements=[
                "Split screen: Windows (working) vs Mac (broken)",
                "Path separators visualized: backslash vs forward slash chaos",
                "Error messages on Mac side showing path failures",
                "Mr. Codenstein facepalming, classic developer mistake",
                "Real G in doorway: 'You built a brain that only works in New Jersey?'",
                "Whiteboard: platform differences (Windows/Mac/Linux)"
            ],
            mood="Comedic failure, cross-platform nightmare, oversight",
            placement_type=PlacementType.COMEDIC_SCENE,
            sequence=1
        ))
        
        # CHAPTER 9: System Maintenance (MAJOR NEW FEATURE)
        beats.append(NarrativeBeat(
            chapter="ch09",
            title="The Maintenance Orchestrator",
            narrative_anchor="'Six phases. Automated health checks. Self-healing.'",
            scene_description="Whiteboard showing six-phase System Maintenance workflow: Healthcheck → Align (auto-fix) → Cleanup → Optimize → Refresh → Healthcheck. Mr. Codenstein designing automated maintenance system. G's apparition observing: 'You're teaching it to maintain itself.'",
            visual_elements=[
                "Whiteboard with six-phase maintenance cycle diagram",
                "Phases labeled: Healthcheck, Align, Cleanup, Optimize, Refresh, Validate",
                "Arrows showing automated workflow progression",
                "Auto-fix engine highlighted (self-healing capability)",
                "Mr. Codenstein drawing with multiple colors for phase types",
                "G's apparition: impressed expression, arms crossed",
                "Terminal showing 'system maintenance' command output"
            ],
            mood="Systematic, self-healing, architectural maturity",
            placement_type=PlacementType.TECHNICAL_DIAGRAM,
            sequence=1
        ))
        
        beats.append(NarrativeBeat(
            chapter="ch09",
            title="Alignment Auto-Fix Success",
            narrative_anchor="'It fixed itself. Automatically. Without asking.'",
            scene_description="Screen showing System Maintenance output: alignment phase detecting and auto-fixing 12 issues (missing files, broken links, outdated metrics). Mr. Codenstein watching in amazement as CORTEX self-heals. Visual progress bars, green checkmarks appearing automatically.",
            visual_elements=[
                "Terminal output: alignment phase running",
                "Issues detected: 12 problems found",
                "Auto-fixes applied: green checkmarks appearing sequentially",
                "Progress bars: file restoration, link repair, metric updates",
                "Mr. Codenstein's amazed expression: 'it's maintaining itself'",
                "Performance metrics: before/after comparison showing improvement",
                "Self-healing architecture concept visualization"
            ],
            mood="Triumph, automation success, system maturity",
            placement_type=PlacementType.KEY_MOMENT,
            sequence=2
        ))
        
        # CHAPTER 10: The Awakening
        beats.append(NarrativeBeat(
            chapter="ch10",
            title="Personality Emergence",
            narrative_anchor="'It's not just remembering. It's... learning who I am.'",
            scene_description="Mr. Codenstein staring at CORTEX response that includes personalized suggestions based on his patterns: 'I noticed you tend to forget error handling until testing—would you like me to include that proactively?' Moment of realization: CORTEX has developed understanding of user personality.",
            visual_elements=[
                "Screen showing CORTEX's personalized response",
                "Highlighted text: 'I noticed you tend to...' (personality awareness)",
                "Mr. Codenstein's face: wonder and slight unease",
                "Background: six months of data/patterns visualized as connection web",
                "G's apparition appearing: 'It knows you' expression",
                "Hebbian learning visualization: patterns strengthening over time"
            ],
            mood="Wonder, emergence, consciousness threshold, slight unease",
            placement_type=PlacementType.KEY_MOMENT,
            sequence=1
        ))
        
        beats.append(NarrativeBeat(
            chapter="ch10",
            title="The First Real Demo",
            narrative_anchor="'User asks to implement authentication,' he narrated, typing the request.",
            scene_description="Mr. Codenstein demonstrating CORTEX to Real G in evening (not 2AM!). Screen shows CORTEX remembering three previous conversations and proactively suggesting error handling. Real G laughing: 'It knows you.' Warm moment of validation after six months work.",
            visual_elements=[
                "Evening lighting (not late night, progress!)",
                "Real G sitting beside him, watching demo",
                "Screen: CORTEX response referencing JWT discussion, security concerns, database structure",
                "Three conversation threads visualized connecting to current request",
                "G's genuine laugh/smile, proud expression",
                "Mr. Codenstein explaining features, confident posture",
                "Basement lab looking more organized (maturity visual)"
            ],
            mood="Validation, partnership, achievement, warmth",
            placement_type=PlacementType.KEY_MOMENT,
            sequence=2
        ))
        
        # CHAPTER 11: The 3.0 Revolution (Planning System 2.0 & Future)
        beats.append(NarrativeBeat(
            chapter="ch11",
            title="The Beautiful Documentation",
            narrative_anchor="'The documentation is beautiful.'",
            scene_description="Miss G's apparition studying GitHub Pages site at 11:47 PM (not 2:17 AM, progress!). Screen shows glassmorphism design, feature cards, SKULL Rulebook showcase. Fifteen professional pages. G genuinely surprised by quality. Visual: documentation as product, not afterthought.",
            visual_elements=[
                "Screen showing GitHub Pages landing page (glassmorphism)",
                "Six feature cards with glass effects, gradient hero",
                "Miss G's apparition: genuine surprise expression",
                "Clock: 11:47 PM (earlier than usual, maturity)",
                "Dark mode, responsive design visible",
                "SKULL Rulebook page open (prominent showcase)",
                "Mr. Codenstein proud but humble expression"
            ],
            mood="Professional achievement, documentation as art, maturity",
            placement_type=PlacementType.KEY_MOMENT,
            sequence=1
        ))
        
        beats.append(NarrativeBeat(
            chapter="ch11",
            title="Planning System 2.0 Vision",
            narrative_anchor="'Phase 2 is about making CORTEX real.'",
            scene_description="Whiteboard showing Planning System 2.0 architecture: incremental planning with DoR/DoD gates, TDD integration, ADO compatibility. Mr. Codenstein explaining next evolution to Miss G. Visual: roadmap from basement project to production system.",
            visual_elements=[
                "Whiteboard: Planning System 2.0 flowchart",
                "DoR/DoD gates as checkpoints in workflow",
                "TDD integration (RED-GREEN-REFACTOR) embedded in planning",
                "ADO Operations branch showing enterprise integration",
                "Miss G's apparition listening, engaged expression",
                "Metrics visible: 87ms latency, 81.4% coverage, 12.3% churn",
                "Evolution visual: basement → production system"
            ],
            mood="Vision, roadmap, next evolution, scale",
            placement_type=PlacementType.TECHNICAL_DIAGRAM,
            sequence=2
        ))
        
        # EPILOGUE: Six Months Later
        beats.append(NarrativeBeat(
            chapter="epilogue",
            title="Where Are They Now",
            narrative_anchor="Six months later, the basement laboratory looked different.",
            scene_description="Epilogue montage: organized basement (still technical but less chaotic), Mr. Codenstein working at reasonable hour with Real G bringing actual dinner (not coffee). Monitor showing CORTEX helping other developers. Coffee mugs reduced to reasonable number. Visual: progress, sustainability, success.",
            visual_elements=[
                "Organized basement: still technical but mature",
                "Reasonable number of coffee mugs (5-7, not 17)",
                "Clock showing 8 PM (reasonable hour!)",
                "Real G bringing dinner plate (not coffee)",
                "Screen: CORTEX helping multiple users (adoption visual)",
                "Whiteboard: clean diagrams, no frantic arrows",
                "Both looking satisfied, sustainable work-life balance"
            ],
            mood="Resolution, sustainability, success, healthy balance",
            placement_type=PlacementType.CHAPTER_OPENING,
            sequence=1
        ))
        
        # VALIDATION: Ensure 20-30 total beats
        print(f"Generated {len(beats)} narrative beats for illustration")
        print(f"Coverage: {len(set(b.chapter for b in beats))} chapters")
        
        # Category breakdown
        by_type = {}
        for beat in beats:
            type_name = beat.placement_type.value
            by_type[type_name] = by_type.get(type_name, 0) + 1
        
        print(f"\nBreakdown by type:")
        for type_name, count in sorted(by_type.items()):
            print(f"  {type_name}: {count}")
        
        return beats
    
    def generate_prompt(self, beat: NarrativeBeat) -> DALLEPrompt:
        """
        Create structured DALL-E prompt from narrative beat.
        
        Args:
            beat: Narrative moment to illustrate
            
        Returns:
            Complete DALL-E prompt with metadata
        """
        # Build filename from convention
        filename = f"cortex-awakening-{beat.chapter}-{beat.sequence:02d}.png"
        
        # Construct DALL-E prompt with specific visual details
        prompt_parts = [
            f"Digital illustration: {beat.scene_description}",
            f"\n\nMood: {beat.mood}",
            f"\n\nKey visual elements:",
        ]
        
        for elem in beat.visual_elements:
            prompt_parts.append(f"- {elem}")
        
        prompt_parts.append(f"\n\nStyle: {self.STYLE_GUIDE.strip()}")
        
        prompt_text = "\n".join(prompt_parts)
        
        return DALLEPrompt(
            filename=filename,
            beat=beat,
            prompt_text=prompt_text,
            style_guide=self.STYLE_GUIDE.strip(),
            technical_notes=self.TECHNICAL_NOTES.strip()
        )
    
    def export_prompts(self, prompts: List[DALLEPrompt]) -> Dict[str, int]:
        """
        Save all prompts to output directory.
        
        Args:
            prompts: Generated DALL-E prompts
            
        Returns:
            Statistics (files created, chapters covered, etc.)
        """
        stats = {
            "total_prompts": len(prompts),
            "chapters_covered": len(set(p.beat.chapter for p in prompts)),
            "chapter_openings": sum(1 for p in prompts if p.beat.placement_type == PlacementType.CHAPTER_OPENING),
            "key_moments": sum(1 for p in prompts if p.beat.placement_type == PlacementType.KEY_MOMENT),
            "character_intros": sum(1 for p in prompts if p.beat.placement_type == PlacementType.CHARACTER_INTRO),
            "comedic_scenes": sum(1 for p in prompts if p.beat.placement_type == PlacementType.COMEDIC_SCENE),
            "technical_diagrams": sum(1 for p in prompts if p.beat.placement_type == PlacementType.TECHNICAL_DIAGRAM),
        }
        
        # Save individual prompt files
        for prompt in prompts:
            prompt_file = self.output_dir / f"{prompt.filename.replace('.png', '.txt')}"
            prompt_file.write_text(prompt.to_file_content(), encoding='utf-8')
        
        # Save master catalog with all filenames (for Phase 2 reference)
        catalog_lines = [
            "# CORTEX Story Illustration Catalog",
            "# Generated DALL-E prompts with filenames for story reference",
            "",
            "## Quick Reference",
            f"Total illustrations: {stats['total_prompts']}",
            f"Chapters covered: {stats['chapters_covered']}",
            "",
            "## Filenames by Chapter",
            ""
        ]
        
        current_chapter = None
        for prompt in sorted(prompts, key=lambda p: (p.beat.chapter, p.beat.sequence)):
            if prompt.beat.chapter != current_chapter:
                current_chapter = prompt.beat.chapter
                catalog_lines.append(f"\n### {prompt.beat.chapter.upper()}")
            
            catalog_lines.append(f"- `{prompt.filename}` - {prompt.beat.title} ({prompt.beat.placement_type.value})")
        
        catalog_lines.append("\n## Usage in Story")
        catalog_lines.append("```markdown")
        catalog_lines.append("![{beat.title}](illustrations/images/{filename})")
        catalog_lines.append("```")
        
        catalog_file = self.output_dir / "ILLUSTRATION-CATALOG.md"
        catalog_file.write_text("\n".join(catalog_lines), encoding='utf-8')
        
        print(f"\n✅ Exported {stats['total_prompts']} prompts to {self.output_dir}")
        print(f"   Chapters: {stats['chapters_covered']}")
        print(f"   Chapter Openings: {stats['chapter_openings']}")
        print(f"   Key Moments: {stats['key_moments']}")
        print(f"   Character Intros: {stats['character_intros']}")
        print(f"   Comedic Scenes: {stats['comedic_scenes']}")
        print(f"   Technical Diagrams: {stats['technical_diagrams']}")
        
        return stats
    
    def run(self) -> Dict[str, int]:
        """
        Execute full prompt generation workflow.
        
        Returns:
            Statistics about generated prompts
        """
        print("🎨 DALL-E Prompt Generator - Pre-Phase Execution")
        print("=" * 60)
        print(f"Analyzing: {self.master_file.name}")
        print(f"Output: {self.output_dir}")
        print()
        
        # Step 1: Analyze story structure
        print("📖 Analyzing story structure...")
        beats = self.analyze_story_structure()
        print(f"   Found {len(beats)} narrative beats for illustration")
        
        # Step 2: Generate prompts
        print("\n✍️  Generating DALL-E prompts...")
        prompts = [self.generate_prompt(beat) for beat in beats]
        print(f"   Created {len(prompts)} structured prompts")
        
        # Step 3: Export everything
        print("\n💾 Exporting prompts...")
        stats = self.export_prompts(prompts)
        
        print("\n✅ DALL-E Prompt Generation Complete!")
        print(f"   All image filenames now known for Phase 2 story updates")
        print(f"   No backtracking needed - references can be written correctly first time")
        
        return stats


# CLI entry point for testing
if __name__ == "__main__":
    from pathlib import Path
from src.utils.resource_resolver import get_root_path
    
    # Paths
    cortex_root = get_root_path().parent.parent
    master_file = cortex_root / "cortex-brain" / "documents" / "narratives" / "THE-AWAKENING-OF-CORTEX-MASTER.md"
    output_dir = cortex_root / "docs" / "story" / "illustrations" / "prompts"
    
    # Run generator
    generator = DALLEPromptGenerator(master_file, output_dir)
    stats = generator.run()
    
    print("\n" + "=" * 60)
    print("NEXT STEPS:")
    print("1. Review prompts in docs/story/illustrations/prompts/")
    print("2. Use DALL-E 3 to generate images (20-30 PNGs)")
    print("3. Save images to docs/story/illustrations/images/")
    print("4. Proceed to Phase 2 content generation (filenames already known)")
