#!/usr/bin/env python3
"""
CLI Wrapper Generator for CORTEX Toolkit Utilities.

Auto-generates CLI wrapper scripts for all utilities with:
- Proper imports and error handling
- Audit logging integration
- Help text and usage documentation
- Exit code propagation

Part of Phase P05.4: CLI Wrapper Generation.
"""

from pathlib import Path
from typing import List
import importlib.util

# Import ScriptsUtilitiesManager
spec = importlib.util.spec_from_file_location(
    'manager',
    Path(__file__).parent.parent / 'core' / 'scripts_utilities_manager.py'
)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
ScriptsUtilitiesManager = module.ScriptsUtilitiesManager


def generate_cli_wrapper(utility_name: str, category: str, description: str) -> str:
    """Generate CLI wrapper script content."""
    return f'''#!/usr/bin/env python3
"""
CLI Wrapper for {utility_name}

Category: {category}
Description: {description}

Auto-generated by cortex-toolkit CLI Wrapper Generator.
"""

import sys
from pathlib import Path

# Add project root to path
current = Path(__file__).resolve()
for parent in [current.parent] + list(current.parents):
    if (parent / "cortex.config.json").exists():
        project_root = parent
        sys.path.insert(0, str(project_root))
        break

try:
    # Import ScriptsUtilitiesManager for audit logging
    from cortex_toolkit.core.scripts_utilities_manager import ScriptsUtilitiesManager
    
    # Initialize manager
    manager = ScriptsUtilitiesManager()
    
    # Execute utility with audit logging
    exit_code, stdout, stderr = manager.execute_utility(
        utility_name="{utility_name}",
        args=sys.argv[1:],  # Forward all CLI arguments
    )
    
    # Print output
    if stdout:
        print(stdout, end='')
    if stderr:
        print(stderr, end='', file=sys.stderr)
    
    # Exit with utility's exit code
    sys.exit(exit_code)

except ImportError as e:
    print(f"Error: Cannot import ScriptsUtilitiesManager: {{e}}", file=sys.stderr)
    print("Falling back to direct execution...", file=sys.stderr)
    
    # Fallback: direct execution without audit logging
    import subprocess
    utility_path = project_root / "cortex-toolkit" / "scripts-utilities" / "{category}" / "{utility_name}.py"
    
    if not utility_path.exists():
        print(f"Error: Utility not found: {{utility_path}}", file=sys.stderr)
        sys.exit(1)
    
    result = subprocess.run(
        ["python3", str(utility_path)] + sys.argv[1:],
        capture_output=False
    )
    sys.exit(result.returncode)

except Exception as e:
    print(f"Error executing {utility_name}: {{e}}", file=sys.stderr)
    sys.exit(1)
'''


def generate_all_wrappers():
    """Generate CLI wrappers for all utilities."""
    # Detect project root
    current = Path(__file__).resolve()
    for parent in [current.parent] + list(current.parents):
        if (parent / "cortex.config.json").exists():
            project_root = parent
            break
    else:
        project_root = current.parent.parent.parent
    
    # Initialize manager
    manager = ScriptsUtilitiesManager(
        scripts_dir=str(project_root / "scripts" / "utilities"),
        toolkit_dir=str(project_root / "cortex-toolkit" / "scripts-utilities")
    )
    
    # Discover utilities
    utilities = manager.discover_utilities()
    print(f"🔍 Discovered {len(utilities)} utilities\n")
    
    # Create wrappers directory
    wrappers_dir = project_root / "cortex-toolkit" / "cli" / "wrappers"
    wrappers_dir.mkdir(parents=True, exist_ok=True)
    
    # Generate wrappers
    generated_count = 0
    for util in utilities:
        wrapper_name = f"cortex-{util.name}"
        wrapper_path = wrappers_dir / wrapper_name
        
        # Generate wrapper content
        content = generate_cli_wrapper(
            utility_name=util.name,
            category=util.category,
            description=util.description
        )
        
        # Write wrapper file
        wrapper_path.write_text(content)
        wrapper_path.chmod(0o755)  # Make executable
        
        print(f"✅ Generated: {wrapper_name} ({util.category})")
        generated_count += 1
    
    print(f"\n✅ CLI wrapper generation complete: {generated_count} wrappers")
    print(f"📁 Location: {wrappers_dir}")
    print(f"\n💡 Usage: cortex-toolkit/cli/wrappers/cortex-<utility-name> [args...]")


if __name__ == "__main__":
    generate_all_wrappers()
