sequenceDiagram
    user Client
    user XUpdateTransactionBatch
    user Database

    Client->>+XUpdateTransactionBatch: Execute
    XUpdateTransactionBatch->>XUpdateTransactionBatch: Validate Inputs
    XUpdateTransactionBatch->>XUpdateTransactionBatch: transactionBatch_equals_null
    XUpdateTransactionBatch->>XUpdateTransactionBatch: stringIsNullOrEmptyTransactionCash
    XUpdateTransactionBatch->>+Database: SELECT TransactionBatch
    Database-->>-XUpdateTransactionBatch: Result
    XUpdateTransactionBatch->>+Database: SELECT CashInOut
    Database-->>-XUpdateTransactionBatch: Result
    XUpdateTransactionBatch-->>-Client: Success
