flowchart TD
    Start([manager_report_orchestrator])

    Init[Initialize ManagerReportOrchestrator]
    Start --> Init

    M0[  Init  ]
    Init --> M0
    M1[Generate Report]
    M0 --> M1

    M5 --> End([Complete])