classDiagram
    class XGenerateTransactionInvoice {
        +Execute
    }
    class IoC
    XGenerateTransactionInvoice --> IoC
    class Utilities
    XGenerateTransactionInvoice --> Utilities
    class Abstractions
    XGenerateTransactionInvoice --> Abstractions
    class Paragon
    XGenerateTransactionInvoice --> Paragon
