"""
Unit tests for TechStackMapper and StalenessChecker.

CORE Rules:
- CORE-008: TDD (tests before code) ✅
"""

import pytest
from pathlib import Path

from cortex.brain.knowledge.tech_stack_mapper import TechStackMapper, ImportMapping
from cortex.brain.knowledge.staleness_checker import StalenessChecker, StalenessReport


class TestTechStackMapper:
    """Test TechStackMapper class."""

    @pytest.fixture
    def mapper(self):
        """Create mapper with defaults (skip config file)."""
        mapper = TechStackMapper()
        return mapper

    def test_mapper_loads_defaults(self, mapper):
        """Mapper should load default mappings."""
        assert len(mapper.mappings) > 0
        assert "fastapi" in mapper.mappings
        assert "pytest" in mapper.mappings
        assert "sqlalchemy" in mapper.mappings

    def test_map_single_import(self, mapper):
        """Mapper should map single import."""
        result = mapper.map_imports(["fastapi"])

        assert len(result) == 1
        import_name, categories, confidence = result[0]
        assert import_name == "fastapi"
        assert "fastapi" in categories
        assert "rest-api" in categories
        assert confidence > 0.9

    def test_map_multiple_imports(self, mapper):
        """Mapper should map multiple imports."""
        imports = ["fastapi", "pydantic", "pytest"]
        result = mapper.map_imports(imports)

        assert len(result) == 3
        import_names = [r[0] for r in result]
        assert set(import_names) == set(imports)

    def test_fuzzy_match_submodule(self, mapper):
        """Mapper should fuzzy-match submodule imports."""
        result = mapper.map_imports(["fastapi.security"])

        assert len(result) == 1
        import_name, categories, confidence = result[0]
        assert import_name == "fastapi.security"
        assert "fastapi" in categories
        # Confidence should be lower for fuzzy match
        assert confidence < 0.95

    def test_get_categories_for_intent(self, mapper):
        """Mapper should get combined categories for intent."""
        imports = ["fastapi", "pydantic", "pytest"]
        categories = mapper.get_categories_for_intent(imports)

        assert len(categories) > 0
        # Should include categories from all imports
        expected = {"fastapi", "pydantic", "pytest", "testing", "tdd", "validation"}
        assert len(set(categories) & expected) > 0

    def test_get_missing_categories(self, mapper):
        """Mapper should identify missing categories."""
        imports = ["fastapi", "sqlalchemy"]
        loaded_yamls = ["fastapi-security.yaml"]

        missing = mapper.get_missing_categories(imports, loaded_yamls)

        assert len(missing) > 0
        # sqlalchemy should be in missing
        assert any("sql" in m.lower() for m in missing)

    def test_empty_imports(self, mapper):
        """Mapper should handle empty imports list."""
        result = mapper.map_imports([])
        assert result == []

    def test_unknown_import(self, mapper):
        """Mapper should skip unknown imports gracefully."""
        result = mapper.map_imports(["unknown_package_xyz_123"])
        # Should return empty list (no match)
        assert result == []


class TestStalenessChecker:
    """Test StalenessChecker class."""

    @pytest.fixture
    def checker(self):
        """Create checker."""
        return StalenessChecker()

    def test_checker_initialization(self, checker):
        """Checker should initialize with TechStackMapper."""
        assert checker.tech_mapper is not None

    def test_check_staleness_no_missing(self, checker):
        """Checker should return INFO when all tech is documented."""
        ast_imports = ["fastapi", "pydantic"]
        # Include all categories generated by these imports
        loaded_yamls = [
            "cortex/knowledge/async.yaml",
            "cortex/knowledge/data-validation.yaml",
            "cortex/knowledge/fastapi.yaml",
            "cortex/knowledge/pydantic.yaml",
            "cortex/knowledge/python-web.yaml",
            "cortex/knowledge/rest-api.yaml",
            "cortex/knowledge/serialization.yaml",
            "cortex/knowledge/type-hints.yaml",
        ]

        report = checker.check_staleness(ast_imports, loaded_yamls)

        assert report.severity == "INFO"
        assert len(report.missing_tech) == 0

    def test_check_staleness_with_missing(self, checker):
        """Checker should return WARNING when tech is missing."""
        ast_imports = ["fastapi", "sqlalchemy"]
        loaded_yamls = ["cortex/knowledge/fastapi.yaml"]

        report = checker.check_staleness(ast_imports, loaded_yamls)

        assert report.severity == "WARNING"
        assert len(report.missing_tech) > 0
        assert len(report.recommendations) > 0

    def test_check_staleness_force_critical(self, checker):
        """Checker should respect force_critical flag."""
        ast_imports = ["fastapi"]
        loaded_yamls = ["cortex/knowledge/fastapi.yaml"]

        report = checker.check_staleness(
            ast_imports, loaded_yamls, force_critical=True
        )

        assert report.severity == "CRITICAL"

    def test_staleness_report_to_dict(self, checker):
        """StalenessReport should convert to dict."""
        ast_imports = ["fastapi"]
        loaded_yamls = []

        report = checker.check_staleness(ast_imports, loaded_yamls)
        report_dict = report.to_dict()

        assert "detected_tech" in report_dict
        assert "missing_tech" in report_dict
        assert "recommendations" in report_dict
        assert "severity" in report_dict

    def test_staleness_report_is_critical(self):
        """StalenessReport should report criticality."""
        report = StalenessReport(severity="CRITICAL")
        assert report.is_critical() is True
        assert report.is_warning() is False

        report2 = StalenessReport(severity="WARNING")
        assert report2.is_warning() is True
        assert report2.is_critical() is False

    def test_recommend_yaml_updates(self, checker):
        """Checker should recommend YAML updates."""
        ast_imports = ["fastapi", "sqlalchemy"]
        loaded_yamls = ["fastapi.yaml"]

        report = checker.check_staleness(ast_imports, loaded_yamls)
        recommendations = checker.recommend_yaml_updates(report)

        assert len(recommendations) > 0
        # Should recommend creating YAML for missing tech
        assert any("sqlalchemy" in rec for rec in recommendations)

    def test_check_staleness_empty_imports(self, checker):
        """Checker should handle empty imports."""
        report = checker.check_staleness([], [])

        assert report.severity in ["INFO", "WARNING"]
        assert len(report.detected_tech) == 0

    def test_check_staleness_handles_failure(self, checker):
        """Checker should gracefully handle failures."""
        # Mock the mapper to raise exception
        checker.tech_mapper.get_categories_for_intent = Mock(
            side_effect=ValueError("Mapper failed")
        )

        report = checker.check_staleness(["fastapi"], [])

        assert report.severity == "WARNING"
        assert "failed" in str(report.recommendations).lower()


# Import Mock for the failure test
from unittest.mock import Mock
