#!/bin/bash

##############################################################################
# CORTEX Repository Registration Script
# AC-DEPLOY-ENHANCED-003-01: Automated repo registration and setup
#
# Usage: ./register-repo.sh /path/to/repo
#
# This script performs one-time setup for CORTEX deployment in any repo:
# 1. Creates cortex-config.yaml with repo metadata
# 2. Sets up .github/prompts directory with symlinks (macOS/Linux) or copies (Windows)
# 3. Creates .github/tier0 stub for local governance
# 4. Validates MCP connectivity
# 5. Creates git commit with audit entry
#
# Idempotent: Safe to run multiple times
# Cross-platform: Handles symlinks and copies based on OS
##############################################################################

set -euo pipefail

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Global variables
REPO_ROOT="${1:-.}"
CORTEX_HUB="/Users/asifhussain/PROJECTS/CORTEX"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

##############################################################################
# Helper Functions
##############################################################################

print_info() {
    echo -e "${BLUE}ℹ ${1}${NC}"
}

print_success() {
    echo -e "${GREEN}✓ ${1}${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ ${1}${NC}"
}

print_error() {
    echo -e "${RED}✗ ${1}${NC}"
}

##############################################################################
# Validation Functions
##############################################################################

validate_repo_root() {
    # Check if REPO_ROOT is provided
    if [[ -z "$REPO_ROOT" ]] || [[ "$REPO_ROOT" == "." ]]; then
        if [[ ! -d .git ]]; then
            print_error "Not a git repository or REPO_ROOT not specified"
            echo "Usage: $0 /path/to/repo" >&2
            exit 1
        fi
        REPO_ROOT="$(pwd)"
    fi

    # Resolve to absolute path
    REPO_ROOT="$(cd "$REPO_ROOT" 2>/dev/null && pwd)" || {
        print_error "Repository path does not exist: $REPO_ROOT"
        exit 1
    }

    # Check if it's a git repo
    if [[ ! -d "$REPO_ROOT/.git" ]]; then
        print_error "Not a git repository: $REPO_ROOT"
        exit 1
    fi

    print_success "Repository validated: $REPO_ROOT"
}

derive_repo_id() {
    # Try to derive repo_id from git remote origin URL
    local repo_id
    
    repo_id=$(cd "$REPO_ROOT" && git config --get remote.origin.url 2>/dev/null || echo "")
    
    if [[ -n "$repo_id" ]]; then
        # Extract repo name from URL (e.g., git@github.com:org/repo.git → repo)
        repo_id=$(basename "$repo_id" .git)
        repo_id="${repo_id##*/}"
    else
        # Fall back to directory name
        repo_id=$(basename "$REPO_ROOT")
    fi
    
    # Sanitize: lowercase, replace spaces with hyphens
    repo_id=$(echo "$repo_id" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g')
    
    echo "$repo_id"
}

derive_repo_name() {
    local repo_name
    repo_name=$(basename "$REPO_ROOT")
    repo_name=$(echo "$repo_name" | tr '-' ' ' | sed 's/\b\(.\)/\u\1/g')
    echo "$repo_name"
}

##############################################################################
# Configuration File Functions
##############################################################################

create_cortex_config() {
    local config_file="$REPO_ROOT/cortex-config.yaml"
    
    # Skip if already exists
    if [[ -f "$config_file" ]]; then
        print_warning "cortex-config.yaml already exists, skipping creation"
        return 0
    fi

    print_info "Creating cortex-config.yaml..."
    
    local repo_id=$(derive_repo_id)
    local repo_name=$(derive_repo_name)
    local mcp_endpoint="${CORTEX_MCP_ENDPOINT:-http://127.0.0.1:8000}"
    
    cat > "$config_file" << EOF
# CORTEX Repository Configuration
# Generated by register-repo.sh on $(date -u +'%Y-%m-%dT%H:%M:%SZ')

# Repository Metadata
repo_id: "$repo_id"
repo_name: "$repo_name"
repo_type: "source"  # source, orchestrator, tool, or knowledge

# CORTEX Hub Configuration
mcp_endpoint: "$mcp_endpoint"
mcp_health_check_interval_seconds: 30
mcp_timeout_seconds: 10

# Version Management
version: "1.0.0"
min_hub_version: "1.0.0"

# Governance Configuration
governance_enabled: true
audit_trail_enabled: true
isolation_mode: "strict"  # strict, moderate, or permissive

# Offline Mode
offline_mode_enabled: false
offline_queue_max_items: 1000

# Feature Flags
enable_version_negotiation: true
enable_cross_repo_access: false

# Metadata
description: "Repository registered with CORTEX deployment system"
registered_at: $(date -u +'%Y-%m-%dT%H:%M:%SZ')
EOF

    print_success "cortex-config.yaml created"
}

##############################################################################
# Directory Setup Functions
##############################################################################

setup_prompts_directory() {
    local prompts_dir="$REPO_ROOT/.github/prompts"
    local source_prompts="$CORTEX_HUB/cortex_brain/tier1"
    
    # Create .github directory if needed
    mkdir -p "$REPO_ROOT/.github"
    
    # Skip if prompts directory already exists
    if [[ -d "$prompts_dir" ]]; then
        print_warning ".github/prompts directory already exists, skipping setup"
        return 0
    fi

    print_info "Setting up .github/prompts directory..."
    mkdir -p "$prompts_dir"
    
    # Use symlinks on macOS/Linux, copies on Windows
    if [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]]; then
        # Windows: copy files
        if [[ -d "$source_prompts" ]]; then
            cp -r "$source_prompts"/*.md "$prompts_dir/" 2>/dev/null || true
            cp -r "$source_prompts"/*.yaml "$prompts_dir/" 2>/dev/null || true
        fi
        print_success "Prompts copied to .github/prompts (Windows mode)"
    else
        # macOS/Linux: create symlinks
        if [[ -d "$source_prompts" ]]; then
            for file in "$source_prompts"/*.md "$source_prompts"/*.yaml; do
                if [[ -f "$file" ]]; then
                    ln -sf "$file" "$prompts_dir/$(basename "$file")"
                fi
            done
            print_success "Prompts symlinked in .github/prompts (Unix mode)"
        else
            print_warning "Source prompts directory not found: $source_prompts"
        fi
    fi
    
    # Create a fallback prompt if none exist
    if [[ -z "$(ls "$prompts_dir" 2>/dev/null)" ]]; then
        cat > "$prompts_dir/CORTEX-SYSTEM-PROMPT.md" << 'EOF'
# CORTEX System Prompt

This repository is registered with the CORTEX governance system.

## Governance Rules
- All pull requests undergo governance validation
- Prompt compliance is mandatory
- Audit trail is maintained for all operations

## Hub Reference
- MCP Endpoint: See ../cortex-config.yaml
- Hub Documentation: Reference tier0 governance structure

## Next Steps
1. Review cortex-config.yaml for hub endpoint
2. Run tests to validate integration
3. Check .github/tier0 for governance stubs
EOF
        print_success "Created default CORTEX system prompt"
    fi
}

setup_tier0_stub() {
    local tier0_dir="$REPO_ROOT/.github/tier0"
    
    # Skip if already exists
    if [[ -d "$tier0_dir" ]]; then
        print_warning ".github/tier0 already exists, skipping creation"
        return 0
    fi

    print_info "Creating .github/tier0 governance stub..."
    mkdir -p "$tier0_dir"
    
    cat > "$tier0_dir/README.md" << EOF
# Local Governance Stub

This directory contains local governance references for the CORTEX deployment system.

## Structure
- This is a **stub** - actual governance rules are in the central hub
- Local rules can override hub defaults (if governance mode permits)
- All changes are audited through the MCP hub

## Hub Reference
See \`cortex-config.yaml\` in the repository root for hub endpoint and configuration.

## Governance Modes
- **strict**: Hub rules are mandatory, no local overrides (default)
- **moderate**: Hub rules + local supplements allowed
- **permissive**: Hub recommendations only

## Getting Started
1. Connect to hub via cortex-config.yaml
2. Review hub governance rules
3. Request local rule changes via hub governance flow

Generated: $(date -u +'%Y-%m-%dT%H:%M:%SZ')
EOF

    print_success ".github/tier0 stub created"
}

##############################################################################
# MCP Connectivity Functions
##############################################################################

validate_mcp_connectivity() {
    local config_file="$REPO_ROOT/cortex-config.yaml"
    local mcp_endpoint
    
    # Extract mcp_endpoint from config
    mcp_endpoint=$(grep "^mcp_endpoint:" "$config_file" | cut -d'"' -f2)
    
    print_info "Validating MCP connectivity to $mcp_endpoint..."
    
    # Try to reach health endpoint
    if command -v curl &> /dev/null; then
        if curl -sf "$mcp_endpoint/health" > /dev/null 2>&1; then
            print_success "MCP hub is reachable"
        else
            print_warning "MCP hub not reachable (offline mode may be enabled)"
        fi
    else
        print_warning "curl not available, skipping MCP connectivity check"
    fi
}

##############################################################################
# Git Functions
##############################################################################

create_git_commit() {
    local repo_id
    repo_id=$(derive_repo_id)
    
    # Check if there are changes to commit
    if ! cd "$REPO_ROOT" && git diff --quiet && git diff --cached --quiet; then
        print_info "No changes to commit"
        return 0
    fi

    print_info "Creating git commit for CORTEX registration..."
    
    # Ensure user is configured
    if ! cd "$REPO_ROOT" && git config user.email > /dev/null; then
        print_warning "Git user not configured, skipping commit"
        print_info "Configure with: git config user.email 'email@example.com' && git config user.name 'Your Name'"
        return 0
    fi

    # Add all CORTEX-related files
    cd "$REPO_ROOT"
    git add -f cortex-config.yaml .github/prompts .github/tier0 2>/dev/null || true

    # Create commit if there are staged changes
    if git diff --cached --quiet; then
        print_info "No staged changes to commit"
    else
        git commit -m "chore(cortex): Initial CORTEX registration and setup

- Create cortex-config.yaml with hub configuration
- Setup .github/prompts with governance prompts
- Create .github/tier0 governance stub
- Enable MCP connectivity and audit trail

Repository ID: $repo_id
Registration Date: $(date -u +'%Y-%m-%dT%H:%M:%SZ')
" || print_warning "Commit creation failed (repository may be in special state)"
        print_success "Git commit created"
    fi
}

##############################################################################
# Main Execution
##############################################################################

main() {
    echo ""
    echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║         CORTEX Repository Registration Script             ║${NC}"
    echo -e "${BLUE}║         AC-DEPLOY-ENHANCED-003-01                         ║${NC}"
    echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""

    # Execute registration steps
    validate_repo_root
    print_info "Starting registration process..."
    
    create_cortex_config
    setup_prompts_directory
    setup_tier0_stub
    validate_mcp_connectivity
    create_git_commit

    echo ""
    echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║      ✓ Repository registration completed successfully     ║${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    
    print_info "Repository: $REPO_ROOT"
    print_info "Config file: $REPO_ROOT/cortex-config.yaml"
    print_info "Next steps:"
    echo "  1. Review cortex-config.yaml for your environment"
    echo "  2. Verify .github/prompts contains governance prompts"
    echo "  3. Test MCP connectivity: curl $(grep mcp_endpoint "$REPO_ROOT/cortex-config.yaml" | cut -d'"' -f2)/health"
    echo "  4. Push changes: git push"
    echo ""
}

# Run main function
main "$@"
