"""
Orchestrator Scaffolder renderers — template rendering functions.

Phase 103-i: extracted from orchestrator_scaffolder.py (1,455L) god-object.
All _render_* methods live here as module-level functions.
"""
from __future__ import annotations

import re
from datetime import datetime
from typing import Any, Dict, List

from cortex.tools.naming_utils import to_class_name, to_module_name, yaml_type_to_python


def render_orchestrator(
    class_name: str,
    template: Any,
    params: List[Dict[str, Any]],
    stages: List[Dict[str, Any]],
    hooks: Dict[str, Any],
    config: Any,
) -> str:
    """Render orchestrator Python code."""
    param_fields = []
    for param in params:
        py_type = yaml_type_to_python(param["type"])
        if not param["required"]:
            py_type = f"Optional[{py_type}]"
        default = param.get("default")
        ds = f" = {repr(default)}" if default is not None else (" = None" if not param["required"] else "")
        param_fields.append(f"    {param['name']}: {py_type}{ds}")
    param_fields_str = "\n".join(param_fields) if param_fields else "    pass"

    stage_methods = []
    stage_dispatch = []
    stage_names = []
    for i, stage in enumerate(stages):
        sn = stage.get("name", f"stage_{i}")
        safe = re.sub(r"[^a-zA-Z0-9_]", "_", sn)
        stage_names.append(sn)
        stage_dispatch.append(f"            '{sn}': self._execute_{safe},")
        stage_methods.append(
            f"    def _execute_{safe}(self, context):\n        self._log_stage_start('{sn}')\n        return None\n\n"
            f"    def _process_{safe}(self, context):\n        return {{'processed': True}}"
        )

    hook_methods = []
    for hook_name in hooks:
        safe = re.sub(r"[^a-zA-Z0-9_]", "_", hook_name)
        hook_methods.append(
            f"    def _hook_{safe}(self, context, **kwargs):\n"
            f"        for cb in self._hooks.get('{hook_name}', []):\n"
            f"            try:\n                cb(context, **kwargs)\n            except Exception: pass"
        )

    stage_list_str = ", ".join(f"'{n}'" for n in stage_names)
    stage_dispatch_str = "\n".join(stage_dispatch)
    stage_methods_str = "\n\n".join(stage_methods)
    hook_methods_str = "\n\n".join(hook_methods)

    return f'''"""
{template.name} Orchestrator
Domain: {template.domain} | Version: {template.version}

{template.description}

Generated by CORTEX OrchestratorScaffolder
Generated at: {datetime.now().isoformat()}
"""

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Callable, Dict, List, Optional
import logging

from cortex.orchestrators.base import BaseOrchestrator, ExecutionContext, ExecutionResult
from cortex.orchestrators.stages import StageResult

logger = logging.getLogger(__name__)


@dataclass
class {class_name}Params:
    """Parameters for {template.name}."""
{param_fields_str}


class {class_name}(BaseOrchestrator):
    """{template.description}"""

    DOMAIN = '{template.domain}'
    VERSION = '{template.version}'
    STAGES = [{stage_list_str}]

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        super().__init__(config)
        self._hooks: Dict[str, List[Callable]] = {{}}
        self._stage_handlers: Dict[str, Callable] = {{
{stage_dispatch_str}
        }}

    @property
    def domain(self) -> str:
        return self.DOMAIN

    @property
    def version(self) -> str:
        return self.VERSION

    def register_hook(self, hook_name: str, callback: Callable) -> None:
        self._hooks.setdefault(hook_name, []).append(callback)

    def unregister_hook(self, hook_name: str, callback: Callable) -> None:
        if hook_name in self._hooks and callback in self._hooks[hook_name]:
            self._hooks[hook_name].remove(callback)

    def execute(self, params, context=None, **kwargs):
        if isinstance(params, dict):
            params = {class_name}Params(**params)
        context = context or ExecutionContext(orchestrator=self.DOMAIN, params=params.__dict__, started_at=datetime.now())
        self._hook_pre_execute(context)
        try:
            results = self._execute_pipeline(context)
            result = ExecutionResult(status='completed', output={{s.stage: s.output for s in results if s and s.output}}, stages=results, context=context)
            self._hook_on_success(context, result=result)
        except Exception as e:
            logger.exception(f"Execution failed: {{e}}")
            result = ExecutionResult(status='failed', error=str(e), context=context)
            self._hook_on_error(context, error=e)
        self._hook_post_execute(context, result=result)
        return result

    def _execute_pipeline(self, context):
        results = []
        for sn in self.STAGES:
            handler = self._stage_handlers.get(sn)
            if handler:
                r = handler(context)
                results.append(r)
                if hasattr(context, 'stage_results'):
                    context.stage_results[sn] = r
        return results

    def _log_stage_start(self, s): logger.info(f"Starting stage: {{s}}")
    def _log_stage_complete(self, s): logger.info(f"Completed stage: {{s}}")
    def _log_stage_error(self, s, e): logger.error(f"Stage {{s}} failed: {{e}}")
    def _log_hook_error(self, h, e): logger.warning(f"Hook {{h}} error: {{e}}")

    def _hook_pre_execute(self, context):
        for cb in self._hooks.get('pre_execute', []):
            try: cb(context)
            except Exception as e: self._log_hook_error('pre_execute', e)

    def _hook_post_execute(self, context, **kwargs):
        for cb in self._hooks.get('post_execute', []):
            try: cb(context, **kwargs)
            except Exception as e: self._log_hook_error('post_execute', e)

    def _hook_on_success(self, context, **kwargs):
        for cb in self._hooks.get('on_success', []):
            try: cb(context, **kwargs)
            except Exception as e: self._log_hook_error('on_success', e)

    def _hook_on_error(self, context, **kwargs):
        for cb in self._hooks.get('on_error', []):
            try: cb(context, **kwargs)
            except Exception as e: self._log_hook_error('on_error', e)

{stage_methods_str}

{hook_methods_str}


def register_orchestrator():
    """Register orchestrator with the CORTEX registry."""
    from cortex.orchestrators.factory import OrchestratorRegistry
    OrchestratorRegistry.register('{template.domain}', {class_name})
'''


def render_tests(
    class_name: str,
    test_class_name: str,
    template: Any,
    params: List[Dict[str, Any]],
    stages: List[Dict[str, Any]],
    config: Any,
) -> str:
    """Render test file."""
    fixtures = []
    for p in params:
        v = p.get("default")
        if v is None:
            t = p["type"]
            if t == "str":
                v = "'test_value'"
            elif t in ("int", "integer"):
                v = "1"
            elif t in ("float", "number"):
                v = "1.0"
            elif t in ("bool", "boolean"):
                v = "True"
            else:
                v = "'test'"
        else:
            v = repr(v)
        fixtures.append(f"        '{p['name']}': {v},")
    fixtures_str = "\n".join(fixtures)

    stage_tests = []
    for i, stage in enumerate(stages):
        sn = stage.get("name", f"stage_{i}")
        safe = re.sub(r"[^a-zA-Z0-9_]", "_", sn)
        stage_tests.append(
            f"    def test_stage_{safe}(self, orchestrator, sample_params):\n"
            f"        result = orchestrator.execute(sample_params)\n        assert result is not None"
        )
    stage_tests_str = "\n\n".join(stage_tests) if stage_tests else "    def test_stages_placeholder(self, orchestrator):\n        pass"

    mod_name = to_module_name(template.name)
    return f'''"""Tests for {template.name} Orchestrator."""
import pytest
from typing import Any, Dict


class {test_class_name}:
    """Tests for {class_name}."""

    @pytest.fixture
    def orchestrator(self):
        from cortex.orchestrators.factory import create_orchestrator
        return create_orchestrator('{template.domain}')

    @pytest.fixture
    def sample_params(self) -> Dict[str, Any]:
        return {{
{fixtures_str}
        }}

    def test_creation(self, orchestrator):
        assert orchestrator is not None

    def test_basic_execution(self, orchestrator, sample_params):
        result = orchestrator.execute(sample_params)
        assert result is not None

{stage_tests_str}


def test_{mod_name}_creation():
    from cortex.orchestrators.factory import create_orchestrator
    orch = create_orchestrator('{template.domain}')
    assert orch is not None
'''


def render_config(template: Any, config: Any) -> str:
    """Render YAML configuration file."""
    mod_name = to_module_name(template.name)
    return f"""# {template.name} Configuration
# Domain: {template.domain} | Version: {template.version}
# Generated by CORTEX OrchestratorScaffolder

orchestrator:
  name: {template.name}
  domain: {template.domain}
  version: {template.version}
  tier: {config.tier}

execution:
  timeout: 30
  retry_count: 3
  continue_on_error: false

logging:
  level: INFO
  format: structured
"""


def render_integrations(
    class_name: str,
    template: Any,
    integrations: Dict[str, Any],
    config: Any,
) -> str:
    """Render integration adapter."""
    methods = []
    for name in integrations:
        safe = re.sub(r"[^a-zA-Z0-9_]", "_", name)
        methods.append(
            f"    def connect_{safe}(self, **kwargs):\n        return self.connect('{name}', **kwargs)"
        )
    methods_str = "\n\n".join(methods)
    return f'"""Integration adapter for {template.name}."""\nfrom typing import Any, Dict\n\n\nclass {class_name}:\n    def __init__(self):\n        self._connections: Dict[str, Any] = {{}}\n\n    def connect(self, name: str, **kwargs):\n        self._connections[name] = kwargs\n        return kwargs\n\n{methods_str}\n'
