"""
CORTEX Templates - Template Manager

Template management, rendering, and content retrieval.

"""

from dataclasses import dataclass
from typing import Dict, List, Any, Optional
import re

from cortex.templates.content_strategy import ContentPopulationStrategy


class TemplateManager:
    """Template manager for content retrieval and rendering.
    
    Manages template content, variable substitution, and rendering.
    """
    
    def __init__(self) -> None:
        """Initialize template manager."""
        self._strategy = ContentPopulationStrategy()
        self._template_content = self._initialize_template_content()
    
    def _initialize_template_content(self) -> Dict[str, str]:
        """Initialize template content.
        
        Returns:
            Dictionary of template ID to content.
        """
        # Get all templates from strategy
        all_templates = {}
        for domain in self._strategy.domains:
            templates = self._strategy.get_domain_templates(domain)
            for template in templates:
                template_id = template['id']
                # Generate generic content for each template
                all_templates[template_id] = self._generate_template_content(template)
        
        return all_templates
    
    def _generate_template_content(self, template: Dict[str, Any]) -> str:
        """Generate template content.
        
        Args:
            template: Template metadata dictionary.
            
        Returns:
            Generated template content.
        """
        template_id = template['id']
        name = template['name']
        description = template['description']
        
        # Generate content based on template ID
        if template_id == 'planning-recommendations':
            return self._get_planning_recommendations_content()
        elif template_id == 'planning-impact-assessment':
            return self._get_planning_impact_assessment_content()
        elif template_id == 'planning-timeline':
            return self._get_planning_timeline_content()
        elif template_id == 'planning-resource-allocation':
            return self._get_planning_resource_allocation_content()
        elif template_id == 'planning-risk-analysis':
            return self._get_planning_risk_analysis_content()
        elif template_id == 'planning-milestone-tracker':
            return self._get_planning_milestone_tracker_content()
        elif template_id == 'planning-dependency-map':
            return self._get_planning_dependency_map_content()
        elif template_id == 'planning-progress-report':
            return self._get_planning_progress_report_content()
        elif template_id == 'planning-roadmap':
            return self._get_planning_roadmap_content()
        elif template_id == 'planning-stakeholder-analysis':
            return self._get_planning_stakeholder_analysis_content()
        elif template_id == 'analysis-gap-assessment':
            return self._get_analysis_gap_assessment_content()
        elif template_id == 'analysis-impact-evaluation':
            return self._get_analysis_impact_evaluation_content()
        elif 'codebase' in template_id or 'code-quality' in template_id:
            return self._get_analysis_codebase_content()
        else:
            # Generic template content
            return f"""# {name}

## Overview
{description}

## Details
{{details}}

## Context
{{context}}

## Recommendations
{{recommendations}}

## Next Steps
{{next_steps}}

---
Generated by CORTEX Template System
"""
    
    def _get_planning_recommendations_content(self) -> str:
        """Get planning recommendations template content."""
        return """# Planning Recommendations: {plan_title}

## Overview
Phase: {phase}
Acceptance Criteria Count: {ac_count}
Estimated Effort: {estimated_hours} hours

## Acceptance Criteria Breakdown
{ac_table}

## Recommendations
{recommendation}

## Dependencies
{dependencies}

## Risk Assessment
{risks}

## Next Steps
1. Review and approve plan
2. Allocate resources
3. Begin implementation

---
Generated by CORTEX Planning Orchestrator
"""
    
    def _get_planning_impact_assessment_content(self) -> str:
        """Get planning impact assessment template content."""
        return """# Impact Assessment: {assessment_title}

## Scope
{scope_description}

## Affected Components
{component_list}

## Impact Analysis
### Technical Impact
{technical_impact}

### Resource Impact
{resource_impact}

### Schedule Impact
{schedule_impact}

## Mitigation Strategies
{mitigation_strategies}

## Approval Status
{approval_status}
"""
    
    def _get_planning_timeline_content(self) -> str:
        """Get planning timeline template content."""
        return """# Timeline: {timeline_title}

## Project Duration
Start Date: {start_date}
End Date: {end_date}
Total Duration: {duration_days} days

## Phase Breakdown
{phase_table}

## Critical Path
{critical_path}

## Milestones
{milestone_list}
"""
    
    def _get_planning_resource_allocation_content(self) -> str:
        """Get planning resource allocation template content."""
        return """# Resource Allocation: {project_title}

## Team Composition
{team_members}

## Resource Distribution
{resource_table}

## Capacity Analysis
{capacity_analysis}

## Budget Allocation
{budget_breakdown}
"""
    
    def _get_planning_risk_analysis_content(self) -> str:
        """Get planning risk analysis template content."""
        return """# Risk Analysis: {project_title}

## Risk Register
{risk_table}

## Risk Matrix
{risk_matrix}

## Mitigation Plans
{mitigation_plans}

## Contingency Plans
{contingency_plans}
"""
    
    def _get_planning_milestone_tracker_content(self) -> str:
        """Get planning milestone tracker template content."""
        return """# Milestone Tracker: {project_title}

## Milestone Status
{milestone_status_table}

## Completion Metrics
- Total Milestones: {total_milestones}
- Completed: {completed_milestones}
- In Progress: {in_progress_milestones}
- Upcoming: {upcoming_milestones}

## Critical Milestones
{critical_milestones}
"""
    
    def _get_planning_dependency_map_content(self) -> str:
        """Get planning dependency map template content."""
        return """# Dependency Map: {project_title}

## Dependency Graph
{dependency_graph}

## Critical Dependencies
{critical_dependencies}

## Blocked Items
{blocked_items}

## Dependency Resolution
{resolution_plan}
"""
    
    def _get_planning_progress_report_content(self) -> str:
        """Get planning progress report template content."""
        return """# Progress Report: {project_title}

## Reporting Period
{report_period}

## Overall Progress
Completion: {completion_percentage}%
Status: {overall_status}

## Accomplishments
{accomplishments}

## Upcoming Work
{upcoming_work}

## Issues and Blockers
{issues_blockers}
"""
    
    def _get_planning_roadmap_content(self) -> str:
        """Get planning roadmap template content."""
        return """# Roadmap: {roadmap_title}

## Vision
{vision_statement}

## Strategic Goals
{strategic_goals}

## Phase Overview
{phase_overview}

## Timeline
{timeline_visualization}
"""
    
    def _get_planning_stakeholder_analysis_content(self) -> str:
        """Get planning stakeholder analysis template content."""
        return """# Stakeholder Analysis: {project_title}

## Stakeholder Registry
{stakeholder_table}

## Engagement Plan
{engagement_plan}

## Communication Strategy
{communication_strategy}
"""
    
    def _get_analysis_gap_assessment_content(self) -> str:
        """Get analysis gap assessment template content."""
        return """# Gap Assessment: {assessment_title}

## Current State
{current_state}

## Target State
{target_state}

## Identified Gaps
{gap_table}

## Remediation Plan
{remediation_plan}

## Effort Estimation
{effort_estimation}
"""
    
    def _get_analysis_impact_evaluation_content(self) -> str:
        """Get analysis impact evaluation template content."""
        return """# Impact Evaluation: {evaluation_title}

## Change Description
{change_description}

## Impact Assessment
### System Impact
{system_impact}

### User Impact
{user_impact}

### Performance Impact
{performance_impact}

## Risk Assessment
{risk_assessment}
"""
    
    def _get_analysis_codebase_content(self) -> str:
        """Get analysis codebase template content."""
        return """# Codebase Analysis: {codebase_title}

## Repository Overview
{repository_info}

## Code Metrics
{code_metrics}

## Quality Assessment
{quality_assessment}

## Technical Debt
{technical_debt}

## Recommendations
{recommendations}
"""
    
    def get_domain_templates(self, domain: str) -> List[Dict[str, Any]]:
        """Get templates for a specific domain.
        
        Args:
            domain: Domain name.
            
        Returns:
            List of template dictionaries.
        """
        return self._strategy.get_domain_templates(domain)
    
    def get_template_content(self, template_id: str) -> Optional[str]:
        """Get template content by ID.
        
        Args:
            template_id: Template ID.
            
        Returns:
            Template content or None if not found.
        """
        return self._template_content.get(template_id)
    
    def render_template(self, template_id: str, variables: Dict[str, Any]) -> str:
        """Render template with variables.
        
        Args:
            template_id: Template ID.
            variables: Variables to substitute.
            
        Returns:
            Rendered template content.
            
        Raises:
            ValueError: If template not found or required variables missing.
        """
        content = self.get_template_content(template_id)
        if content is None:
            raise ValueError(f"Template not found: {template_id}")
        
        # Find all variables in template
        required_vars = set(re.findall(r'\{(\w+)\}', content))
        provided_vars = set(variables.keys())
        
        # Check for missing variables
        missing_vars = required_vars - provided_vars
        if missing_vars:
            raise ValueError(f"Missing required variables: {missing_vars}")
        
        # Substitute variables
        rendered = content
        for key, value in variables.items():
            rendered = rendered.replace(f'{{{key}}}', str(value))
        
        return rendered
