<#
.SYNOPSIS
    CORTEX Documentation Organizer - Cleans root-level docs files and updates links

.DESCRIPTION
    Analyzes docs/ folder structure, moves misplaced root-level files to appropriate
    subfolders, updates all link references, and removes unlinked orphaned files.
    
    This script enforces the docs/ organization standard:
    - Root level: index.html, faq.html, sitemap.html, infrastructure files only
    - All content files must be in subfolders
    - All files must be linked from somewhere in the navigation tree

.PARAMETER DryRun
    Preview changes without modifying files (default: $true)

.PARAMETER DeleteOrphans
    Delete files not linked anywhere (default: $false, moves to archive)

.PARAMETER Force
    Skip confirmation prompts

.EXAMPLE
    .\docs-organizer.ps1 -DryRun $true
    # Preview what would be changed

.EXAMPLE
    .\docs-organizer.ps1 -DryRun $false -Force
    # Execute cleanup without prompts

.NOTES
    Version: 1.0.0
    Author: CORTEX Toolkit Manager
    Part of: CORTEX 4.0 Documentation System
#>

[CmdletBinding()]
param(
    [switch]$DryRun = $true,
    [switch]$DeleteOrphans = $false,
    [switch]$Force = $false
)

# ============================================================================
# CONFIGURATION
# ============================================================================

$DocsRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\docs")).Path
$ArchiveDir = Join-Path $DocsRoot "archives\cleanup-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
$ReportPath = Join-Path (Split-Path $PSScriptRoot -Parent) "cortex-brain\documents\reports\docs-cleanup-$(Get-Date -Format 'yyyyMMdd').json"

# Files that MUST stay at root (infrastructure)
$RootWhitelist = @(
    'index.html',
    'faq.html',
    'sitemap.html',
    'search-index.json',
    '404.md',
    'README.md',
    'DEPLOYMENT.md',
    'QUICK-LAUNCH.md',
    '.nojekyll',
    '.deployment-trigger',
    '.trigger'
)

# Files to move with their target folders
$MoveMap = @{
    'dashboard-diagnostic.html' = 'lens/diagnostics/'
    'test-tabs.html' = 'prototypes/'
    'testing-planning-orchestrator.md' = 'development/testing/'
    'visual-differentiation-demo.html' = 'prototypes/'
}

# Patterns for files that should be deleted (not archived)
$DeletePatterns = @(
    '*-old.html',
    '*-backup.html',
    '*-test.html',
    '*.tmp'
)

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

function Write-ColorOutput {
    param(
        [string]$Message,
        [string]$Color = "White",
        [string]$Icon = ""
    )
    $IconText = if ($Icon) { "$Icon " } else { "" }
    Write-Host "$IconText$Message" -ForegroundColor $Color
}

function Get-AllHtmlFiles {
    param([string]$Path)
    Get-ChildItem -Path $Path -Recurse -Filter "*.html" -File
}

function Test-IsStubPage {
    param([string]$FilePath)
    
    if (-not (Test-Path $FilePath)) { return $false }
    
    try {
        $content = Get-Content $FilePath -Raw -ErrorAction SilentlyContinue
        if (-not $content) { return $false }
        
        # Check for stub page markers
        return ($content -match 'stub-container' -or 
                $content -match 'under construction' -or
                $content -match 'Auto-generated by CORTEX Toolkit Manager' -or
                $content -match 'Page Status.*Placeholder')
    } catch {
        return $false
    }
}

function Get-LinksInFile {
    param([string]$FilePath)
    
    $content = Get-Content $FilePath -Raw -ErrorAction SilentlyContinue
    if (-not $content) { return @{} }
    
    $links = @{
        HTML = @()
        CSS = @()
        JS = @()
        Images = @()
    }
    
    # Extract href links (HTML pages)
    $hrefMatches = [regex]::Matches($content, 'href=[''"]([^''"#]+\.html[^''"]*)')
    foreach ($match in $hrefMatches) {
        $link = $match.Groups[1].Value -replace '\?.*$', ''  # Remove query params
        if ($link -notmatch '^(https?:|mailto:)') {
            $links.HTML += $link
        }
    }
    
    # Extract CSS links
    $cssMatches = [regex]::Matches($content, '<link[^>]+href=[''"]([^''"]+\.css[^''"]*)')
    foreach ($match in $cssMatches) {
        $link = $match.Groups[1].Value -replace '\?.*$', ''
        if ($link -notmatch '^https?:') {
            $links.CSS += $link
        }
    }
    
    # Extract JS links
    $jsMatches = [regex]::Matches($content, '<script[^>]+src=[''"]([^''"]+\.js[^''"]*)')
    foreach ($match in $jsMatches) {
        $link = $match.Groups[1].Value -replace '\?.*$', ''
        if ($link -notmatch '^https?:') {
            $links.JS += $link
        }
    }
    
    # Extract image links
    $imgMatches = [regex]::Matches($content, 'src=[''"]([^''"]+\.(png|jpg|jpeg|gif|svg|webp)[^''"]*)')
    foreach ($match in $imgMatches) {
        $link = $match.Groups[1].Value -replace '\?.*$', ''
        if ($link -notmatch '^(https?:|data:)') {
            $links.Images += $link
        }
    }
    
    # Make all arrays unique
    $links.HTML = $links.HTML | Select-Object -Unique
    $links.CSS = $links.CSS | Select-Object -Unique
    $links.JS = $links.JS | Select-Object -Unique
    $links.Images = $links.Images | Select-Object -Unique
    
    return $links
}

function Build-LinkGraph {
    param([string]$RootPath)
    
    Write-ColorOutput "🔍 Building comprehensive link graph..." "Cyan" "🔍"
    
    $graph = @{
        Files = @{}
        LinkedFiles = @()
        OrphanedFiles = @()
        BrokenLinks = @()
        MissingAssets = @{
            CSS = @()
            JS = @()
            Images = @()
        }
    }
    
    $allFiles = Get-AllHtmlFiles -Path $RootPath
    $totalFiles = $allFiles.Count
    $current = 0
    
    foreach ($file in $allFiles) {
        $current++
        Write-Progress -Activity "Analyzing files" -Status "$current of $totalFiles" -PercentComplete (($current / $totalFiles) * 100)
        
        $relativePath = $file.FullName.Replace("$RootPath\", "").Replace('\', '/')
        $links = Get-LinksInFile -FilePath $file.FullName
        
        $graph.Files[$relativePath] = @{
            FullPath = $file.FullName
            Links = $links
            LinkedFrom = @()
            Dependencies = @{
                CSS = $links.CSS
                JS = $links.JS
                Images = $links.Images
            }
        }
    }
    
    Write-Progress -Activity "Analyzing files" -Completed
    
    # Build reverse links (what links TO each file)
    foreach ($file in $graph.Files.Keys) {
        $fileDir = Split-Path $file -Parent
        if ($fileDir) { $fileDir = $fileDir.Replace('\', '/') + '/' }
        
        foreach ($link in $graph.Files[$file].Links.HTML) {
            # Resolve relative links to absolute paths from docs root
            $resolvedLink = Resolve-RelativePath -BasePath $fileDir -TargetPath $link
            
            # Track if this file is linked
            if ($graph.Files.ContainsKey($resolvedLink)) {
                $graph.Files[$resolvedLink].LinkedFrom += $file
            } else {
                # Check if file exists but not in HTML list
                $fullPath = Join-Path $RootPath $resolvedLink
                if (-not (Test-Path $fullPath)) {
                    $graph.BrokenLinks += @{
                        From = $file
                        To = $resolvedLink
                        Type = 'HTML'
                    }
                }
            }
        }
        
        # Validate CSS dependencies
        foreach ($cssLink in $graph.Files[$file].Dependencies.CSS) {
            $resolvedCss = Resolve-RelativePath -BasePath $fileDir -TargetPath $cssLink
            $fullPath = Join-Path $RootPath $resolvedCss
            $fullPath = $fullPath.Replace('\', '/')
            if (-not (Test-Path -LiteralPath $fullPath)) {
                $graph.MissingAssets.CSS += @{
                    File = $file
                    Asset = $resolvedCss
                    FullPath = $fullPath
                }
            }
        }
        
        # Validate JS dependencies
        foreach ($jsLink in $graph.Files[$file].Dependencies.JS) {
            $resolvedJs = Resolve-RelativePath -BasePath $fileDir -TargetPath $jsLink
            $fullPath = Join-Path $RootPath $resolvedJs
            $fullPath = $fullPath.Replace('\', '/')
            if (-not (Test-Path -LiteralPath $fullPath)) {
                $graph.MissingAssets.JS += @{
                    File = $file
                    Asset = $resolvedJs
                    FullPath = $fullPath
                }
            }
        }
        
        # Validate Image dependencies
        foreach ($imgLink in $graph.Files[$file].Dependencies.Images) {
            $resolvedImg = Resolve-RelativePath -BasePath $fileDir -TargetPath $imgLink
            $fullPath = Join-Path $RootPath $resolvedImg
            $fullPath = $fullPath.Replace('\', '/')
            if (-not (Test-Path -LiteralPath $fullPath)) {
                $graph.MissingAssets.Images += @{
                    File = $file
                    Asset = $resolvedImg
                    FullPath = $fullPath
                }
            }
        }
    }
    
    # Identify orphaned files
    foreach ($file in $graph.Files.Keys) {
        $isStub = Test-IsStubPage -FilePath $graph.Files[$file].FullPath
        
        if ($graph.Files[$file].LinkedFrom.Count -eq 0 -and $file -ne 'index.html') {
            if ($isStub) {
                # Stub pages that aren't linked are expected (work in progress)
                $graph.Files[$file].IsStub = $true
                $graph.LinkedFiles += $file  # Treat stubs as "linked" to prevent deletion
            } else {
                $graph.OrphanedFiles += $file
            }
        } else {
            $graph.LinkedFiles += $file
        }
    }
    
    Write-ColorOutput "✅ Link graph built: $($graph.Files.Count) files, $($graph.OrphanedFiles.Count) orphaned" "Green" "✅"
    Write-ColorOutput "  🔗 Broken links: $($graph.BrokenLinks.Count)" "Yellow" "  🔗"
    Write-ColorOutput "  📄 Missing CSS: $($graph.MissingAssets.CSS.Count)" "Yellow" "  📄"
    Write-ColorOutput "  📜 Missing JS: $($graph.MissingAssets.JS.Count)" "Yellow" "  📜"
    Write-ColorOutput "  🖼️  Missing Images: $($graph.MissingAssets.Images.Count)" "Yellow" "  🖼️"
    
    $stubCount = ($graph.Files.Values | Where-Object { $_.IsStub -eq $true }).Count
    if ($stubCount -gt 0) {
        Write-ColorOutput "  📝 Stub pages (WIP): $stubCount" "Cyan" "  📝"
    }
    
    return $graph
}

function Resolve-RelativePath {
    param(
        [string]$BasePath,
        [string]$TargetPath
    )
    
    $currentDir = $BasePath
    $resolvedLink = $TargetPath
    
    # Handle ../ navigation
    while ($resolvedLink -match '^\.\.\/') {
        $resolvedLink = $resolvedLink -replace '^\.\.\/', ''
        if ($currentDir) {
            $currentDir = Split-Path $currentDir.TrimEnd('/') -Parent
            if ($currentDir) { $currentDir = $currentDir.Replace('\', '/') + '/' }
        }
    }
    
    # Remove leading ./
    $resolvedLink = $resolvedLink -replace '^\.\/', ''
    
    # Combine with current directory
    $finalLink = if ($currentDir) { "$currentDir$resolvedLink" } else { $resolvedLink }
    return $finalLink.Replace('\', '/')
}

function Get-RootLevelFiles {
    param([string]$Path)
    
    Get-ChildItem -Path $Path -File | Where-Object { 
        $_.Name -notmatch '^\.' 
    }
}

function Update-LinksInFile {
    param(
        [string]$FilePath,
        [hashtable]$LinkUpdates
    )
    
    if (-not (Test-Path $FilePath)) { return }
    
    $content = Get-Content $FilePath -Raw
    $updated = $false
    
    foreach ($oldLink in $LinkUpdates.Keys) {
        $newLink = $LinkUpdates[$oldLink]
        if ($content -match [regex]::Escape($oldLink)) {
            $content = $content -replace [regex]::Escape($oldLink), $newLink
            $updated = $true
        }
    }
    
    if ($updated) {
        if (-not $DryRun) {
            Set-Content -Path $FilePath -Value $content -NoNewline
        }
        return $true
    }
    
    return $false
}

# ============================================================================
# MAIN ANALYSIS
# ============================================================================

Write-ColorOutput "`n🧠 CORTEX Documentation Organizer v1.0.0" "Cyan" "🧠"
Write-ColorOutput "Mode: $(if ($DryRun) { 'DRY RUN (preview only)' } else { 'EXECUTE' })" "Yellow" "⚙️"
Write-ColorOutput ""

# Step 1: Build link graph
$linkGraph = Build-LinkGraph -RootPath $DocsRoot

# Step 2: Analyze root-level files
Write-ColorOutput "`n📂 Analyzing root-level files..." "Cyan" "📂"
$rootFiles = Get-RootLevelFiles -Path $DocsRoot
$rootAnalysis = @{
    Keep = @()
    Move = @()
    Review = @()
}

foreach ($file in $rootFiles) {
    $fileName = $file.Name
    
    if ($fileName -in $RootWhitelist) {
        $rootAnalysis.Keep += $fileName
    }
    elseif ($MoveMap.ContainsKey($fileName)) {
        $rootAnalysis.Move += @{
            File = $fileName
            Target = $MoveMap[$fileName]
            Linked = $linkGraph.LinkedFiles -contains $fileName
        }
    }
    else {
        $rootAnalysis.Review += @{
            File = $fileName
            Linked = $linkGraph.LinkedFiles -contains $fileName
        }
    }
}

Write-ColorOutput "  ✅ Keep at root: $($rootAnalysis.Keep.Count)" "Green" "  ✅"
Write-ColorOutput "  📦 Move to subfolders: $($rootAnalysis.Move.Count)" "Yellow" "  📦"
Write-ColorOutput "  ⚠️  Review needed: $($rootAnalysis.Review.Count)" "Magenta" "  ⚠️"

# Step 3: Generate report
$report = @{
    Timestamp = Get-Date -Format "o"
    DryRun = $DryRun
    DocsRoot = $DocsRoot
    RootAnalysis = $rootAnalysis
    LinkGraph = @{
        TotalFiles = $linkGraph.Files.Count
        LinkedFiles = $linkGraph.LinkedFiles.Count
        OrphanedFiles = $linkGraph.OrphanedFiles.Count
        BrokenLinks = $linkGraph.BrokenLinks.Count
        MissingCSS = $linkGraph.MissingAssets.CSS.Count
        MissingJS = $linkGraph.MissingAssets.JS.Count
        MissingImages = $linkGraph.MissingAssets.Images.Count
    }
    Validation = @{
        BrokenLinks = $linkGraph.BrokenLinks
        MissingAssets = $linkGraph.MissingAssets
    }
    OrphanedFiles = $linkGraph.OrphanedFiles
    Actions = @{
        FilesToMove = @()
        LinksToUpdate = @()
        FilesToArchive = @()
        FilesToDelete = @()
    }
}

# ============================================================================
# EXECUTE CLEANUP
# ============================================================================

if (-not $DryRun -and -not $Force) {
    $confirmation = Read-Host "`n⚠️  This will modify files. Continue? (yes/no)"
    if ($confirmation -ne 'yes') {
        Write-ColorOutput "❌ Cancelled by user" "Red" "❌"
        exit
    }
}

Write-ColorOutput "`n🔧 Executing cleanup..." "Cyan" "🔧"

# Create archive directory if needed
if (-not $DryRun) {
    New-Item -ItemType Directory -Path $ArchiveDir -Force | Out-Null
}

$linkUpdates = @{}

# Move misplaced files
foreach ($item in $rootAnalysis.Move) {
    $fileName = $item.File
    $targetFolder = $item.Target
    $sourcePath = Join-Path $DocsRoot $fileName
    $targetPath = Join-Path $DocsRoot $targetFolder
    $targetFilePath = Join-Path $targetPath $fileName
    
    Write-ColorOutput "  📦 Moving: $fileName → $targetFolder" "Yellow" "  📦"
    
    if (-not $DryRun) {
        New-Item -ItemType Directory -Path $targetPath -Force | Out-Null
        Move-Item -Path $sourcePath -Destination $targetFilePath -Force
    }
    
    # Track link update needed
    $linkUpdates[$fileName] = "$targetFolder$fileName"
    
    $report.Actions.FilesToMove += @{
        Source = $fileName
        Target = "$targetFolder$fileName"
    }
}

# Archive or delete orphaned files
foreach ($orphan in $linkGraph.OrphanedFiles) {
    $orphanPath = Join-Path $DocsRoot $orphan
    if (-not (Test-Path $orphanPath)) { continue }
    
    $shouldDelete = $false
    foreach ($pattern in $DeletePatterns) {
        if ($orphan -like $pattern) {
            $shouldDelete = $true
            break
        }
    }
    
    if ($shouldDelete -or $DeleteOrphans) {
        Write-ColorOutput "  🗑️  Deleting: $orphan" "Red" "  🗑️"
        if (-not $DryRun) {
            Remove-Item -Path $orphanPath -Force
        }
        $report.Actions.FilesToDelete += $orphan
    }
    else {
        Write-ColorOutput "  📁 Archiving: $orphan" "Gray" "  📁"
        if (-not $DryRun) {
            $archivePath = Join-Path $ArchiveDir $orphan
            $archiveFolder = Split-Path $archivePath -Parent
            New-Item -ItemType Directory -Path $archiveFolder -Force | Out-Null
            Move-Item -Path $orphanPath -Destination $archivePath -Force
        }
        $report.Actions.FilesToArchive += $orphan
    }
}

# Update links in all HTML files
if ($linkUpdates.Count -gt 0) {
    Write-ColorOutput "`n🔗 Updating links in HTML files..." "Cyan" "🔗"
    
    $allHtmlFiles = Get-AllHtmlFiles -Path $DocsRoot
    $updatedCount = 0
    
    foreach ($file in $allHtmlFiles) {
        $relativePath = $file.FullName.Replace($DocsRoot, "").TrimStart('\', '/').Replace('\', '/')
        $updated = Update-LinksInFile -FilePath $file.FullName -LinkUpdates $linkUpdates
        if ($updated) {
            $updatedCount++
            $report.Actions.LinksToUpdate += $relativePath
        }
    }
    
    Write-ColorOutput "  ✅ Updated links in $updatedCount files" "Green" "  ✅"
}

# ============================================================================
# SAVE REPORT
# ============================================================================

$reportDir = Split-Path $ReportPath -Parent
if (-not (Test-Path $reportDir)) {
    New-Item -ItemType Directory -Path $reportDir -Force | Out-Null
}

$report | ConvertTo-Json -Depth 10 | Set-Content -Path $ReportPath

Write-ColorOutput "`n📊 Report saved: $ReportPath" "Green" "📊"

# ============================================================================
# SUMMARY
# ============================================================================

Write-ColorOutput "`n✅ Cleanup Complete!" "Green" "✅"
Write-ColorOutput ""
Write-ColorOutput "Summary:" "Cyan"
Write-ColorOutput "  📦 Files moved: $($report.Actions.FilesToMove.Count)" "Yellow"
Write-ColorOutput "  🔗 Files with updated links: $($report.Actions.LinksToUpdate.Count)" "Cyan"
Write-ColorOutput "  📁 Files archived: $($report.Actions.FilesToArchive.Count)" "Gray"
Write-ColorOutput "  🗑️  Files deleted: $($report.Actions.FilesToDelete.Count)" "Red"

# Categorize orphaned files for review
if ($linkGraph.OrphanedFiles.Count -gt 0) {
    Write-ColorOutput "`n⚠️  Orphaned Files Found ($($linkGraph.OrphanedFiles.Count)):" "Yellow" "⚠️"
    
    $categories = @{
        'Story Chapters' = @()
        'Old/Backup Files' = @()
        'Prototypes' = @()
        'Duplicates' = @()
        'Other' = @()
    }
    
    foreach ($orphan in $linkGraph.OrphanedFiles) {
        $fileName = Split-Path $orphan -Leaf
        if ($orphan -match 'story/Chapter') {
            $categories['Story Chapters'] += $fileName
        }
        elseif ($orphan -match '-old\.html|index-old') {
            $categories['Old/Backup Files'] += $fileName
        }
        elseif ($orphan -match 'prototypes/') {
            $categories['Prototypes'] += $fileName
        }
        elseif ($orphan -match 'technical/orchestrators/') {
            $categories['Duplicates'] += $fileName
        }
        else {
            $categories['Other'] += $fileName
        }
    }
    
    foreach ($category in $categories.Keys | Sort-Object) {
        if ($categories[$category].Count -gt 0) {
            Write-ColorOutput "  📂 $category`: $($categories[$category].Count)" "Gray" "  📂"
        }
    }
    
    Write-ColorOutput "`n  💡 Tip: Run with -DeleteOrphans to remove old files, or review report at:" "Cyan" "  💡"
    Write-ColorOutput "     $ReportPath" "Gray"
}

if ($DryRun) {
    Write-ColorOutput "`n⚠️  DRY RUN MODE - No changes were made" "Yellow" "⚠️"
    Write-ColorOutput "Run with -DryRun `$false to execute" "Yellow"
}
else {
    Write-ColorOutput "`n🎉 All changes applied successfully!" "Green" "🎉"
    if ($ArchiveDir -and (Test-Path $ArchiveDir)) {
        Write-ColorOutput "Archived files saved to: $ArchiveDir" "Gray"
    }
}

Write-ColorOutput ""
