"""
Setup Script Generator

Generates platform-specific setup scripts for development environments.

Supports:
- Windows PowerShell (.ps1)
- macOS/Linux Bash (.sh)

Features:
- Dependency installation commands
- Environment variable setup
- Tool recommendations
- Runtime version checks

Author: Asif Hussain
Copyright: © 2025 Asif Hussain. All rights reserved.
"""

from pathlib import Path
from typing import Dict, Any, List
from enum import Enum

# DependencyDetector integration
try:
    from src.intelligence.dependency_detector import DependencyDetector
    DEPENDENCY_DETECTOR_AVAILABLE = True
except ImportError:
    DEPENDENCY_DETECTOR_AVAILABLE = False


class Platform(str, Enum):
    """Supported platforms."""
    WINDOWS = "windows"
    UNIX = "unix"


class SetupScriptGenerator:
    """Generates setup scripts for development environments."""
    
    def __init__(self, dependencies: Dict[str, Any]):
        """
        Initialize setup script generator.
        
        Args:
            dependencies: Dependency data from DependencyDetector
                - by_language: Dict of language -> dependencies
                - env_vars: Optional dict of environment variables
        """
        self.dependencies = dependencies
        self.by_language = dependencies.get("by_language", {})
        self.env_vars = dependencies.get("env_vars", {})
    
    @classmethod
    def from_repository(cls, repo_path: Path) -> 'SetupScriptGenerator':
        """
        Create setup script generator by detecting dependencies from repository.
        
        Args:
            repo_path: Path to repository root
        
        Returns:
            SetupScriptGenerator instance with detected dependencies
        """
        if not DEPENDENCY_DETECTOR_AVAILABLE:
            raise ImportError(
                "DependencyDetector not available. "
                "Required for automatic dependency detection."
            )
        
        detector = DependencyDetector(repo_path)
        dependencies = detector.detect()
        return cls(dependencies)
    
    def generate(self) -> Dict[str, str]:
        """
        Generate setup scripts for all platforms.
        
        Returns:
            Dictionary with platform -> script content
        """
        return {
            "windows": self._generate_windows(),
            "unix": self._generate_unix()
        }
    
    def save(self, output_dir: Path) -> Dict[str, Path]:
        """
        Save scripts to files.
        
        Args:
            output_dir: Directory to save scripts
            
        Returns:
            Dictionary with platform -> file path
        """
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        
        scripts = self.generate()
        files = {}
        
        # Save Windows script
        win_file = output_dir / "setup.ps1"
        win_file.write_text(scripts["windows"], encoding="utf-8")
        files["windows"] = win_file
        
        # Save Unix script
        unix_file = output_dir / "setup.sh"
        unix_file.write_text(scripts["unix"], encoding="utf-8")
        # Make executable
        unix_file.chmod(0o755)
        files["unix"] = unix_file
        
        return files
    
    def _generate_windows(self) -> str:
        """Generate Windows PowerShell script."""
        lines = []
        
        # Header
        lines.append("# Setup script for Windows")
        lines.append("# Auto-generated by CORTEX")
        lines.append("")
        lines.append("Write-Host '==================================' -ForegroundColor Cyan")
        lines.append("Write-Host 'Development Environment Setup' -ForegroundColor Cyan")
        lines.append("Write-Host '==================================' -ForegroundColor Cyan")
        lines.append("")
        
        # Python setup
        if "python" in self.by_language:
            lines.extend(self._windows_python_setup())
        
        # Node.js setup
        if "javascript" in self.by_language:
            lines.extend(self._windows_nodejs_setup())
        
        # .NET setup
        if "csharp" in self.by_language:
            lines.extend(self._windows_dotnet_setup())
        
        # Ruby setup
        if "ruby" in self.by_language:
            lines.extend(self._windows_ruby_setup())
        
        # Environment variables
        if self.env_vars:
            lines.extend(self._windows_env_setup())
        
        # Tool recommendations
        lines.extend(self._windows_tool_recommendations())
        
        # Footer
        lines.append("")
        lines.append("Write-Host ''")
        lines.append("Write-Host 'Setup complete! ✓' -ForegroundColor Green")
        
        return "\n".join(lines)
    
    def _generate_unix(self) -> str:
        """Generate Unix Bash script."""
        lines = []
        
        # Shebang and header
        lines.append("#!/bin/bash")
        lines.append("# Setup script for macOS/Linux")
        lines.append("# Auto-generated by CORTEX")
        lines.append("")
        lines.append("echo '=================================='")
        lines.append("echo 'Development Environment Setup'")
        lines.append("echo '=================================='")
        lines.append("")
        
        # Python setup
        if "python" in self.by_language:
            lines.extend(self._unix_python_setup())
        
        # Node.js setup
        if "javascript" in self.by_language:
            lines.extend(self._unix_nodejs_setup())
        
        # .NET setup
        if "csharp" in self.by_language:
            lines.extend(self._unix_dotnet_setup())
        
        # Ruby setup
        if "ruby" in self.by_language:
            lines.extend(self._unix_ruby_setup())
        
        # Environment variables
        if self.env_vars:
            lines.extend(self._unix_env_setup())
        
        # Tool recommendations
        lines.extend(self._unix_tool_recommendations())
        
        # Footer
        lines.append("")
        lines.append("echo ''")
        lines.append("echo 'Setup complete! ✓'")
        
        return "\n".join(lines)
    
    # ===== Windows Helpers =====
    
    def _windows_python_setup(self) -> List[str]:
        """Generate Windows Python setup commands."""
        lines = []
        lines.append("# Python Setup")
        lines.append("Write-Host 'Checking Python...' -ForegroundColor Yellow")
        lines.append("python --version")
        lines.append("")
        
        python_deps = self.by_language.get("python", [])
        if python_deps:
            lines.append("Write-Host 'Installing Python packages...' -ForegroundColor Yellow")
            
            # Group dependencies
            packages = []
            for dep in python_deps:
                if dep.get("constraint") == "*":
                    packages.append(dep["name"])
                else:
                    packages.append(f"{dep['name']}{dep.get('constraint', '==')}{dep['version']}")
            
            # Install all at once
            lines.append(f"pip install {' '.join(packages)}")
            lines.append("")
        
        return lines
    
    def _windows_nodejs_setup(self) -> List[str]:
        """Generate Windows Node.js setup commands."""
        lines = []
        lines.append("# Node.js Setup")
        lines.append("Write-Host 'Checking Node.js...' -ForegroundColor Yellow")
        lines.append("node --version")
        lines.append("npm --version")
        lines.append("")
        
        # List packages as comment
        node_deps = self.by_language.get("javascript", [])
        if node_deps:
            pkg_names = [f"{d['name']}@{d.get('constraint', '')}{d['version']}" for d in node_deps]
            lines.append(f"# Packages: {', '.join(pkg_names)}")
        
        lines.append("Write-Host 'Installing Node.js packages...' -ForegroundColor Yellow")
        lines.append("npm install")
        lines.append("")
        
        return lines
    
    def _windows_dotnet_setup(self) -> List[str]:
        """Generate Windows .NET setup commands."""
        lines = []
        lines.append("# .NET Setup")
        lines.append("Write-Host 'Checking .NET...' -ForegroundColor Yellow")
        lines.append("dotnet --version")
        lines.append("")
        
        lines.append("Write-Host 'Restoring .NET packages...' -ForegroundColor Yellow")
        lines.append("dotnet restore")
        lines.append("")
        
        return lines
    
    def _windows_ruby_setup(self) -> List[str]:
        """Generate Windows Ruby setup commands."""
        lines = []
        lines.append("# Ruby Setup")
        lines.append("Write-Host 'Checking Ruby...' -ForegroundColor Yellow")
        lines.append("ruby --version")
        lines.append("")
        
        lines.append("Write-Host 'Installing Ruby gems...' -ForegroundColor Yellow")
        lines.append("bundle install")
        lines.append("")
        
        return lines
    
    def _windows_env_setup(self) -> List[str]:
        """Generate Windows environment variable setup."""
        lines = []
        lines.append("# Environment Variables")
        lines.append("Write-Host 'Setting environment variables...' -ForegroundColor Yellow")
        
        for key, value in self.env_vars.items():
            lines.append(f"$env:{key} = '{value}'")
        
        lines.append("")
        return lines
    
    def _windows_tool_recommendations(self) -> List[str]:
        """Generate Windows tool recommendations."""
        lines = []
        lines.append("# Recommended Development Tools")
        lines.append("Write-Host 'Recommended tools:' -ForegroundColor Cyan")
        
        if "python" in self.by_language:
            lines.append("Write-Host '  Python: pylint, black, pytest, mypy' -ForegroundColor Gray")
            lines.append("Write-Host '    Install: pip install pylint black pytest mypy' -ForegroundColor Gray")
        
        if "javascript" in self.by_language:
            lines.append("Write-Host '  Node.js: eslint, prettier, jest' -ForegroundColor Gray")
            lines.append("Write-Host '    Install: npm install -D eslint prettier jest' -ForegroundColor Gray")
        
        if "csharp" in self.by_language:
            lines.append("Write-Host '  .NET: dotnet-format, StyleCop' -ForegroundColor Gray")
        
        lines.append("")
        return lines
    
    # ===== Unix Helpers =====
    
    def _unix_python_setup(self) -> List[str]:
        """Generate Unix Python setup commands."""
        lines = []
        lines.append("# Python Setup")
        lines.append("echo 'Checking Python...'")
        lines.append("python3 --version || python --version")
        lines.append("")
        
        python_deps = self.by_language.get("python", [])
        if python_deps:
            lines.append("echo 'Installing Python packages...'")
            
            # Group dependencies
            packages = []
            for dep in python_deps:
                if dep.get("constraint") == "*":
                    packages.append(dep["name"])
                else:
                    packages.append(f"{dep['name']}{dep.get('constraint', '==')}{dep['version']}")
            
            # Install all at once
            lines.append(f"pip3 install {' '.join(packages)} || pip install {' '.join(packages)}")
            lines.append("")
        
        return lines
    
    def _unix_nodejs_setup(self) -> List[str]:
        """Generate Unix Node.js setup commands."""
        lines = []
        lines.append("# Node.js Setup")
        lines.append("echo 'Checking Node.js...'")
        lines.append("node --version")
        lines.append("npm --version")
        lines.append("")
        
        # List packages as comment
        node_deps = self.by_language.get("javascript", [])
        if node_deps:
            pkg_names = [f"{d['name']}@{d.get('constraint', '')}{d['version']}" for d in node_deps]
            lines.append(f"# Packages: {', '.join(pkg_names)}")
        
        lines.append("echo 'Installing Node.js packages...'")
        lines.append("npm install")
        lines.append("")
        
        return lines
    
    def _unix_dotnet_setup(self) -> List[str]:
        """Generate Unix .NET setup commands."""
        lines = []
        lines.append("# .NET Setup")
        lines.append("echo 'Checking .NET...'")
        lines.append("dotnet --version")
        lines.append("")
        
        lines.append("echo 'Restoring .NET packages...'")
        lines.append("dotnet restore")
        lines.append("")
        
        return lines
    
    def _unix_ruby_setup(self) -> List[str]:
        """Generate Unix Ruby setup commands."""
        lines = []
        lines.append("# Ruby Setup")
        lines.append("echo 'Checking Ruby...'")
        lines.append("ruby --version")
        lines.append("")
        
        lines.append("echo 'Installing Ruby gems...'")
        lines.append("bundle install")
        lines.append("")
        
        return lines
    
    def _unix_env_setup(self) -> List[str]:
        """Generate Unix environment variable setup."""
        lines = []
        lines.append("# Environment Variables")
        lines.append("echo 'Setting environment variables...'")
        
        for key, value in self.env_vars.items():
            lines.append(f"export {key}='{value}'")
        
        lines.append("")
        return lines
    
    def _unix_tool_recommendations(self) -> List[str]:
        """Generate Unix tool recommendations."""
        lines = []
        lines.append("# Recommended Development Tools")
        lines.append("echo 'Recommended tools:'")
        
        if "python" in self.by_language:
            lines.append("echo '  Python: pylint, black, pytest, mypy'")
            lines.append("echo '    Install: pip3 install pylint black pytest mypy'")
        
        if "javascript" in self.by_language:
            lines.append("echo '  Node.js: eslint, prettier, jest'")
            lines.append("echo '    Install: npm install -D eslint prettier jest'")
        
        if "csharp" in self.by_language:
            lines.append("echo '  .NET: dotnet-format, StyleCop'")
        
        lines.append("")
        return lines
