# CORTEX Feature Development Workflow
# Complete end-to-end workflow for creating new features with security and quality gates

workflow_id: "feature_development"
name: "Feature Development Workflow"
description: "Complete workflow for creating production-ready features with security, TDD, and documentation"
version: "1.0.0"

stages:
  # Stage 1: Define requirements and Done criteria
  - id: "clarify_dod_dor"
    script: "dod_dor_clarifier"
    description: "Clarify Definition of Done and Definition of Ready"
    required: true
    depends_on: []
    timeout_seconds: 300
  
  # Stage 2: Security threat modeling
  - id: "threat_model"
    script: "threat_modeler"
    description: "Perform STRIDE threat analysis"
    required: true
    depends_on: ["clarify_dod_dor"]
    timeout_seconds: 600
  
  # Stage 3: Multi-phase planning
  - id: "plan"
    script: "work_planner"
    description: "Create multi-phase implementation plan"
    required: true
    depends_on: ["threat_model"]
    timeout_seconds: 600
  
  # Stage 4: Test-Driven Development cycle
  - id: "tdd_cycle"
    script: "tdd_workflow"
    description: "RED → GREEN → REFACTOR implementation"
    required: true
    depends_on: ["plan"]
    retryable: true
    max_retries: 3
    timeout_seconds: 1800
  
  # Stage 5: Execute test suite
  - id: "run_tests"
    script: "test_runner"
    description: "Execute complete test suite"
    required: true
    depends_on: ["tdd_cycle"]
    retryable: true
    max_retries: 2
    timeout_seconds: 600
  
  # Stage 6: Validate Definition of Done
  - id: "validate_dod"
    script: "dod_validator"
    description: "Verify all DoD criteria met"
    required: true
    depends_on: ["run_tests"]
    timeout_seconds: 300
  
  # Stage 7: Code cleanup (optional)
  - id: "cleanup"
    script: "code_cleanup"
    description: "Remove unused imports, format code"
    required: false
    depends_on: ["validate_dod"]
    timeout_seconds: 300
  
  # Stage 8: Generate documentation
  - id: "document"
    script: "doc_generator"
    description: "Generate feature documentation"
    required: false
    depends_on: ["validate_dod"]
    timeout_seconds: 600
