# Quick Feature Workflow
# Fast-track workflow for simple features (skips threat modeling, cleanup)

workflow_id: "quick_feature"
name: "Quick Feature Creation"
description: |
  Streamlined workflow for simple, low-risk features:
  - Clarify DoD/DoR
  - Plan with work-planner
  - Implement with TDD
  - Validate DoD

stages:
  # Stage 1: DoD/DoR Clarification
  - id: "clarify_dod_dor"
    script: "dod_dor_clarifier"
    required: true
    depends_on: []
    timeout_seconds: 30
  
  # Stage 2: Planning
  - id: "plan"
    script: "work_planner"
    required: true
    depends_on: ["clarify_dod_dor"]
    timeout_seconds: 60
  
  # Stage 3: TDD Implementation
  - id: "tdd_cycle"
    script: "tdd_workflow"
    required: true
    depends_on: ["plan"]
    retryable: true
    max_retries: 2
    timeout_seconds: 300
  
  # Stage 4: DoD Validation
  - id: "validate_dod"
    script: "dod_validator"
    required: true
    depends_on: ["tdd_cycle"]
    timeout_seconds: 60
