classDiagram
    class Updater_CreatePaymentTransactionInvoices {
        +Run
    }
    class Constants
    Updater_CreatePaymentTransactionInvoices --> Constants
    class Utilities
    Updater_CreatePaymentTransactionInvoices --> Utilities
    class Components
    Updater_CreatePaymentTransactionInvoices --> Components
