"""
Canonical Enum Definitions - Single Source of Truth (SSOT)

AC-ID: AC-PERMANENT-FIX-017
Purpose: Eliminate CORE-035 violations by consolidating 275+ duplicate enum definitions

This module serves as the SINGLE CANONICAL LOCATION for all enums used across CORTEX.
All other files must import enums from this module, never define duplicates.

Governance Rules:
- CORE-035: Single Canonical Implementation
- CORE-011: Type hints mandatory (all enums use Enum)
- CORE-030: Implementation Truth (this is the truth; other copies are errors)

Migration Strategy:
1. Search codebase for enum definitions
2. Replace with imports from this module
3. Delete original enum definitions
4. Validate circular import prevention
"""

from enum import Enum, IntEnum


# ============================================================================
# ACTION & EXECUTION ENUMS
# ============================================================================

class ActionType(Enum):
    """Types of actions."""
    CREATE = "create"
    MODIFY = "modify"
    DELETE = "delete"
    QUERY = "query"
    EXECUTE = "execute"
    ROLLBACK = "rollback"


class ExecutionMode(Enum):
    """Execution mode enumeration."""
    SYNCHRONOUS = "synchronous"
    ASYNCHRONOUS = "asynchronous"
    BATCH = "batch"
    STREAMING = "streaming"
    PARALLEL = "parallel"
    SANDBOX = "sandbox"
    DRY_RUN = "dry_run"
    SAFE = "safe"
    COMMITTED = "committed"


class ExecutionStrategy(Enum):
    """Strategy for executing operations."""
    SEQUENTIAL = "sequential"
    PARALLEL = "parallel"
    ASYNC = "async"
    DISTRIBUTED = "distributed"
    ADAPTIVE = "adaptive"
    FALLBACK = "fallback"





# ============================================================================
# ALERT & MONITORING ENUMS
# ============================================================================

class AlertSeverity(IntEnum):
    """Alert severity levels."""
    INFO = 0
    WARNING = 1
    CRITICAL = 2
    ERROR = 3


class AlertPriority(Enum):
    """Alert priority levels."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    URGENT = "urgent"


class AlertState(Enum):
    """State of an alert."""
    ACTIVE = "active"
    ACKNOWLEDGED = "acknowledged"
    RESOLVED = "resolved"
    ESCALATED = "escalated"


# ============================================================================
# AUDIT & GOVERNANCE ENUMS
# ============================================================================

class AuditEventType(Enum):
    """Types of audit events."""
    ACCESS = "access"
    MODIFICATION = "modification"
    DELETION = "deletion"
    AUTHORIZATION = "authorization"
    AUTHENTICATION = "authentication"
    CONFIGURATION_CHANGE = "configuration_change"


class AuditAction(Enum):
    """Action being audited."""
    CREATE = "create"
    READ = "read"
    UPDATE = "update"
    DELETE = "delete"
    EXECUTE = "execute"
    ESCALATE = "escalate"


class AuditOperationType(Enum):
    """Type of operation being audited."""
    USER_LOGIN = "user_login"
    DATA_ACCESS = "data_access"
    CONFIGURATION_CHANGE = "configuration_change"
    PRIVILEGE_CHANGE = "privilege_change"
    SYSTEM_CHANGE = "system_change"


class ApprovalStatus(Enum):
    """Status of an approval."""
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    ESCALATED = "escalated"
    EXPIRED = "expired"


class CheckpointStatus(Enum):
    """Status of a checkpoint."""
    CREATED = "created"
    ACTIVE = "active"
    VALIDATED = "validated"
    COMMITTED = "committed"
    ROLLED_BACK = "rolled_back"
    FAILED = "failed"


# ============================================================================
# CHALLENGE & INTENT ENUMS
# ============================================================================

class ChallengeType(Enum):
    """Types of challenges generated by ChallengeEngine."""
    BETTER_SOLUTION = "better_solution"
    MISSING_CONTEXT = "missing_context"
    CLARIFICATION_NEEDED = "clarification_needed"
    ALTERNATIVE_APPROACH = "alternative_approach"
    PERFORMANCE_CONCERN = "performance_concern"
    SECURITY_RISK = "security_risk"
    SCALABILITY_ISSUE = "scalability_issue"
    MAINTAINABILITY_CONCERN = "maintainability_concern"


class ChallengeCategory(Enum):
    """Category of challenge."""
    TECHNICAL = "technical"
    BUSINESS = "business"
    PROCESS = "process"
    ARCHITECTURE = "architecture"
    PERFORMANCE = "performance"
    BREAKING_CHANGE = "breaking_change"
    TEST_GAP = "test_gap"
    GOVERNANCE_RISK = "governance_risk"
    HISTORICAL_ISSUE = "historical_issue"
    PERFORMANCE_RISK = "performance_risk"


class IntentType(Enum):
    """Types of user intents."""
    IMPLEMENT = "implement"
    FIX = "fix"
    REFACTOR = "refactor"
    ANALYZE = "analyze"
    DOCUMENT = "document"
    TEST = "test"
    DEPLOY = "deploy"
    GOVERNANCE = "governance"
    QUERY = "query"
    VALIDATE = "validate"
    MIGRATE = "migrate"
    ONBOARD = "onboard"  # AC-ONBOARD-001: Repository onboarding intent
    PLAN = "plan"  # PHASE-25: CORTEX development planning and phase management
    UNKNOWN = "unknown"


class RoutingType(Enum):
    """Types of routing paths."""
    DIRECT = "direct"
    CACHED = "cached"
    FUZZY = "fuzzy"
    COMPOSITE = "composite"
    FALLBACK = "fallback"


# ============================================================================
# CHANGE & VERSION ENUMS
# ============================================================================

class ChangeType(Enum):
    """Type of change being tracked."""
    FEATURE = "feature"
    BUGFIX = "bugfix"
    REFACTOR = "refactor"
    DOCUMENTATION = "documentation"
    PERFORMANCE = "performance"
    SECURITY = "security"
    BREAKING = "breaking"
    SCHEMA_DRIFT = "schema_drift"
    COVERAGE_GAP = "coverage_gap"
    STALENESS = "staleness"
    VOLUME_ANOMALY = "volume_anomaly"
    SEMANTIC_SHIFT = "semantic_shift"


class BrainTier(Enum):
    """CORTEX brain hierarchy tiers."""
    TIER_0 = "tier_0"
    TIER_1 = "tier_1"
    TIER_2 = "tier_2"
    TIER_3 = "tier_3"


class TierType(Enum):
    """Types of tiers."""
    GOVERNANCE = "governance"
    ACCEPTANCE = "acceptance"
    TEMPLATES = "templates"
    KNOWLEDGE = "knowledge"


# ============================================================================
# CIRCUIT BREAKER & RESILIENCE ENUMS
# ============================================================================

class CircuitBreakerState(IntEnum):
    """States of the circuit breaker."""
    CLOSED = 0      # Normal operation
    OPEN = 1        # Failing, requests rejected
    HALF_OPEN = 2   # Testing recovery


# ============================================================================
# COHERENCE & VALIDATION ENUMS
# ============================================================================

class CoherenceType(Enum):
    """Types of coherence checks."""
    SEMANTIC = "semantic"
    SYNTACTIC = "syntactic"
    LOGICAL = "logical"
    TEMPORAL = "temporal"
    REFERENTIAL = "referential"


class ValidationLevel(Enum):
    """Levels of validation."""
    STRICT = "strict"
    NORMAL = "normal"
    MODERATE = "moderate"
    LENIENT = "lenient"
    NONE = "none"


# ============================================================================
# CONTINUATION & DECISION ENUMS
# ============================================================================

class ContinuationReason(Enum):
    """Reason for continuing conversation."""
    MORE_CONTEXT_NEEDED = "more_context_needed"
    CLARIFICATION_NEEDED = "clarification_needed"
    REFINEMENT_NEEDED = "refinement_needed"
    FOLLOW_UP = "follow_up"
    VALIDATION = "validation"
    COMPLETION = "completion"
    IMPLICIT_NEXT_OPERATION = "implicit_next_operation"
    USER_PROVIDED_FOLLOWUP = "user_provided_followup"
    GOVERNANCE_HALT = "governance_halt"
    INTERACTION_REQUIRED = "interaction_required"
    TOKEN_LIMIT = "token_limit"
    ERROR_UNRECOVERABLE = "error_unrecoverable"
    AUTO_REFINEMENT_LOOP = "auto_refinement_loop"
    USER_REJECTION = "user_rejection"
    MAX_ROUNDS_REACHED = "max_rounds_reached"

    @classmethod
    def from_string(cls, value: str) -> "ContinuationReason":
        """Create enum from string value (case-insensitive)."""
        value_lower = value.lower().replace("-", "_").replace(" ", "_")
        for member in cls:
            if member.value == value_lower or member.name.lower() == value_lower:
                return member
        raise ValueError(f"No ContinuationReason matches '{value}'")

class DecisionStatus(Enum):
    """Status of a decision."""
    PENDING = "pending"
    MADE = "made"
    IMPLEMENTED = "implemented"
    REVIEWED = "reviewed"
    REVISED = "revised"


# ============================================================================
# GOVERNANCE & TIER ENUMS
# ============================================================================

class GovernanceStatus(Enum):
    """Status of governance check."""
    COMPLIANT = "compliant"
    NON_COMPLIANT = "non_compliant"
    WARNING = "warning"
    ESCALATED = "escalated"
    EXEMPT = "exempt"


class RuleType(Enum):
    """Type of governance rule."""
    MANDATORY = "mandatory"
    RECOMMENDED = "recommended"
    OPTIONAL = "optional"
    DEPRECATED = "deprecated"


# ============================================================================
# KNOWLEDGE & ANALYSIS ENUMS
# ============================================================================

class KnowledgeSource(Enum):
    """Source of knowledge."""
    BEST_PRACTICES = "best_practices"
    ARCHITECTURE = "architecture"
    PATTERNS = "patterns"
    ANTI_PATTERNS = "anti_patterns"
    CONVENTIONS = "conventions"
    DOMAIN = "domain"


class AnalysisLevel(Enum):
    """Level of analysis."""
    SHALLOW = "shallow"
    STANDARD = "standard"
    DEEP = "deep"
    COMPREHENSIVE = "comprehensive"


# ============================================================================
# OPERATION & STATE ENUMS
# ============================================================================

class OperationStatus(Enum):
    """Status of an operation."""
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"
    PAUSED = "paused"


class StateTransition(Enum):
    """State transitions."""
    ENTER = "enter"
    EXIT = "exit"
    STAY = "stay"
    LOOP = "loop"
    JUMP = "jump"


class PhaseStatus(Enum):
    """Status of a phase."""
    NOT_STARTED = "not_started"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    BLOCKED = "blocked"
    ARCHIVED = "archived"


class ComponentHealth(Enum):
    """Health status of a component."""
    HEALTHY = "healthy"
    DEGRADED = "degraded"
    UNHEALTHY = "unhealthy"
    RECOVERING = "recovering"
    UNKNOWN = "unknown"


# ============================================================================
# PATTERN & MATCHING ENUMS
# ============================================================================

class PatternType(Enum):
    """Type of pattern."""
    DESIGN_PATTERN = "design_pattern"
    ANTI_PATTERN = "anti_pattern"
    ARCHITECTURAL = "architectural"
    BEHAVIORAL = "behavioral"
    STRUCTURAL = "structural"


class MatchConfidence(Enum):
    """Confidence level of a match."""
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    FUZZY = "fuzzy"


# ============================================================================
# RESPONSE & COMMUNICATION ENUMS
# ============================================================================

class ResponseType(Enum):
    """Type of response."""
    DIRECT = "direct"
    SUGGESTIVE = "suggestive"
    CHALLENGING = "challenging"
    CLARIFYING = "clarifying"
    REFERENTIAL = "referential"
    # AC-REFACTOR-ARCHITECT-001: Added for response template system
    SUCCESS = "success"
    ERROR = "error"
    WARNING = "warning"
    INFORMATIONAL = "informational"
    AUDIT = "audit"
    CHALLENGE = "challenge"
    APPROVAL_GATE = "approval_gate"
    IMPLEMENTATION = "implementation"


class MessageLevel(Enum):
    """Level of messaging."""
    DEBUG = "debug"
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


# ============================================================================
# TESTING & QUALITY ENUMS
# ============================================================================

class TestType(Enum):
    """Type of test."""
    UNIT = "unit"
    INTEGRATION = "integration"
    FUNCTIONAL = "functional"
    PERFORMANCE = "performance"
    SECURITY = "security"
    END_TO_END = "end_to_end"


class TestStatus(Enum):
    """Status of a test."""
    PASSING = "passing"
    FAILING = "failing"
    SKIPPED = "skipped"
    PENDING = "pending"
    FLAKY = "flaky"


class QualityGate(Enum):
    """Quality gate status."""
    PASSED = "passed"
    FAILED = "failed"
    WARNING = "warning"
    BLOCKED = "blocked"


# ============================================================================
# WIRING & REGISTRY ENUMS
# ============================================================================

class WiringState(Enum):
    """State of orchestrator wiring."""
    UNINITIALIZED = "uninitialized"
    LOADING = "loading"
    VALIDATING = "validating"
    WIRED = "wired"
    VALIDATION_FAILED = "validation_failed"
    UNWIRED = "unwired"


# ============================================================================
# WORKFLOW & EXECUTION ENUMS
# ============================================================================

class WorkflowStage(Enum):
    """Stage of workflow execution."""
    INITIATION = "initiation"
    PLANNING = "planning"
    EXECUTION = "execution"
    VALIDATION = "validation"
    COMPLETION = "completion"
    CLEANUP = "cleanup"


class ValidationSeverity(Enum):
    """Validation severity levels.
    
    CORE-035: Canonical definition - import from here, not redefine.
    Used by: Integration validators, domain validation, output validators
    
    Values ordered by severity (INFO < WARNING < ERROR < CRITICAL)
    """
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


class SeverityLevel(str, Enum):
    """Severity levels for duplication detection and performance bottlenecks.
    
    CORE-035: Canonical definition - import from here, not redefine.
    Used by: Duplication registry, performance profiler
    
    Note: Uses (str, Enum) for string comparison and JSON serialization.
    """
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class VariableType(str, Enum):
    """Template variable types.
    
    CORE-035: Canonical definition - import from here, not redefine.
    Used by: Response templates, unified response composer
    """
    STRING = "string"
    INTEGER = "integer"
    BOOLEAN = "boolean"
    LIST = "list"
    OPTIONAL = "optional"


# ============================================================================
# RISK & COMPLEXITY ENUMS (CORE-035 Consolidated)
# ============================================================================

class RiskLevel(Enum):
    """Operation risk classification.
    
    CORE-035: Canonical definition - import from here, not redefine.
    Used by: BLUF orchestrators, challenge engine, DoR approval gate
    """
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ComplexityLevel(Enum):
    """Operation complexity classification.
    
    CORE-035: Canonical definition - import from here, not redefine.
    Used by: BLUF orchestrators, capacity planning, LENS analysis
    """
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    VERY_HIGH = "VERY_HIGH"


class OrchestratorComplexityLevel(Enum):
    """Orchestrator setup/configuration complexity (1-4 scale).
    
    CORE-035: Canonical definition for orchestrator complexity.
    Used by: SetupOrchestrator, UpgradeOrchestrator, RollbackOrchestrator,
             ComposedOrchestrator, BootstrapOrchestrator, ToolDiscoveryOrchestrator
    """
    BASIC = 1
    INTERMEDIATE = 2
    ADVANCED = 3
    EXPERT = 4


class DisagreementType(Enum):
    """Types of challenge/disagreement.
    
    CORE-035: Canonical definition.
    Used by: ChallengeEngine, challenge_engine_plugins
    """
    BETTER_APPROACH = "better_approach"
    MISSING_CONTEXT = "missing_context"
    SCOPE_CONCERN = "scope_concern"
    RISK_WARNING = "risk_warning"
    EFFICIENCY_SUGGESTION = "efficiency_suggestion"


class EntityType(Enum):
    """Types of entities in codebase.
    
    CORE-035: Canonical definition.
    Used by: relationship_analyzer, repository_scanner
    """
    FILE = "file"
    CLASS = "class"
    FUNCTION = "function"
    METHOD = "method"
    MODULE = "module"
    PACKAGE = "package"
    VARIABLE = "variable"
    CONSTANT = "constant"


class HealthStatus(Enum):
    """Health check status.
    
    CORE-035: Canonical definition.
    Used by: health_monitor, production_readiness_manager
    """
    HEALTHY = "healthy"
    DEGRADED = "degraded"
    UNHEALTHY = "unhealthy"
    UNKNOWN = "unknown"


class LENSPhase(Enum):
    """LENS analysis phases.
    
    CORE-035: Canonical definition.
    Used by: LENS orchestrators, rollback/setup/upgrade orchestrators
    """
    LANGUAGE = "language"
    EXAMINATION = "examination"
    NAVIGATION = "navigation"
    SYNTHESIS = "synthesis"


class ResponseFormat(Enum):
    """Response format options.
    
    CORE-035: Canonical definition.
    Used by: BLUF orchestrators, response composers
    """
    BLUF_ONLY = "BLUF_ONLY"
    BLUF_HYBRID = "BLUF_HYBRID"
    FULL_DETAIL = "FULL_DETAIL"


class UserPreferenceMode(Enum):
    """User response format preference mode.
    
    CORE-035: Canonical definition.
    Used by: BLUF orchestrators, adaptive router
    """
    AUTO = "AUTO"
    BLUF = "BLUF"
    FULL = "FULL"
    BLUF_ONLY = "BLUF_ONLY"








# ============================================================================
# AUDIT & GOVERNANCE ENUMS
# ============================================================================











# ============================================================================
# CHALLENGE & INTENT ENUMS
# ============================================================================









# ============================================================================
# CHANGE & VERSION ENUMS
# ============================================================================





# ============================================================================
# CIRCUIT BREAKER & RESILIENCE ENUMS
# ============================================================================



# ============================================================================
# COHERENCE & VALIDATION ENUMS
# ============================================================================





# ============================================================================
# CONTINUATION & DECISION ENUMS
# ============================================================================





# ============================================================================
# GOVERNANCE & TIER ENUMS
# ============================================================================







# ============================================================================
# KNOWLEDGE & ANALYSIS ENUMS
# ============================================================================





# ============================================================================
# OPERATION & STATE ENUMS
# ============================================================================







# ============================================================================
# PATTERN & MATCHING ENUMS
# ============================================================================





# ============================================================================
# RESPONSE & COMMUNICATION ENUMS
# ============================================================================





# ============================================================================
# TESTING & QUALITY ENUMS
# ============================================================================







# ============================================================================
# WIRING & REGISTRY ENUMS
# ============================================================================





# ============================================================================
# WORKFLOW & EXECUTION ENUMS
# ============================================================================





# ============================================================================
# Module-level exports for star imports
# ============================================================================

__all__ = [
    # Action & Execution
    "ActionType",
    "ExecutionMode",
    # Alert & Monitoring
    "AlertSeverity",
    "AlertPriority",
    "AlertState",
    # Audit & Governance
    "AuditEventType",
    "AuditAction",
    "AuditOperationType",
    "ApprovalStatus",
    "CheckpointStatus",
    # Challenge & Intent
    "ChallengeType",
    "ChallengeCategory",
    "IntentType",
    "RoutingType",
    # Change & Version
    "ChangeType",
    "BrainTier",
    # Circuit Breaker & Resilience
    "CircuitBreakerState",
    # Coherence & Validation
    "CoherenceType",
    "ValidationLevel",
    "ValidationSeverity",
    "SeverityLevel",
    "VariableType",
    # Continuation & Decision
    "ContinuationReason",
    "DecisionStatus",
    # Governance & Tier
    "TierType",
    "GovernanceStatus",
    "RuleType",
    # Knowledge & Analysis
    "KnowledgeSource",
    "AnalysisLevel",
    # Operation & State
    "OperationStatus",
    "StateTransition",
    "PhaseStatus",
    # Pattern & Matching
    "PatternType",
    "MatchConfidence",
    # Response & Communication
    "ResponseType",
    "MessageLevel",
    # Testing & Quality
    "TestType",
    "TestStatus",
    "QualityGate",
    # Wiring & Registry
    "WiringState",
    "ComponentHealth",
    # Workflow & Execution
    "WorkflowStage",
    "ExecutionStrategy",
    # Risk & Complexity (CORE-035 Consolidated)
    "RiskLevel",
    "ComplexityLevel",
    "DisagreementType",
    "EntityType",
    "HealthStatus",
    "LENSPhase",
    "ResponseFormat",
    "UserPreferenceMode",
    "ValidationSeverity",
]
