"""
Tests for Smart File Filter (Phase 4.4)

Tests intelligent noise filtering for ambient capture.

Author: Asif Hussain
Copyright: © 2024-2025 Asif Hussain. All rights reserved.
License: Proprietary - See LICENSE file for terms

NOTE: These tests are skipped - ambient daemon removed from CORTEX 3.0
"""

import pytest
import tempfile
import time
from pathlib import Path
from unittest.mock import Mock, patch

# Add src to path
import sys
CORTEX_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(CORTEX_ROOT))


@pytest.mark.skip(reason="Ambient daemon removed from CORTEX 3.0 - manual capture hints used instead")
class TestSmartFileFilter:
    """Test suite for SmartFileFilter (DEPRECATED)."""
    
    def setup_method(self):
        """Set up test fixtures."""
        self.filter = SmartFileFilter(max_file_size_mb=1.0)
        self.temp_dir = tempfile.mkdtemp()
        self.temp_path = Path(self.temp_dir)
    
    def teardown_method(self):
        """Clean up test fixtures."""
        import shutil
        if self.temp_path.exists():
            shutil.rmtree(self.temp_path)
    
    # ========================================================================
    # Build Artifacts Tests
    # ========================================================================
    
    def test_filter_pycache(self):
        """Should filter __pycache__ files."""
        file_path = self.temp_path / "__pycache__" / "module.cpython-311.pyc"
        file_path.parent.mkdir(exist_ok=True)
        file_path.write_text("dummy")
        
        assert self.filter.is_noise_file(file_path)
    
    def test_filter_pyc_files(self):
        """Should filter .pyc files."""
        file_path = self.temp_path / "module.pyc"
        file_path.write_text("dummy")
        
        assert self.filter.is_noise_file(file_path)
    
    def test_filter_node_modules(self):
        """Should filter node_modules directory."""
        file_path = self.temp_path / "node_modules" / "package" / "index.js"
        file_path.parent.mkdir(parents=True, exist_ok=True)
        file_path.write_text("dummy")
        
        assert self.filter.is_noise_file(file_path)
    
    def test_filter_dist_build(self):
        """Should filter dist/ and build/ directories."""
        dist_file = self.temp_path / "dist" / "bundle.js"
        dist_file.parent.mkdir(exist_ok=True)
        dist_file.write_text("dummy")
        
        build_file = self.temp_path / "build" / "output.js"
        build_file.parent.mkdir(exist_ok=True)
        build_file.write_text("dummy")
        
        assert self.filter.is_noise_file(dist_file)
        assert self.filter.is_noise_file(build_file)
    
    # ========================================================================
    # Temporary Files Tests
    # ========================================================================
    
    def test_filter_temp_files(self):
        """Should filter .tmp and .temp files."""
        tmp_file = self.temp_path / "file.tmp"
        tmp_file.write_text("dummy")
        
        temp_file = self.temp_path / "file.temp"
        temp_file.write_text("dummy")
        
        assert self.filter.is_noise_file(tmp_file)
        assert self.filter.is_noise_file(temp_file)
    
    def test_filter_swap_files(self):
        """Should filter .swp files (Vim)."""
        swp_file = self.temp_path / ".file.swp"
        swp_file.write_text("dummy")
        
        assert self.filter.is_noise_file(swp_file)
    
    def test_filter_ds_store(self):
        """Should filter .DS_Store files (macOS)."""
        ds_file = self.temp_path / ".DS_Store"
        ds_file.write_text("dummy")
        
        assert self.filter.is_noise_file(ds_file)
    
    # ========================================================================
    # Auto-Generated Files Tests
    # ========================================================================
    
    def test_filter_generated_marker(self):
        """Should filter files with @generated marker."""
        gen_file = self.temp_path / "generated.py"
        gen_file.write_text("""
# @generated
# This file is auto-generated. DO NOT EDIT.

def foo():
    pass
""")
        
        assert self.filter.is_noise_file(gen_file)
    
    def test_filter_autogenerated_marker(self):
        """Should filter files with autogenerated marker."""
        gen_file = self.temp_path / "proto.py"
        gen_file.write_text("""
# Code generated by protoc. DO NOT EDIT.

class Message:
    pass
""")
        
        assert self.filter.is_noise_file(gen_file)
    
    def test_filter_generated_directory(self):
        """Should filter files in generated/ directory."""
        gen_file = self.temp_path / "generated" / "output.py"
        gen_file.parent.mkdir(exist_ok=True)
        gen_file.write_text("def foo(): pass")
        
        assert self.filter.is_noise_file(gen_file)
    
    # ========================================================================
    # Version Control Tests
    # ========================================================================
    
    def test_filter_git_directory(self):
        """Should filter .git directory files."""
        git_file = self.temp_path / ".git" / "objects" / "abc123"
        git_file.parent.mkdir(parents=True, exist_ok=True)
        git_file.write_text("dummy")
        
        assert self.filter.is_noise_file(git_file)
    
    # ========================================================================
    # IDE Files Tests
    # ========================================================================
    
    def test_filter_vscode_files(self):
        """Should filter .vscode directory files."""
        vscode_file = self.temp_path / ".vscode" / "settings.json"
        vscode_file.parent.mkdir(exist_ok=True)
        vscode_file.write_text("{}")
        
        assert self.filter.is_noise_file(vscode_file)
    
    def test_filter_idea_files(self):
        """Should filter .idea directory files."""
        idea_file = self.temp_path / ".idea" / "workspace.xml"
        idea_file.parent.mkdir(exist_ok=True)
        idea_file.write_text("<xml/>")
        
        assert self.filter.is_noise_file(idea_file)
    
    # ========================================================================
    # File Size Tests
    # ========================================================================
    
    def test_filter_large_files(self):
        """Should filter files larger than max size."""
        large_file = self.temp_path / "large.json"
        # Create file > 1MB
        large_file.write_text("x" * (1024 * 1024 + 1))
        
        assert self.filter.is_noise_file(large_file)
    
    def test_filter_empty_files(self):
        """Should filter empty files."""
        empty_file = self.temp_path / "empty.py"
        empty_file.write_text("")
        
        assert self.filter.is_noise_file(empty_file)
    
    def test_allow_normal_size_files(self):
        """Should allow files within size limit."""
        normal_file = self.temp_path / "normal.py"
        normal_file.write_text("def foo(): pass\n" * 100)
        
        assert not self.filter.is_noise_file(normal_file)
    
    # ========================================================================
    # Binary Files Tests
    # ========================================================================
    
    def test_filter_binary_files(self):
        """Should filter binary files."""
        binary_file = self.temp_path / "binary.dat"
        binary_file.write_bytes(b'\x00\x01\x02\x03\xff\xfe\xfd')
        
        assert self.filter.is_noise_file(binary_file)
    
    # ========================================================================
    # Valid Files Tests
    # ========================================================================
    
    def test_allow_python_source(self):
        """Should allow Python source files."""
        py_file = self.temp_path / "src" / "module.py"
        py_file.parent.mkdir(exist_ok=True)
        py_file.write_text("""
def hello():
    return "Hello, World!"
""")
        
        assert not self.filter.is_noise_file(py_file)
    
    def test_allow_markdown_docs(self):
        """Should allow Markdown documentation."""
        md_file = self.temp_path / "docs" / "README.md"
        md_file.parent.mkdir(exist_ok=True)
        md_file.write_text("# Documentation\n\nSome docs here.")
        
        assert not self.filter.is_noise_file(md_file)
    
    def test_allow_json_config(self):
        """Should allow JSON configuration files."""
        json_file = self.temp_path / "config.json"
        json_file.write_text('{"key": "value"}')
        
        assert not self.filter.is_noise_file(json_file)
    
    def test_allow_yaml_files(self):
        """Should allow YAML files."""
        yaml_file = self.temp_path / "config.yaml"
        yaml_file.write_text("key: value")
        
        assert not self.filter.is_noise_file(yaml_file)
    
    # ========================================================================
    # Cache Tests
    # ========================================================================
    
    def test_cache_generated_marker_check(self):
        """Should cache generated marker checks."""
        gen_file = self.temp_path / "generated.py"
        gen_file.write_text("# @generated\ndef foo(): pass")
        
        # First call - miss
        result1 = self.filter.is_noise_file(gen_file)
        
        # Second call - hit (should be faster)
        result2 = self.filter.is_noise_file(gen_file)
        
        assert result1 == result2 == True
        assert str(gen_file) in self.filter._cache
    
    def test_cache_size_limit(self):
        """Should limit cache size."""
        # Create many files to exceed cache
        for i in range(1100):
            test_file = self.temp_path / f"file{i}.py"
            test_file.write_text(f"# File {i}")
            self.filter.is_noise_file(test_file)
        
        # Cache should be trimmed
        stats = self.filter.get_filter_stats()
        assert stats['cache_size'] <= stats['max_cache_size']
    
    # ========================================================================
    # Performance Tests
    # ========================================================================
    
    def test_filtering_performance(self):
        """Should filter files quickly (<5ms per file)."""
        test_file = self.temp_path / "test.py"
        test_file.write_text("def test(): pass")
        
        start = time.time()
        for _ in range(100):
            self.filter.is_noise_file(test_file)
        duration = time.time() - start
        
        avg_time_ms = (duration / 100) * 1000
        assert avg_time_ms < 5.0, f"Filtering too slow: {avg_time_ms:.2f}ms"
    
    # ========================================================================
    # Edge Cases
    # ========================================================================
    
    def test_handle_nonexistent_file(self):
        """Should handle nonexistent files gracefully."""
        nonexistent = self.temp_path / "nonexistent.py"
        
        # Should return True (filter out)
        assert self.filter.is_noise_file(nonexistent)
    
    def test_handle_permission_error(self):
        """Should handle permission errors gracefully."""
        # This test is platform-specific
        import sys
        if sys.platform != "win32":
            no_read_file = self.temp_path / "no_read.py"
            no_read_file.write_text("def foo(): pass")
            no_read_file.chmod(0o000)
            
            # Should return True (filter out on error)
            result = self.filter.is_noise_file(no_read_file)
            
            # Clean up
            no_read_file.chmod(0o644)
            assert result == True
    
    def test_handle_unicode_filename(self):
        """Should handle Unicode filenames."""
        unicode_file = self.temp_path / "файл.py"  # Russian
        unicode_file.write_text("def test(): pass")
        
        # Should not filter valid Unicode files
        assert not self.filter.is_noise_file(unicode_file)


class TestSmartFilterIntegration:
    """Integration tests for SmartFileFilter."""
    
    def test_filter_stats(self):
        """Should return filter statistics."""
        filter = SmartFileFilter()
        stats = filter.get_filter_stats()
        
        assert 'cache_size' in stats
        assert 'max_cache_size' in stats
        assert stats['max_cache_size'] == 1000


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
