"""
RegistryMaterializer — Phase 149-c.

Writes live CORTEX framework metadata (extracted from copilot-instructions.md)
into ``cortex-registry/knowledge/cortex-frame-context/framework-context.yaml``
so that ``IntelligenceFacade.registry_index("cortex-frame-context")`` can
serve it as a structured knowledge entry.
"""
from __future__ import annotations

import datetime
import logging
from pathlib import Path
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)

_DEFAULT_OUTPUT = Path(
    "cortex-registry/knowledge/cortex-frame-context/framework-context.yaml"
)


class RegistryMaterializer:
    """
    Materializes live framework metadata into the knowledge registry.

    Reads live counts from ``CortexFrameworkAnalyzer.analyze_metadata()`` and
    writes them into ``framework-context.yaml`` so that
    ``IntelligenceFacade.registry_index("cortex-frame-context")`` can discover
    them without re-parsing the instructions file.

    Usage::

        m = RegistryMaterializer()
        path = m.write_framework_knowledge_yaml()
        print(f"Written to {path}")
    """

    def __init__(
        self,
        output_path: Optional[Path] = None,
        instructions_path: Optional[Path] = None,
    ) -> None:
        self._output = output_path or _DEFAULT_OUTPUT
        self._instructions = instructions_path

    def write_framework_knowledge_yaml(self) -> Path:
        """Extract live metadata and write ``framework-context.yaml``.

        Returns:
            Path to the written file.
        """
        meta = self._extract_metadata()
        yaml_text = self._render_yaml(meta)
        self._output.parent.mkdir(parents=True, exist_ok=True)
        self._output.write_text(yaml_text, encoding="utf-8")
        logger.info(
            "RegistryMaterializer: wrote framework-context.yaml "
            "(orchestrators=%s, mcp_tools=%s, intent_types=%s)",
            meta.get("orchestrator_count"),
            meta.get("mcp_tool_count"),
            meta.get("intent_type_count"),
        )
        return self._output

    def get_metadata(self) -> Dict[str, Any]:
        """Return extracted metadata without writing any files."""
        return self._extract_metadata()

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _extract_metadata(self) -> Dict[str, Any]:
        try:
            from cortex.lens.analyzers.cortex_framework_analyzer import (
                CortexFrameworkAnalyzer,
            )

            analyzer = CortexFrameworkAnalyzer()
            meta = analyzer.analyze_metadata(self._instructions)
            meta["materialized_at"] = datetime.datetime.utcnow().isoformat(
                timespec="seconds"
            )
            return meta
        except Exception as exc:  # pragma: no cover — graceful degradation
            logger.warning("RegistryMaterializer._extract_metadata failed: %s", exc)
            return {
                "orchestrator_count": None,
                "mcp_tool_count": None,
                "intent_type_count": None,
                "instructions_found": False,
                "materialized_at": None,
            }

    @staticmethod
    def _render_yaml(meta: Dict[str, Any]) -> str:
        """Render the framework-context.yaml file content from *meta*."""
        orch = meta.get("orchestrator_count", "null")
        mcp = meta.get("mcp_tool_count", "null")
        intent = meta.get("intent_type_count", "null")
        found = meta.get("instructions_found", False)
        ts = meta.get("materialized_at") or "null"

        return f"""\
# ==============================================================================
# CORTEX Framework Context — Knowledge Domain (generated by RegistryMaterializer)
# ==============================================================================
# Authority: Phase 149-c (GAP-149-03)
# Consumer: IntelligenceFacade.registry_index("cortex-frame-context")
# ==============================================================================

domain: cortex-frame-context
status: active
description: |
  Live framework metadata extracted from .github/copilot-instructions.md by
  RegistryMaterializer.write_framework_knowledge_yaml().  Auto-discovered by
  IntelligenceFacade.registry_index("cortex-frame-context").

metadata:
  orchestrator_count: {orch}
  mcp_tool_count: {mcp}
  intent_type_count: {intent}
  instructions_found: {str(found).lower()}
  materialized_at: "{ts}"

framework_facts:
  package: cortex
  runtime_dir: .cortex-runtime
  registry_dir: cortex-registry
  tests_dir: tests
  mcp_transport: stdio
"""
