# CORTEX Refactoring Workflow
# Safe refactoring workflow with comprehensive testing and validation

workflow_id: "refactoring"
name: "Code Refactoring Workflow"
description: "Safe refactoring workflow with automated testing and quality checks"
version: "1.0.0"

stages:
  # Stage 1: Identify refactoring targets
  - id: "identify_targets"
    script: "refactor_analyzer"
    description: "Identify code smells and refactoring opportunities"
    required: true
    depends_on: []
    timeout_seconds: 600
  
  # Stage 2: Establish baseline tests
  - id: "baseline_tests"
    script: "test_runner"
    description: "Run all tests to establish baseline"
    required: true
    depends_on: ["identify_targets"]
    timeout_seconds: 600
  
  # Stage 3: Plan refactoring
  - id: "plan_refactor"
    script: "refactor_planner"
    description: "Plan refactoring steps and strategy"
    required: true
    depends_on: ["baseline_tests"]
    timeout_seconds: 300
  
  # Stage 4: Apply refactoring
  - id: "apply_refactor"
    script: "refactor_executor"
    description: "Apply refactoring changes incrementally"
    required: true
    depends_on: ["plan_refactor"]
    retryable: true
    max_retries: 2
    timeout_seconds: 1800
  
  # Stage 5: Verify tests still pass
  - id: "verify_tests"
    script: "test_runner"
    description: "Verify all tests still pass after refactoring"
    required: true
    depends_on: ["apply_refactor"]
    retryable: true
    max_retries: 2
    timeout_seconds: 600
  
  # Stage 6: Code quality check
  - id: "quality_check"
    script: "quality_checker"
    description: "Verify code quality improvements"
    required: true
    depends_on: ["verify_tests"]
    timeout_seconds: 300
  
  # Stage 7: Cleanup (optional)
  - id: "cleanup"
    script: "code_cleanup"
    description: "Final cleanup and formatting"
    required: false
    depends_on: ["quality_check"]
    timeout_seconds: 300
