"""
Response Validation Infrastructure - AC-TEMPLATE-005 Implementation

Implements CORE-026: Mandatory Response Header Enforcement

All responses must include:
- Copyright statement with current year
- Version information matching CORTEX version
- ISO 8601 UTC timestamp
- Author attribution

This module provides:
- MandatoryHeaderEnforcer: Validates response headers
- ValidationResult: Result structure for validation
"""

from dataclasses import dataclass
from datetime import datetime
from typing import List, Optional
import re


@dataclass
class ValidationResult:
    """Result of header validation"""
    is_valid: bool
    errors: Optional[List[str]] = None
    
    def __post_init__(self):
        if self.errors is None:
            self.errors = []


class MandatoryHeaderEnforcer:
    """
    CORE-026 Enforcement: Validates that all responses include mandatory headers.
    
    Required headers:
    - Copyright: "Copyright © YYYY Author. All rights reserved."
    - Version: "CORTEX X.Y.Z" or similar
    - Timestamp: ISO 8601 UTC format
    - Author: Executor name
    """
    
    # Patterns for header detection
    COPYRIGHT_PATTERN = r'Copyright\s*©\s*(\d{4})\s+[\w\s]+\.\s*All\s+rights\s+reserved'
    VERSION_PATTERN = r'CORTEX\s+[\d\.]+'
    TIMESTAMP_PATTERN = r'\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[\.\d]*Z?\+?00:?00'
    AUTHOR_PATTERN = r'Author\s*[:=]\s*[\w\s]+'
    
    def __init__(self):
        """Initialize the header enforcer"""
        self.current_year = datetime.utcnow().year
        self.cortex_version = "6.0"  # From active CORTEX version
    
    def validate(self, response: str) -> ValidationResult:
        """
        Validate that response contains all mandatory headers.
        
        Args:
            response: Response text to validate
            
        Returns:
            ValidationResult with validation status and errors
        """
        errors = []
        
        # Check for copyright
        if not self._has_copyright(response):
            errors.append("Missing copyright statement: 'Copyright © YYYY Author. All rights reserved.'")
        
        # Check for version
        if not self._has_version(response):
            errors.append(f"Missing version statement: 'CORTEX {self.cortex_version}' or similar")
        
        # Check for timestamp
        if not self._has_timestamp(response):
            errors.append("Missing ISO 8601 UTC timestamp")
        
        # Check for author
        if not self._has_author(response):
            errors.append("Missing author attribution")
        
        is_valid = len(errors) == 0
        return ValidationResult(is_valid=is_valid, errors=errors if errors else None)
    
    def _has_copyright(self, response: str) -> bool:
        """Check if response includes copyright statement"""
        # Look for copyright pattern
        if re.search(self.COPYRIGHT_PATTERN, response, re.IGNORECASE):
            # Extract year from copyright
            match = re.search(r'Copyright\s*©\s*(\d{4})', response, re.IGNORECASE)
            if match:
                year = int(match.group(1))
                # Year should be current or recent (within 2 years)
                if abs(year - self.current_year) <= 2:
                    return True
        
        # Also accept short form
        if "Copyright" in response and "©" in response:
            return True
        
        return False
    
    def _has_version(self, response: str) -> bool:
        """Check if response includes version information"""
        return bool(re.search(self.VERSION_PATTERN, response, re.IGNORECASE))
    
    def _has_timestamp(self, response: str) -> bool:
        """Check if response includes ISO 8601 UTC timestamp"""
        # Check for ISO 8601 format
        iso_pattern = r'\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[.\d]*(\+00:00|Z)?'
        
        if re.search(iso_pattern, response):
            return True
        
        # Also accept "Date:" or "Timestamp:" labels
        if re.search(r'(Date|Timestamp):\s*\d{4}-\d{2}-\d{2}', response, re.IGNORECASE):
            return True
        
        return False
    
    def _has_author(self, response: str) -> bool:
        """Check if response includes author attribution"""
        # Look for explicit author field
        if re.search(self.AUTHOR_PATTERN, response, re.IGNORECASE):
            return True
        
        # Also accept common author mentions
        if re.search(r'(Author|By|Generated By)\s*[:=]\s*[\w\s]+', response, re.IGNORECASE):
            return True
        
        # Check for Copilot or similar
        if any(x in response for x in ['Copilot', 'GitHub Copilot', 'CORTEX Orchestrator']):
            return True
        
        return False
