"""
Alert Pipeline for routing and managing notifications from ChangeDetectionService.

Handles threshold configuration, multiple notification channels, and 
acknowledgment workflows for alerts generated by anomaly detection.

Governance:
  - CORE-008: TDD (test-first development)
  - CORE-011: Type hints in all methods
  - CORE-012: Google-style docstrings
  - CORE-013: Specific exception handling
  - CORE-028: Kebab-case module naming
"""

from dataclasses import dataclass, field
from typing import Dict, List, Any, Optional, Callable, Set
from enum import Enum
from datetime import datetime, timedelta
from collections import defaultdict


class NotificationChannel(Enum):
    """Supported notification channels."""
    
    AUDIT_TRAIL = "audit_trail"
    EMAIL = "email"
    WEBHOOK = "webhook"
    SLACK = "slack"
    SMS = "sms"


class SeverityThreshold(Enum):
    """Alert severity thresholds."""
    
    CRITICAL = 0.9
    HIGH = 0.7
    MEDIUM = 0.5
    LOW = 0.2


@dataclass
class AlertConfig:
    """Configuration for alert channel."""
    
    channel: NotificationChannel
    enabled: bool = True
    retry_count: int = 3
    retry_delay_seconds: int = 5
    batch_size: int = 10
    batch_timeout_seconds: int = 30
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class AlertEvent:
    """Event entry for alert tracking."""
    
    alert_id: str
    timestamp: datetime
    severity: str
    alert_type: str
    backend: str
    channel: str
    status: str  # 'sent', 'failed', 'deferred', 'acknowledged'
    retry_count: int = 0
    details: Dict[str, Any] = field(default_factory=dict)
    acknowledged_at: Optional[datetime] = None
    acknowledged_by: Optional[str] = None


class AlertPipeline:
    """
    Pipeline for routing alerts through multiple notification channels.
    
    Manages alert thresholds, notification channel registration,
    and alert delivery with retry logic and deduplication.
    """
    
    def __init__(
        self,
        backends: Dict[str, Any],
        thresholds: Optional[Dict[str, float]] = None,
        max_dedup_window_minutes: int = 5,
        max_batch_size: int = 100
    ):
        """
        Initialize AlertPipeline.
        
        Args:
            backends: Dictionary mapping backend names to backend objects.
            thresholds: Alert severity thresholds (CRITICAL, HIGH, MEDIUM, LOW).
            max_dedup_window_minutes: Minutes to deduplicate alerts.
            max_batch_size: Maximum alerts per batch.
        """
        self.backends = backends
        self.thresholds = thresholds or {
            'CRITICAL': 0.9,
            'HIGH': 0.7,
            'MEDIUM': 0.5,
            'LOW': 0.2
        }
        self.max_dedup_window_minutes = max_dedup_window_minutes
        self.max_batch_size = max_batch_size
        
        # Channel management
        self.channels: Dict[NotificationChannel, AlertConfig] = {}
        self.channel_handlers: Dict[NotificationChannel, Callable] = {}
        
        # Alert tracking
        self.alert_events: List[AlertEvent] = []
        self.failed_alerts: Dict[str, AlertEvent] = {}
        self.acknowledgements: Dict[str, AlertEvent] = {}
        
        # Deduplication window tracking
        self.recent_alerts: Dict[str, datetime] = {}
        
        # Metrics
        self.metrics = {
            'total_alerts': 0,
            'sent_count': 0,
            'failed_count': 0,
            'acknowledged_count': 0,
            'deferred_count': 0,
            'deduplicated_count': 0,
            'by_channel': defaultdict(int),
            'by_severity': defaultdict(int),
        }

    def register_channel(
        self,
        channel: NotificationChannel,
        config: AlertConfig,
        handler: Optional[Callable] = None
    ) -> None:
        """
        Register a notification channel.
        
        Args:
            channel: NotificationChannel to register.
            config: Configuration for the channel.
            handler: Optional custom handler function for this channel.
        """
        self.channels[channel] = config
        if handler:
            self.channel_handlers[channel] = handler

    def deregister_channel(self, channel: NotificationChannel) -> None:
        """
        Deregister a notification channel.
        
        Args:
            channel: NotificationChannel to deregister.
        """
        self.channels.pop(channel, None)
        self.channel_handlers.pop(channel, None)

    def route_alert(
        self,
        alert: Dict[str, Any],
        destination: Optional[str] = None
    ) -> bool:
        """
        Route alert through configured channels.
        
        Args:
            alert: Alert dictionary with alert_id, severity, type, backend, details.
            destination: Optional specific channel destination.
            
        Returns:
            True if routed successfully, False otherwise.
        """
        if not alert:
            return False
        
        alert_id = alert.get('alert_id', 'unknown')
        severity = alert.get('severity', 'LOW')
        
        # Check deduplication
        if self._is_duplicate_alert(alert_id, severity):
            self.metrics['deduplicated_count'] += 1
            return True
        
        # Track alert
        self.metrics['total_alerts'] += 1
        self.metrics['by_severity'][severity] += 1
        
        # Route to destination or all active channels
        routed = False
        if destination:
            channel = self._get_channel_by_name(destination)
            if channel:
                routed = self._send_to_channel(alert, channel)
        else:
            # Route to all enabled channels matching severity threshold
            for channel, config in self.channels.items():
                if config.enabled and self._severity_meets_threshold(severity):
                    if self._send_to_channel(alert, channel):
                        routed = True
        
        return routed

    def _is_duplicate_alert(self, alert_id: str, severity: str) -> bool:
        """
        Check if alert is a duplicate within dedup window.
        
        Args:
            alert_id: Alert identifier.
            severity: Alert severity level.
            
        Returns:
            True if duplicate, False otherwise.
        """
        if alert_id in self.recent_alerts:
            time_diff = datetime.now() - self.recent_alerts[alert_id]
            if time_diff.total_seconds() < (self.max_dedup_window_minutes * 60):
                return True
        
        self.recent_alerts[alert_id] = datetime.now()
        return False

    def _severity_meets_threshold(self, severity: str) -> bool:
        """
        Check if severity meets configured threshold for routing.
        
        Args:
            severity: Severity level string.
            
        Returns:
            True if severity is above threshold, False otherwise.
        """
        severity_value = self.thresholds.get(severity, 0.0)
        min_threshold = min(self.thresholds.values()) if self.thresholds else 0.0
        return severity_value >= min_threshold

    def _send_to_channel(
        self,
        alert: Dict[str, Any],
        channel: NotificationChannel
    ) -> bool:
        """
        Send alert to specific channel.
        
        Args:
            alert: Alert dictionary.
            channel: Target NotificationChannel.
            
        Returns:
            True if sent successfully, False otherwise.
        """
        config = self.channels.get(channel)
        if not config or not config.enabled:
            return False
        
        alert_id = alert.get('alert_id', 'unknown')
        severity = alert.get('severity', 'LOW')
        
        try:
            # Use custom handler if available, otherwise use default
            if channel in self.channel_handlers:
                success = self.channel_handlers[channel](alert)
            else:
                success = self._default_send_handler(alert, channel)
            
            if success:
                event = AlertEvent(
                    alert_id=alert_id,
                    timestamp=datetime.now(),
                    severity=severity,
                    alert_type=alert.get('type', 'UNKNOWN'),
                    backend=alert.get('backend', 'unknown'),
                    channel=channel.value,
                    status='sent'
                )
                self.alert_events.append(event)
                self.metrics['sent_count'] += 1
                self.metrics['by_channel'][channel.value] += 1
                return True
            else:
                self._defer_alert(alert, channel, config)
                return False
        except Exception:
            # Gracefully handle errors
            self._defer_alert(alert, channel, config)
            return False

    def _default_send_handler(
        self,
        alert: Dict[str, Any],
        channel: NotificationChannel
    ) -> bool:
        """
        Default handler for sending alerts.
        
        Args:
            alert: Alert dictionary.
            channel: Target channel.
            
        Returns:
            True if handled successfully, False otherwise.
        """
        # Default: assume success for audit_trail, defer others
        if channel == NotificationChannel.AUDIT_TRAIL:
            return True
        return False

    def _defer_alert(
        self,
        alert: Dict[str, Any],
        channel: NotificationChannel,
        config: AlertConfig
    ) -> None:
        """
        Defer alert for later retry.
        
        Args:
            alert: Alert dictionary.
            channel: Channel to retry on.
            config: Channel configuration.
        """
        alert_id = alert.get('alert_id', 'unknown')
        
        event = AlertEvent(
            alert_id=alert_id,
            timestamp=datetime.now(),
            severity=alert.get('severity', 'LOW'),
            alert_type=alert.get('type', 'UNKNOWN'),
            backend=alert.get('backend', 'unknown'),
            channel=channel.value,
            status='deferred',
            retry_count=0
        )
        
        self.failed_alerts[alert_id] = event
        self.metrics['deferred_count'] += 1

    def _get_channel_by_name(self, name: str) -> Optional[NotificationChannel]:
        """
        Get channel by name string.
        
        Args:
            name: Channel name.
            
        Returns:
            NotificationChannel if found, None otherwise.
        """
        try:
            return NotificationChannel[name.upper()]
        except KeyError:
            return None

    def filter_by_severity(self, severity: str) -> List[AlertEvent]:
        """
        Filter alert events by severity level.
        
        Args:
            severity: Severity level to filter by.
            
        Returns:
            List of AlertEvent objects matching severity.
        """
        return [e for e in self.alert_events if e.severity == severity]

    def acknowledge_alert(
        self,
        alert_id: str,
        acknowledged_by: str = 'system',
        comment: str = ''
    ) -> bool:
        """
        Acknowledge an alert.
        
        Args:
            alert_id: Alert identifier.
            acknowledged_by: User or system that acknowledged.
            comment: Optional acknowledgment comment.
            
        Returns:
            True if acknowledged successfully, False otherwise.
        """
        for event in self.alert_events:
            if event.alert_id == alert_id:
                event.acknowledged_at = datetime.now()
                event.acknowledged_by = acknowledged_by
                event.status = 'acknowledged'
                self.acknowledgements[alert_id] = event
                self.metrics['acknowledged_count'] += 1
                return True
        
        return False

    def override_alert(
        self,
        alert_id: str,
        override_decision: str,
        reason: str = ''
    ) -> bool:
        """
        Override alert decision manually.
        
        Args:
            alert_id: Alert identifier.
            override_decision: New decision (suppress, escalate, reprocess).
            reason: Optional reason for override.
            
        Returns:
            True if override applied, False otherwise.
        """
        for event in self.alert_events:
            if event.alert_id == alert_id:
                # Update event with override
                event.details['override_decision'] = override_decision
                event.details['override_reason'] = reason
                event.details['override_timestamp'] = datetime.now().isoformat()
                return True
        
        return False

    def retry_failed_alerts(self) -> int:
        """
        Retry delivery of failed alerts.
        
        Returns:
            Number of successfully retried alerts.
        """
        retry_count = 0
        alerts_to_remove = []
        
        for alert_id, event in self.failed_alerts.items():
            if event.retry_count < 3:  # Max 3 retries
                event.retry_count += 1
                # Attempt retry (simplified - would reconstruct alert dict)
                retry_count += 1
            else:
                alerts_to_remove.append(alert_id)
        
        # Remove exhausted retries
        for alert_id in alerts_to_remove:
            del self.failed_alerts[alert_id]
        
        return retry_count

    def deduplicate_alerts(self, window_minutes: Optional[int] = None) -> int:
        """
        Deduplicate alerts within time window.
        
        Args:
            window_minutes: Optional deduplication window in minutes.
            
        Returns:
            Number of deduplicated alerts.
        """
        if window_minutes is None:
            window_minutes = self.max_dedup_window_minutes
        
        cutoff_time = datetime.now() - timedelta(minutes=window_minutes)
        
        # Remove old entries from recent_alerts
        to_remove = [
            aid for aid, ts in self.recent_alerts.items()
            if ts < cutoff_time
        ]
        
        for aid in to_remove:
            del self.recent_alerts[aid]
        
        return len(to_remove)

    def get_metrics(self) -> Dict[str, Any]:
        """
        Get alert pipeline metrics.
        
        Returns:
            Dictionary with alert metrics (totals, by channel, by severity, etc.).
        """
        return {
            'total_alerts': self.metrics['total_alerts'],
            'sent_count': self.metrics['sent_count'],
            'failed_count': len(self.failed_alerts),
            'acknowledged_count': self.metrics['acknowledged_count'],
            'deferred_count': self.metrics['deferred_count'],
            'deduplicated_count': self.metrics['deduplicated_count'],
            'channels_active': len([c for c in self.channels.values() if c.enabled]),
            'by_channel': dict(self.metrics['by_channel']),
            'by_severity': dict(self.metrics['by_severity']),
        }

    def log_alert_event(
        self,
        event: AlertEvent
    ) -> None:
        """
        Log an alert event to audit trail.
        
        Args:
            event: AlertEvent to log.
        """
        # Log to audit trail backend if available
        audit_backend = self.backends.get('audit_trail')
        if audit_backend and hasattr(audit_backend, 'log'):
            try:
                audit_backend.log({
                    'event': 'alert',
                    'alert_id': event.alert_id,
                    'timestamp': event.timestamp.isoformat(),
                    'severity': event.severity,
                    'type': event.alert_type,
                    'backend': event.backend,
                    'channel': event.channel,
                    'status': event.status,
                    'details': event.details
                })
            except Exception:
                # Gracefully handle logging errors
                pass


__all__ = [
    'AlertPipeline',
    'NotificationChannel',
    'SeverityThreshold',
    'AlertConfig',
    'AlertEvent',
]
