classDiagram
    class Updater_CreateRAFundingInvoices {
        +Run
    }
    class Constants
    Updater_CreateRAFundingInvoices --> Constants
    class Utilities
    Updater_CreateRAFundingInvoices --> Utilities
    class Components
    Updater_CreateRAFundingInvoices --> Components
