# tests/regression/guards — auto-generated regression guard tests
# Authority: Phase 106-A (GAP-106-01)
# DO NOT hand-edit individual guard files — they are generated by
# regression-guard-generator.yaml primitive after each audit-fix auto-fix.
