# TIER 3: CONTEXT AWARENESS - Productivity Patterns
# Version: 1.0 (migrated from kds-brain/development-context.yaml)
# Last Updated: 2025-11-03
# Purpose: Productivity metrics and work pattern analysis
# Auto-updated by: brain/housekeeping/services/context-updater/

work_patterns:
  avg_coding_hours_per_day: 0.00
  most_productive_time: "unknown"
  
  session_patterns:
    morning_sessions: 0.00
    afternoon_sessions: 0.00
    evening_sessions: 0.00
  
  focus_duration:
    avg_without_interruption: "0 hours"
    longest_session: "0 hours"
    longest_session_date: null
  
  feature_lifecycle:
    avg_days_from_start_to_deploy: 0.00
    avg_iterations_per_feature: 0.00
  
  last_updated: "2025-11-03T10:31:04Z"

correlations:
  kds_usage_vs_velocity:
    correlation: null
    high_kds_weeks: []
    high_kds_velocity: null
    low_kds_weeks: []
    low_kds_velocity: null
    insight: null
  
  commit_size_vs_success:
    small_commits_range: "1-3 files"
    small_commit_success_rate: null
    large_commits_range: "10+ files"
    large_commit_success_rate: null
    insight: null
  
  test_first_vs_rework:
    test_first_rework_rate: null
    test_skip_rework_rate: null
    insight: null
  
  last_updated: "2025-11-03T10:31:04Z"

statistics:
  enabled: true
  version: 1.0
  collection_frequency: "hourly"
  last_collection: "2025-11-03T10:31:04Z"
  total_metrics_collected: 5
  total_storage_kb: 0
  data_sources:
    - "git"
    - "kds-events"
    - "test-results"
    - "build-logs"
  last_updated: "2025-11-03T10:31:04Z"

metadata:
  version: "1.0"
  last_updated: "2025-11-03T10:31:04Z"
  source: "kds-brain/development-context.yaml"
  migration_date: "2025-11-04"
  tier: 3
  purpose: "Productivity patterns and correlations for understanding what works best"
  auto_managed: true
  housekeeping_service: "context-updater"
  collection_frequency: "hourly"
