"""
Agent Evaluation Framework

Phase 5 Task 5.10: Agent Evaluation Framework
LLM-as-judge for evaluating agent reasoning, efficiency, and quality.

Evaluation Criteria:
- Reasoning quality (1-10)
- Token efficiency
- Tool usage appropriateness
- Context relevance
- Output correctness

Author: CORTEX Development Team
Version: 1.0.0
Created: 2025-12-21
"""

import json
import logging
from typing import Dict, Any, List, Optional
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum

logger = logging.getLogger(__name__)


class EvaluationCategory(Enum):
    """Evaluation categories"""
    REASONING = "reasoning"
    EFFICIENCY = "efficiency"
    TOOL_USAGE = "tool_usage"
    CONTEXT_RELEVANCE = "context_relevance"
    CORRECTNESS = "correctness"


@dataclass
class EvaluationResult:
    """Result from agent evaluation"""
    agent_name: str
    category: EvaluationCategory
    score: float  # 1-10
    reasoning: str
    metrics: Dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.now)


class AgentEvaluator:
    """
    Evaluate agent performance using LLM-as-judge pattern.
    
    Uses LLM to judge:
    - Reasoning quality (score 1-10)
    - Token efficiency (tokens per output quality unit)
    - Tool usage appropriateness
    - Context relevance
    """
    
    def __init__(self, llm_client: Optional[Any] = None):
        """
        Initialize evaluator.
        
        Args:
            llm_client: LLM client for evaluation (optional, can use mock)
        """
        self.llm = llm_client
        self.evaluation_history: List[EvaluationResult] = []
    
    async def evaluate_reasoning(
        self,
        agent_name: str,
        input_context: str,
        agent_output: str,
        expected_output: Optional[str] = None
    ) -> EvaluationResult:
        """
        Evaluate agent reasoning quality using LLM-as-judge.
        
        Args:
            agent_name: Name of agent being evaluated
            input_context: Input context provided to agent
            agent_output: Output generated by agent
            expected_output: Optional expected output for comparison
            
        Returns:
            EvaluationResult with reasoning score (1-10) and explanation
        """
        prompt = self._build_reasoning_prompt(
            input_context,
            agent_output,
            expected_output
        )
        
        if self.llm:
            try:
                response = await self.llm.complete(prompt)
                score, reasoning = self._parse_llm_response(response)
            except Exception as e:
                logger.error(f"LLM evaluation failed: {e}")
                score, reasoning = self._fallback_evaluation(agent_output)
        else:
            # Fallback: heuristic-based evaluation
            score, reasoning = self._fallback_evaluation(agent_output)
        
        result = EvaluationResult(
            agent_name=agent_name,
            category=EvaluationCategory.REASONING,
            score=score,
            reasoning=reasoning,
            metrics={
                'input_length': len(input_context),
                'output_length': len(agent_output),
            }
        )
        
        self.evaluation_history.append(result)
        logger.info(f"📊 {agent_name} reasoning: {score}/10")
        
        return result
    
    def evaluate_efficiency(
        self,
        agent_name: str,
        tokens_used: int,
        output_quality: float,
        execution_time_seconds: float
    ) -> EvaluationResult:
        """
        Evaluate token efficiency.
        
        Args:
            agent_name: Name of agent
            tokens_used: Total tokens consumed
            output_quality: Quality score of output (1-10)
            execution_time_seconds: Execution time
            
        Returns:
            EvaluationResult with efficiency score
        """
        # Efficiency = quality / (tokens + time_penalty)
        time_penalty = execution_time_seconds / 10  # 10s = 1 token equivalent
        efficiency = output_quality / (tokens_used + time_penalty)
        
        # Normalize to 1-10 scale (assuming ideal is 0.01 efficiency)
        score = min(efficiency * 1000, 10)
        
        result = EvaluationResult(
            agent_name=agent_name,
            category=EvaluationCategory.EFFICIENCY,
            score=score,
            reasoning=f"Used {tokens_used} tokens in {execution_time_seconds:.1f}s for quality {output_quality}/10",
            metrics={
                'tokens_used': tokens_used,
                'execution_time': execution_time_seconds,
                'efficiency_ratio': efficiency,
            }
        )
        
        self.evaluation_history.append(result)
        logger.info(f"📊 {agent_name} efficiency: {score:.1f}/10")
        
        return result
    
    def evaluate_tool_usage(
        self,
        agent_name: str,
        tools_used: List[str],
        tools_available: List[str],
        context: Dict[str, Any]
    ) -> EvaluationResult:
        """
        Evaluate tool usage appropriateness.
        
        Args:
            agent_name: Name of agent
            tools_used: List of tools actually used
            tools_available: List of all available tools
            context: Context for judging appropriateness
            
        Returns:
            EvaluationResult with tool usage score
        """
        # Heuristics for tool usage quality
        score = 5.0  # Start neutral
        reasoning_parts = []
        
        # Penalty for using no tools when tools would help
        if len(tools_used) == 0 and len(tools_available) > 0:
            score -= 2
            reasoning_parts.append("No tools used when tools were available")
        
        # Bonus for using appropriate number of tools
        if 1 <= len(tools_used) <= 3:
            score += 2
            reasoning_parts.append(f"Appropriate tool count: {len(tools_used)}")
        elif len(tools_used) > 5:
            score -= 1
            reasoning_parts.append(f"Excessive tool usage: {len(tools_used)}")
        
        # Check for redundant tool calls
        if len(tools_used) != len(set(tools_used)):
            score -= 1
            reasoning_parts.append("Redundant tool calls detected")
        
        score = max(1, min(score, 10))
        
        result = EvaluationResult(
            agent_name=agent_name,
            category=EvaluationCategory.TOOL_USAGE,
            score=score,
            reasoning="; ".join(reasoning_parts) if reasoning_parts else "Tool usage appropriate",
            metrics={
                'tools_used_count': len(tools_used),
                'tools_available_count': len(tools_available),
                'tools_used': tools_used,
            }
        )
        
        self.evaluation_history.append(result)
        logger.info(f"📊 {agent_name} tool usage: {score}/10")
        
        return result
    
    def evaluate_context_relevance(
        self,
        agent_name: str,
        input_context: str,
        agent_output: str
    ) -> EvaluationResult:
        """
        Evaluate how relevant agent output is to input context.
        
        Args:
            agent_name: Name of agent
            input_context: Input context
            agent_output: Agent output
            
        Returns:
            EvaluationResult with relevance score
        """
        # Simple keyword overlap heuristic (can be enhanced with embeddings)
        input_words = set(input_context.lower().split())
        output_words = set(agent_output.lower().split())
        
        overlap = len(input_words & output_words)
        overlap_ratio = overlap / max(len(input_words), 1)
        
        # Score based on overlap ratio
        score = min(overlap_ratio * 20, 10)  # 50% overlap = 10/10
        
        result = EvaluationResult(
            agent_name=agent_name,
            category=EvaluationCategory.CONTEXT_RELEVANCE,
            score=score,
            reasoning=f"{overlap_ratio*100:.1f}% keyword overlap with input context",
            metrics={
                'overlap_ratio': overlap_ratio,
                'overlapping_words': overlap,
            }
        )
        
        self.evaluation_history.append(result)
        logger.info(f"📊 {agent_name} context relevance: {score:.1f}/10")
        
        return result
    
    def get_overall_score(self, agent_name: str) -> float:
        """
        Calculate overall score for agent across all evaluations.
        
        Args:
            agent_name: Name of agent
            
        Returns:
            Average score across all evaluations (1-10)
        """
        agent_evaluations = [
            e for e in self.evaluation_history
            if e.agent_name == agent_name
        ]
        
        if not agent_evaluations:
            return 5.0  # Neutral default
        
        avg_score = sum(e.score for e in agent_evaluations) / len(agent_evaluations)
        return avg_score
    
    def _build_reasoning_prompt(
        self,
        input_context: str,
        agent_output: str,
        expected_output: Optional[str]
    ) -> str:
        """Build LLM prompt for reasoning evaluation"""
        prompt = f"""
Evaluate the quality of this agent's reasoning (score 1-10):

## Input Context
{input_context}

## Agent Output
{agent_output}
"""
        
        if expected_output:
            prompt += f"""
## Expected Output (for reference)
{expected_output}
"""
        
        prompt += """
## Evaluation Criteria
- Logical coherence (is reasoning sound?)
- Completeness (addresses all aspects of input?)
- Clarity (easy to understand?)
- Correctness (factually accurate?)

Respond in JSON format:
{
    "score": <1-10>,
    "reasoning": "<brief explanation>"
}
"""
        return prompt
    
    def _parse_llm_response(self, response: str) -> tuple[float, str]:
        """Parse LLM evaluation response"""
        try:
            data = json.loads(response)
            score = float(data.get('score', 5.0))
            reasoning = data.get('reasoning', 'No reasoning provided')
            return max(1, min(score, 10)), reasoning
        except (json.JSONDecodeError, ValueError, KeyError) as e:
            logger.error(f"Failed to parse LLM response: {e}")
            return 5.0, "Failed to parse LLM evaluation"
    
    def _fallback_evaluation(self, agent_output: str) -> tuple[float, str]:
        """Fallback heuristic evaluation when LLM unavailable"""
        # Simple heuristics
        score = 5.0
        reasoning_parts = []
        
        # Length heuristic
        if len(agent_output) < 50:
            score -= 2
            reasoning_parts.append("Output too brief")
        elif 100 <= len(agent_output) <= 500:
            score += 1
            reasoning_parts.append("Appropriate output length")
        
        # Structure heuristic
        if '\n' in agent_output:
            score += 1
            reasoning_parts.append("Well-structured with line breaks")
        
        score = max(1, min(score, 10))
        reasoning = "; ".join(reasoning_parts) if reasoning_parts else "Heuristic evaluation"
        
        return score, reasoning
