classDiagram
    class XGenerateFundingInvoice {
        +Execute
    }
    class IoC
    XGenerateFundingInvoice --> IoC
    class Utilities
    XGenerateFundingInvoice --> Utilities
    class Abstractions
    XGenerateFundingInvoice --> Abstractions
    class Paragon
    XGenerateFundingInvoice --> Paragon
