"""
RCA Models — Phase 87: RCA Memory Engine.

Provides structured data types for the Root Cause Analysis engine:
  - RCATemplate: four analysis methodologies
  - RCACategory: four failure categories (Fishbone axes)
  - GateLevel: three prevention gate levels
  - RCAAnalysis: full structured RCA result dataclass
  - PreventionRule: actionable prevention rule derived from RCA
  - PreventionGateResult: result of a prevention gate check

AC-PHASE87-001: RCAAnalysis dataclass + RCATemplate enum — structured RCA methodology
CORE-011: Type hints on all functions
CORE-012: Docstrings on all public APIs
CORE-028: snake_case file naming
CORE-035: Single canonical implementation — no duplicates
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, Optional


class RCATemplate(Enum):
    """
    Root Cause Analysis methodology selection.

    Four proven industrial methodologies:
      FIVE_WHYS    — linear causal chain (most common)
      FISHBONE     — multi-category Ishikawa diagram
      FAULT_TREE   — probability-weighted AND/OR gate tree
      CAUSAL_CHAIN — time-ordered event sequence
    """

    FIVE_WHYS = "five_whys"
    FISHBONE = "fishbone"
    FAULT_TREE = "fault_tree"
    CAUSAL_CHAIN = "causal_chain"


class RCACategory(Enum):
    """
    Root cause failure category — maps to Fishbone (Ishikawa) diagram axes.

    TECHNOLOGY — Framework, library, language, infrastructure failures
    PROCESS    — Missing steps, skipped validation, workflow gaps
    PEOPLE     — Assumptions, context switch errors, knowledge gaps
    DATA       — Stale fixtures, unrepresentative mocks, schema drift
    """

    TECHNOLOGY = "technology"
    PROCESS = "process"
    PEOPLE = "people"
    DATA = "data"


class GateLevel(Enum):
    """
    Prevention Gate escalation level.

    PASS     — No matching prevention rule found; operation proceeds normally.
    ADVISORY — 1st recurrence; info surfaced in next OPJ consult.
    WARNING  — 2nd recurrence; governance gate response includes RCA reference.
    BLOCKING — 3+ P0 recurrences; operation halted; structured review required.
    """

    PASS = "pass"
    ADVISORY = "advisory"
    WARNING = "warning"
    BLOCKING = "blocking"


@dataclass
class PreventionRule:
    """
    Actionable prevention rule derived from a structured RCA.

    Generated by RCAEngine.generate_prevention_rule() and stored in
    RCAStore.prevention_rules table.

    Attributes:
        id: Unique rule identifier — "PREV-{uuid}".
        rca_id: Foreign key to the originating RCAAnalysis.
        rule_text: Human-readable prevention rule.
        gate_level: Escalation level when this rule fires.
        active: Whether the rule is currently enforced. Defaults to True.
        trigger_count: Number of times this rule has fired.
        false_positive_count: Times the rule fired incorrectly (bypass count).
        created_at: ISO timestamp when rule was created.
    """

    id: str
    rca_id: str
    rule_text: str
    gate_level: GateLevel
    active: bool = True
    trigger_count: int = 0
    false_positive_count: int = 0
    created_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())


@dataclass
class RCAAnalysis:
    """
    Full structured result of a Root Cause Analysis.

    Produced by RCAEngine and persisted in RCAStore.rca_analyses table.
    Carries the methodology-specific analysis in analysis_data, and
    optionally a prevention_rule derived from the analysis.

    Attributes:
        id: Unique RCA identifier — "RCA-{uuid}".
        failure_id: OPJ failure entry this RCA was triggered from.
        methodology: Which RCATemplate methodology was applied.
        category: The RCACategory classifying this failure.
        root_cause: Structured root cause string (result of analysis).
        confidence: Confidence in the analysis — 0.0 to 1.0.
        analysis_data: Methodology-specific structured data.
            FIVE_WHYS  → {"whys": [{"why": str, "answer": str}]}
            FISHBONE   → {"categories": {"technology": [...], "process": [...], ...}}
            FAULT_TREE → {"gates": [{"type": "AND|OR", "children": [...]}]}
            CAUSAL_CHAIN → {"events": [{"time_delta_ms": int, "event": str}]}
        prevention_rule: Optional rule generated from this analysis.
        recurrence_signature: Canonical fingerprint for matching.
        created_at: ISO timestamp.
    """

    id: str
    failure_id: str
    methodology: RCATemplate
    category: RCACategory
    root_cause: str
    confidence: float
    analysis_data: Dict[str, Any] = field(default_factory=dict)
    prevention_rule: Optional[PreventionRule] = None
    recurrence_signature: Optional[str] = None
    created_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())


@dataclass
class PreventionGateResult:
    """
    Result of a prevention gate check against stored prevention rules.

    Returned by PreventionGate.check(operation_context).

    Attributes:
        gate_level: The escalation level determined by the check.
        matched_rule: The PreventionRule that triggered, or None for PASS.
        similarity_score: Similarity between operation and matched rule (0.0–1.0).
        rca_summary: Brief summary of the matched RCA for inline display.
        message: Human-readable message for the developer (Advisory/Warning/Blocking text).
    """

    gate_level: GateLevel
    matched_rule: Optional[PreventionRule] = None
    similarity_score: float = 0.0
    rca_summary: Optional[str] = None
    message: Optional[str] = None
