"""
TDDExecutionMixin — RED/GREEN/REFACTOR phase execution methods.

Extracted from tdd_orchestrator.py (Phase 103-c).
Owns: execute_with_directive, brittleness scan hooks, phase completion hook,
_execute_domain_logic, _determine_tdd_phase, _build_tdd_guidance,
_select_test_patterns, _execute_tdd_phase, _execute_{red,green,refactor}_phase,
get_tdd_status, create_test_stub.

Governance:
- CORE-011: Type hints on all functions
- CORE-012: Docstrings on all public APIs
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import TYPE_CHECKING, Any, Dict, List, Optional

from cortex.core.result import Err, Ok, Result
from cortex.orchestrators.core.tdd_orchestrator.tdd_models import (
    GateResult,
    SuccessCriteria,
    TDDImplementationGuidance,
    TDDPhase,
)

if TYPE_CHECKING:
    from cortex.orchestrators.intelligence.agent_rules_interpreter import ExecutionDirective

logger = logging.getLogger(__name__)


class TDDExecutionMixin:
    """Mixin that provides RED → GREEN → REFACTOR phase execution logic.

    Intended to be mixed into :class:`TDDOrchestrator`.  All methods rely on
    ``self.knowledge_loader``, ``self.guidance_engine``, and the OPJ helpers
    (``_opj_consult``, ``_opj_record_success``, ``_opj_record_failure``)
    provided by the coordinator class.
    """

    # ------------------------------------------------------------------
    # Public: create_test_stub
    # ------------------------------------------------------------------

    def create_test_stub(
        self,
        gap: Dict[str, Any],
        output_dir: Optional[Path] = None,
    ) -> Path:
        """Generate a TDD RED phase test stub for a given intelligence gap.

        Called by BlindSpotDetector to auto-generate RED phase test files for
        newly detected gaps (GAP-66-014 — Phase 66-B).

        Args:
            gap: Gap descriptor dict with keys: ``gap_id``, ``description``,
                 ``severity``, ``x`` (source), ``y`` (target).
            output_dir: Directory to write the stub file.
                        Defaults to ``tests/unit/stubs/``.

        Returns:
            Path to the written ``.py`` stub file.
        """
        # AC_START: AC-66-B-003-CREATE-TEST-STUB-20260224T000000Z
        if output_dir is None:
            output_dir = Path("tests/unit/stubs")
        output_dir.mkdir(parents=True, exist_ok=True)

        gap_id = gap.get("gap_id", "GAP-UNKNOWN")
        description = gap.get("description", "No description provided.")
        severity = gap.get("severity", "P1")
        source_x = gap.get("x", "SourceComponent")
        target_y = gap.get("y", "TargetComponent")

        slug = gap_id.lower().replace("-", "_").replace(" ", "_")
        stub_path = output_dir / f"test_stub_{slug}.py"

        stub_content = f'''"""
TDD RED phase stub — {gap_id}: {description}

Auto-generated by TDDOrchestrator.create_test_stub() (GAP-66-014).
Severity: {severity}
Wire: {source_x} → {target_y}

CORE-008: This file is the RED phase. Implement GREEN code to make these pass.
Author: CORTEX AutoStub
"""
import pytest
from typing import Any

# AC_START: AC-{slug.upper()}-STUB-RED


class TestStub{gap_id.replace("-", "").replace("_", "")}:
    """RED-phase stubs for {gap_id}: {description}"""

    def test_source_component_exists(self) -> None:
        """Verify {source_x} is importable (RED — will fail until implemented)."""
        pytest.skip("RED stub — implement GREEN code for {gap_id}")

    def test_target_wiring(self) -> None:
        """Verify {source_x} → {target_y} wiring (RED — implement GREEN)."""
        pytest.skip("RED stub — implement GREEN code for {gap_id}")


# AC_COMPLETE: AC-{slug.upper()}-STUB-RED ✅ (stub generated)
'''
        stub_path.write_text(stub_content, encoding="utf-8")
        logger.info(f"[TDDOrchestrator] Created RED stub: {stub_path} for {gap_id}")
        # AC_COMPLETE: AC-66-B-003-CREATE-TEST-STUB-20260224T000000Z ✅
        return stub_path

    # ------------------------------------------------------------------
    # Public: execute_with_directive
    # ------------------------------------------------------------------

    def execute_with_directive(
        self,
        directive: "ExecutionDirective",
        context: Dict[str, Any],
    ) -> Result:
        """Execute TDD workflow with ExecutionDirective from Phase 52.

        AC-PHASE52-002: TDDOrchestrator accepts ExecutionDirective.

        Args:
            directive: ExecutionDirective from AgentRulesInterpreter.
            context: Execution context with module_path, etc.

        Returns:
            Result with TDD execution outcome.
        """
        try:
            logger.info(
                f"TDD executing with directive: "
                f"agent={directive.agent_id}, "
                f"rules={directive.rule_id}, "
                f"context={directive.context.value if hasattr(directive.context, 'value') else str(directive.context)}"
            )

            context["_execution_directive"] = directive
            context["_rule_constraints"] = directive.constraints

            for constraint in directive.constraints:
                if constraint.constraint_type == "pattern":
                    context.setdefault("_patterns_to_enforce", []).append(constraint.value)

            if context.get("_patterns_to_enforce"):
                logger.debug(
                    f"Applied {len(context['_patterns_to_enforce'])} pattern constraints from directive"
                )

            result = self.execute_with_protocol(
                user_request=context.get("request", ""),
                context=context,
            )
            return result

        except Exception as e:
            logger.error(f"TDD execution with directive failed: {str(e)}")
            return Err(f"TDD execution failed: {str(e)}")

    # ------------------------------------------------------------------
    # Private: brittleness scan hooks
    # ------------------------------------------------------------------

    def _run_pre_execution_brittleness_scan(self, context: Dict[str, Any]) -> None:
        """Run BrittlenessScanner before TDD execution (AC-PHASE24-005).

        Non-blocking: violations are logged as warnings; execution continues.

        Args:
            context: Execution context with module_path.
        """
        if getattr(self, "_brittleness_scanner", None) is None:
            return

        try:
            module_path = context.get("module_path", "")
            if not module_path:
                return

            scan_path = str(Path(module_path).parent)
            scan_result = self._brittleness_scanner.scan(scan_path)

            if scan_result.brittleness_score > 0.5:
                logger.warning(
                    f"⚠️ Brittleness detected (score: {scan_result.brittleness_score:.2f}) "
                    f"in {scan_result.scanned_path}"
                )

            for violation in scan_result.circular_dependencies:
                logger.warning(
                    f"⚠️ Circular dependency: {' → '.join(violation.cycle_path)} "
                    f"(severity: {violation.severity})"
                )

            if scan_result.coupling_violations:
                logger.warning(
                    f"⚠️ High coupling detected: {len(scan_result.coupling_violations)} violations"
                )

        except Exception as e:
            logger.warning(f"BrittlenessScanner failed (non-blocking): {e}")

    def _run_post_execution_brittleness_scan(self, context: Dict[str, Any]) -> None:
        """Run BrittlenessScanner AFTER TDD execution (AC-PHASE24-005).

        Args:
            context: Execution context with module_path.
        """
        if getattr(self, "_brittleness_scanner", None) is None:
            return

        try:
            module_path = context.get("module_path", "")
            if not module_path:
                return

            scan_path = str(Path(module_path).parent)
            scan_result = self._brittleness_scanner.scan(scan_path)

            if scan_result.brittleness_score > 0.5:
                logger.warning(
                    f"⚠️ Post-execution brittleness (score: {scan_result.brittleness_score:.2f}) "
                    f"in {scan_result.scanned_path}"
                )

            for violation in scan_result.circular_dependencies:
                logger.warning(
                    f"⚠️ Post-execution circular dependency: {' → '.join(violation.cycle_path)} "
                    f"(severity: {violation.severity})"
                )

            if scan_result.coupling_violations:
                logger.warning(
                    f"⚠️ Post-execution high coupling: {len(scan_result.coupling_violations)} violations"
                )

        except Exception as e:
            logger.warning(f"Post-execution BrittlenessScanner failed (non-blocking): {e}")

    def _run_phase_completion_hook(
        self,
        context: Dict[str, Any],
        execution_result: Dict[str, Any],
    ) -> None:
        """Run PhaseCompletionOrchestrator after successful TDD execution (AC-PHASE24-007).

        Non-blocking: failures are logged as warnings.

        Args:
            context: Execution context.
            execution_result: TDD execution results.
        """
        if getattr(self, "_phase_completion_orchestrator", None) is None:
            return

        try:
            phase_file_str = context.get("phase_file")
            phase_key = context.get("phase_key")

            if not phase_file_str or not phase_key:
                logger.debug("Skipping phase completion hook: no phase_file or phase_key in context")
                return

            phase_file = Path(phase_file_str)
            enhancement_id = context.get("enhancement_id")

            completion_result = self._phase_completion_orchestrator.complete_phase(
                phase_file=phase_file,
                phase_key=phase_key,
                enhancement_id=enhancement_id,
            )

            if completion_result.success:
                logger.info(
                    f"✅ AC-PHASE24-007: Phase completion hook successful - "
                    f"File: {phase_file.name}, Key: {phase_key}, "
                    f"Dashboard: {completion_result.dashboard_regenerated}"
                )
            else:
                logger.warning(
                    f"⚠️ AC-PHASE24-007: Phase completion hook failed - "
                    f"Error: {completion_result.error}"
                )

        except Exception as e:
            logger.warning(f"PhaseCompletionOrchestrator hook failed (non-blocking): {e}")

    # ------------------------------------------------------------------
    # Private: domain logic
    # ------------------------------------------------------------------

    def _execute_domain_logic(
        self,
        user_request: str,
        lens_context: Optional[Any],
        context: Dict[str, Any],
    ) -> Result[Any]:
        """Execute TDD domain logic (RED → GREEN → REFACTOR).

        Called AFTER LENS, security, challenge, and DoR gates.

        Args:
            user_request: User's natural language request.
            lens_context: LENS context from Phase 1 (or None if degraded).
            context: Execution context with module_path, domain, etc.

        Returns:
            Result with TDD guidance and execution status.

        CORE-008: Enforces TDD discipline (RED → GREEN → REFACTOR).
        MCP-GATE: Rejects non-MCP invocations for IMPLEMENT intents.
        AC-PHASE24-005: BrittlenessScanner pre-execution hook.
        """
        try:
            self._run_pre_execution_brittleness_scan(context)

            _opj_prior = self._opj_consult(operation="tdd_execute")
            if _opj_prior:
                logger.debug("TDDOrchestrator: %d prior OPJ patterns found", len(_opj_prior))

            invocation_source = context.get("source", "unknown")
            if invocation_source != "mcp_gateway":
                logger.warning(
                    f"TDD Orchestrator invoked from {invocation_source} instead of MCP gateway"
                )
                return Err(
                    "❌ MCP-GATE VIOLATION (CORE-019)\n\n"
                    "Implementation requests MUST route through MCP gateway.\n"
                    "Direct file creation bypasses:\n"
                    "  - TDD enforcement (CORE-008)\n"
                    "  - Security gates (ARCH-012)\n"
                    "  - Cross-layer validation (CORE-035)\n"
                    "  - Challenge generation\n"
                    "  - DoR confidence gating\n\n"
                    "✅ FIX: Use cortex_process_request MCP tool:\n"
                    "  cortex_process_request(\n"
                    "    request='implement feature X',\n"
                    "    context={'module_path': 'cortex/...', 'domain': '...'}\n"
                    "  )"
                )

            module_path = context.get("module_path", "unknown")
            domain = context.get("domain", "unknown")

            tdd_phase = self._determine_tdd_phase(user_request)

            guidance = self._build_tdd_guidance(
                module_path=module_path,
                domain=domain,
                tdd_phase=tdd_phase,
                user_request=user_request,
                lens_context=lens_context,
            )

            phase_result = self._execute_tdd_phase(tdd_phase, guidance, context)

            if phase_result.is_err():
                return phase_result

            self._run_post_execution_brittleness_scan(context)
            self._run_phase_completion_hook(context, phase_result.unwrap())

            return Ok({
                "orchestrator": "TDDOrchestrator",
                "tdd_phase": tdd_phase.value,
                "guidance": {
                    "module_path": guidance.module_path,
                    "domain": guidance.domain,
                    "rules": [rule.rule_id for rule in guidance.rules],
                    "best_practices": guidance.best_practices,
                    "test_patterns": guidance.test_patterns,
                    "governance_rules": guidance.governance_rules,
                },
                "execution_result": phase_result.unwrap(),
                "lens_context_used": lens_context is not None,
                "protocol_phases_completed": [
                    "LENS Context",
                    "Security Assessment",
                    "Challenge Generation",
                    "DoR Confidence Gate",
                    "TDD Domain Logic",
                ],
            })

        except Exception as e:
            logger.error(f"TDD domain logic failed: {e}", exc_info=True)
            self._opj_record_failure(
                operation="tdd_execute",
                error=str(e),
                attempted_fix="see stack trace",
                confidence=0.8,
            )
            return Err(f"TDD execution error: {str(e)}")

    def _determine_tdd_phase(self, user_request: str) -> TDDPhase:
        """Determine TDD phase from user request keywords.

        Args:
            user_request: User's natural language request.

        Returns:
            TDD phase (RED, GREEN, or REFACTOR).
        """
        request_lower = user_request.lower()

        if any(word in request_lower for word in ["test", "failing test", "red phase", "write test"]):
            return TDDPhase.RED
        elif any(word in request_lower for word in ["refactor", "improve", "optimize", "clean up"]):
            return TDDPhase.REFACTOR
        else:
            return TDDPhase.GREEN

    def _build_tdd_guidance(
        self,
        module_path: str,
        domain: str,
        tdd_phase: TDDPhase,
        user_request: str,
        lens_context: Optional[Any],
    ) -> TDDImplementationGuidance:
        """Build TDD implementation guidance for a cycle.

        Args:
            module_path: Target module path.
            domain: Domain classification.
            tdd_phase: Current TDD phase.
            user_request: User's request.
            lens_context: LENS context (optional).

        Returns:
            Populated :class:`TDDImplementationGuidance`.
        """
        phase_rules = [
            rule for rule in self.knowledge_loader.tdd_rules
            if rule.phase == tdd_phase
        ]
        best_practices = self.knowledge_loader.get_best_practices()

        return TDDImplementationGuidance(
            module_path=module_path,
            domain=domain,
            tdd_phase=tdd_phase,
            rules=phase_rules[:5],
            best_practices=best_practices[:10],
            test_patterns=self._select_test_patterns(tdd_phase),
            coverage_targets={"line": 0.8, "branch": 0.7},
            governance_rules=["CORE-008", "CORE-011", "CORE-012"],
        )

    def _select_test_patterns(self, tdd_phase: TDDPhase) -> List[str]:
        """Select test patterns appropriate for the given TDD phase.

        Args:
            tdd_phase: Current TDD phase.

        Returns:
            List of pattern description strings.
        """
        if tdd_phase == TDDPhase.RED:
            return [
                "Arrange-Act-Assert (AAA)",
                "Given-When-Then (BDD)",
                "Fixture setup with pytest",
                "Parameterized tests for edge cases",
            ]
        elif tdd_phase == TDDPhase.GREEN:
            return [
                "Minimal implementation to pass",
                "Triangulation (add more test cases)",
                "Fake-it-till-you-make-it",
                "Obvious implementation",
            ]
        else:  # REFACTOR
            return [
                "Extract method/class",
                "Replace magic numbers with constants",
                "Apply SOLID principles",
                "Simplify conditionals",
            ]

    def _execute_tdd_phase(
        self,
        tdd_phase: TDDPhase,
        guidance: TDDImplementationGuidance,
        context: Dict[str, Any],
    ) -> Result[Dict[str, Any]]:
        """Dispatch to the appropriate phase handler.

        Args:
            tdd_phase: TDD phase to execute.
            guidance: TDD guidance for the cycle.
            context: Execution context.

        Returns:
            Result with phase execution status dict.
        """
        if tdd_phase == TDDPhase.RED:
            return self._execute_red_phase(guidance, context)
        elif tdd_phase == TDDPhase.GREEN:
            return self._execute_green_phase(guidance, context)
        else:
            return self._execute_refactor_phase(guidance, context)

    def _execute_red_phase(
        self,
        guidance: TDDImplementationGuidance,
        context: Dict[str, Any],
    ) -> Result[Dict[str, Any]]:
        """Execute RED phase (write failing test).

        Args:
            guidance: TDD guidance for the cycle.
            context: Execution context.

        Returns:
            Ok result with RED phase status dict.
        """
        return Ok({
            "phase": "RED",
            "action": "Write failing test",
            "test_patterns": guidance.test_patterns,
            "rules_applied": [rule.rule_id for rule in guidance.rules],
            "status": "ready_for_test_writing",
        })

    def _execute_green_phase(
        self,
        guidance: TDDImplementationGuidance,
        context: Dict[str, Any],
    ) -> Result[Dict[str, Any]]:
        """Execute GREEN phase (minimal implementation).

        Args:
            guidance: TDD guidance for the cycle.
            context: Execution context.

        Returns:
            Ok result with GREEN phase status dict.
        """
        return Ok({
            "phase": "GREEN",
            "action": "Implement minimal code to pass test",
            "implementation_patterns": guidance.test_patterns,
            "rules_applied": [rule.rule_id for rule in guidance.rules],
            "status": "ready_for_implementation",
        })

    def _execute_refactor_phase(
        self,
        guidance: TDDImplementationGuidance,
        context: Dict[str, Any],
    ) -> Result[Dict[str, Any]]:
        """Execute REFACTOR phase (improve design).

        AC-PHASE43-021: Wires to RefactoringOrchestrator for actual execution.
        Falls back to guidance suggestions if adapters unavailable.

        Args:
            guidance: TDD guidance for the cycle.
            context: Execution context.

        Returns:
            Ok result with REFACTOR phase status dict.
        """
        try:
            file_path = context.get("file_path", guidance.module_path)
            language = context.get("language")

            if not language:
                if str(file_path).endswith(".py"):
                    language = "python"
                elif str(file_path).endswith((".ts", ".tsx")):
                    language = "typescript"
                elif str(file_path).endswith((".js", ".jsx")):
                    language = "javascript"
                else:
                    language = "unknown"

            return Ok({
                "phase": "REFACTOR",
                "action": "Refactor code while keeping tests green",
                "language": language,
                "refactoring_suggestions": [
                    "Extract complex logic into smaller methods",
                    "Apply DRY principle to remove duplication",
                    "Improve naming for clarity",
                ],
                "patterns": guidance.test_patterns[:3] if guidance.test_patterns else [],
                "coverage_target": guidance.coverage_targets.get("overall", 0.8),
                "rules_applied": [rule.rule_id for rule in guidance.rules],
                "guidance": guidance.best_practices[:5] if guidance.best_practices else [],
                "source": "TDD guidance (Wave 7 simplified)",
                "status": "success",
            })

        except Exception as e:
            logger.error(f"REFACTOR phase error: {e}", exc_info=True)
            return Ok({
                "phase": "REFACTOR",
                "action": "Refactor code while keeping tests green",
                "refactoring_patterns": guidance.test_patterns,
                "rules_applied": [rule.rule_id for rule in guidance.rules],
                "guidance": guidance.best_practices,
                "status": "ready_for_refactoring",
                "error_handled": True,
            })

    # ------------------------------------------------------------------
    # Public: get_tdd_status
    # ------------------------------------------------------------------

    def get_tdd_status(self) -> Dict[str, Any]:
        """Return TDD orchestrator status and loaded knowledge summary.

        Returns:
            Dict with orchestrator metadata and knowledge stats.
        """
        return {
            "orchestrator": "TDDOrchestrator",
            "version": "2.0",
            "base_protocol": "OrchestratorBaseProtocol",
            "protocol_phases": [
                "LENS Context",
                "Security Assessment",
                "Challenge Generation",
                "DoR Confidence Gate",
                "TDD Domain Logic",
            ],
            "status": "initialized",
            "knowledge_loaded": {
                "tdd_yamls_count": len(self.knowledge_loader.tdd_yamls),
                "tdd_rules_count": len(self.knowledge_loader.tdd_rules),
                "best_practices_count": len(self.knowledge_loader.get_best_practices()),
                "yaml_files": list(self.knowledge_loader.tdd_yamls.keys()),
            },
            "tdd_phases": [phase.value for phase in TDDPhase],
            "routing_intent": "CORE-019: Route ALL implementation intents through TDD-Master",
        }


__all__ = ["TDDExecutionMixin"]
