"""Training Doc Generator — produces structured training documentation (GAP-129-13)."""

from __future__ import annotations

from typing import Any, Dict, List, Optional


class TrainingDocGenerator:
    """Generates structured team training documentation from sprint history.

    Output is a plain-text string (never written to disk — CORE-002).
    Sections: team conventions, velocity baseline, definition-of-done.
    """

    def generate(
        self,
        sprint_history: List[Dict[str, Any]],
        team_norms: Optional[Dict[str, Any]] = None,
    ) -> str:
        """Generate training documentation.

        Args:
            sprint_history: List of sprint dicts with ``sprint_name`` and
                ``completed_points`` keys, plus optional ``team_norms`` override.
            team_norms: Optional dict with convention keys such as
                ``definition_of_done``, ``conventions``, and ``velocity_baseline``.

        Returns:
            Formatted training doc string.
        """
        norms = team_norms or {}
        sections: List[str] = []

        sections.append("# CORTEX Team Training Guide")
        sections.append("=" * 60)
        sections.append(
            "This guide is auto-generated from sprint history and team norms. "
            "Review with your Scrum Master before onboarding new team members."
        )

        # --- Team Conventions ---
        sections.append("\n## Team Conventions")
        conventions = norms.get("conventions", [])
        if conventions:
            for c in conventions:
                sections.append(f"  - {c}")
        else:
            sections.append("  - Use Gherkin acceptance criteria for all user stories.")
            sections.append("  - Run `make test-smoke` before committing code.")
            sections.append("  - All PR reviews require at least one approval.")

        # --- Velocity Baseline ---
        sections.append("\n## Velocity Baseline")
        if sprint_history:
            pts = [float(s.get("completed_points", 0)) for s in sprint_history]
            avg = sum(pts) / len(pts) if pts else 0.0
            max_v = max(pts) if pts else 0.0
            min_v = min(pts) if pts else 0.0
            explicit_baseline = norms.get("velocity_baseline")
            baseline = float(explicit_baseline) if explicit_baseline is not None else round(avg, 1)
            sections.append(f"  - Baseline: {baseline} points/sprint")
            sections.append(f"  - Range: {min_v}–{max_v} pts (last {len(pts)} sprints)")
            sections.append(
                "  - Use this as your planning ceiling; factor in PTO and holidays."
            )
        else:
            sections.append("  - No sprint history available. Set baseline after first sprint.")

        # --- Definition of Done ---
        sections.append("\n## Definition of Done")
        dod = norms.get("definition_of_done", [])
        if dod:
            for criterion in dod:
                sections.append(f"  ✅ {criterion}")
        else:
            sections.append("  ✅ All acceptance criteria pass.")
            sections.append("  ✅ Unit + integration tests GREEN.")
            sections.append("  ✅ Code reviewed and merged to main.")
            sections.append("  ✅ Documentation updated if API changed.")

        sections.append("\n" + "=" * 60)
        sections.append("Generated by CORTEX TrainingDocGenerator")
        return "\n".join(sections)
