#!/usr/bin/env python3
"""
Plan Viewer Launcher for cortex5-epic

Auto-generated by Plan Converter Orchestrator.
Launches HTTP server for plan-viewer.html on port 8000-8010.
"""

import http.server
import socketserver
import os
from pathlib import Path

def find_available_port(start_port=8000, end_port=8010):
    """Find first available port in range."""
    for port in range(start_port, end_port + 1):
        try:
            with socketserver.TCPServer(("", port), http.server.SimpleHTTPRequestHandler) as test_server:
                return port
        except OSError:
            continue
    raise RuntimeError(f"No available ports in range {start_port}-{end_port}")

if __name__ == "__main__":
    # Change to plan folder
    plan_folder = Path(__file__).parent
    os.chdir(plan_folder)
    
    # Find available port
    port = find_available_port()
    
    # Start server
    Handler = http.server.SimpleHTTPRequestHandler
    with socketserver.TCPServer(("", port), Handler) as httpd:
        print(f"🚀 Plan Viewer Server Started")
        print(f"📊 URL: http://localhost:{port}/plan-viewer.html")
        print(f"📁 Serving: {plan_folder}")
        print(f"🛑 Press Ctrl+C to stop")
        httpd.serve_forever()
