"""
Flatten and move Bollywood music files.

Reads the plan from scripts/_flatten_title_cache.json (generated by
flatten_llm_preview.py), then:
  - Moves each winner to Z:/MUSIC/Flattened files/<Title>.mp4
  - Skips smaller duplicates (leaves originals untouched)
  - Prints a move log and a skip log to stdout

Usage:
    python scripts/flatten_bollywood.py           # dry run (shows plan, no moves)
    python scripts/flatten_bollywood.py --execute  # live move
"""

import argparse
import json
import shutil
import sys
from pathlib import Path

DEST_DIR = Path("Z:/MUSIC/Flattened files")
CACHE = Path("scripts/_flatten_title_cache.json")


def load_plan() -> list[dict]:
    if not CACHE.exists():
        print(
            f"ERROR: {CACHE} not found.\n"
            "Run scripts/flatten_llm_preview.py first to generate the plan.",
            file=sys.stderr,
        )
        sys.exit(1)
    return json.loads(CACHE.read_text(encoding="utf-8"))


def run(dry: bool) -> None:
    plan = load_plan()

    moves = [e for e in plan if e["action"] == "move"]
    skips = [e for e in plan if e["action"] == "skip"]

    mode = "DRY RUN" if dry else "LIVE"
    print(f"\n=== flatten_bollywood.py  [{mode}] ===")
    print(f"  Destination : {DEST_DIR}")
    print(f"  Files to move: {len(moves)}  |  Duplicates to skip: {len(skips)}\n")

    if not dry:
        DEST_DIR.mkdir(parents=True, exist_ok=True)

    # --- Moves ---
    moved = 0
    errors = 0
    for entry in moves:
        src = Path(entry["original"])
        dest = DEST_DIR / f"{entry['flat_title']}.mp4"
        size_kb = entry["size_bytes"] // 1024

        if not src.exists():
            print(f"  MISSING  {src.name}")
            errors += 1
            continue

        if dest.exists():
            print(f"  EXISTS  {dest.name}  <- already in destination, skipping")
            errors += 1
            continue

        print(f"  MOVE  {src.name[:55]:<56} -> {dest.name}  ({size_kb:,} KB)")
        if not dry:
            try:
                shutil.move(str(src), str(dest))
                moved += 1
            except Exception as exc:
                print(f"         ERROR: {exc}")
                errors += 1
        else:
            moved += 1

    # --- Skips ---
    print(f"\n--- Duplicates removed ({len(skips)} files, smaller copy discarded) ---")
    for entry in skips:
        src = Path(entry["original"])
        size_kb = entry["size_bytes"] // 1024
        reason = entry.get("reason", "")
        print(f"  SKIP  {src.name[:55]:<56}  ({size_kb:,} KB)  {reason}")

    # --- Summary ---
    print(f"\n{'=' * 60}")
    action = "Would move" if dry else "Moved"
    print(f"  {action} : {moved}")
    print(f"  Skipped (smaller dupes) : {len(skips)}")
    if errors:
        already = errors
        print(f"  Already in destination  : {already} (not overwritten)")
    if dry:
        print("\n  Re-run with --execute to apply.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Flatten Bollywood music library.")
    parser.add_argument(
        "--execute",
        action="store_true",
        help="Perform the actual file moves. Without this flag, runs as dry-run.",
    )
    args = parser.parse_args()
    run(dry=not args.execute)


if __name__ == "__main__":
    main()
