"""
AC-TC-002-01: Template Manager

Manages template rendering, loading, and caching.
Provides the main interface for working with templates.

Copyright © 2025-2026 Asif Hussain. All rights reserved.
"""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Any, Optional, Union
import re
import yaml


@dataclass
class RenderResult:
    """Result of template rendering."""
    success: bool
    content: str = ""
    errors: List[str] = field(default_factory=list)
    missing_variables: List[str] = field(default_factory=list)


class TemplateManager:
    """
    Template manager for tier-2 templates.
    
    Handles template loading, caching, and rendering with
    variable substitution.
    """
    
    # Default template content for domains
    DEFAULT_TEMPLATES: Dict[str, str] = {
        'planning-recommendations': """
## Implementation Recommendations: {plan_title}

**Phase:** {phase}
**Acceptance Criteria:** {ac_count} AC-IDs
**Estimated Hours:** {estimated_hours}

### Overview

This implementation plan outlines the recommended approach for {plan_title}.

### Key Deliverables

1. Complete all {ac_count} acceptance criteria
2. Maintain test coverage above 90%
3. Follow governance rules (CORE-008, CORE-011, CORE-012)

### Timeline

- **Start:** Upon approval
- **Target Completion:** {estimated_hours} hours from start
- **Checkpoints:** After each AC-ID completion

### Risks & Mitigations

| Risk | Mitigation |
|------|------------|
| Scope creep | Strict AC-ID adherence |
| Technical debt | Code review at each checkpoint |
| Testing gaps | TDD approach (tests first) |

### Next Steps

1. Review and approve this plan
2. Create git checkpoint
3. Begin implementation with first AC-ID

---
*Generated by CORTEX Template Engine*
""",
        'planning-impact-assessment': """
## Impact Assessment: {change_scope}

### Affected Files

{affected_files}

### Risk Level: {risk_level}

### Analysis Summary

This change impacts the following areas of the codebase:

- **Direct Impact:** Files listed above will be modified
- **Indirect Impact:** Dependent modules may need updates
- **Test Impact:** Related test files should be verified

### Recommendations

1. Create backup/checkpoint before proceeding
2. Run full test suite after changes
3. Review affected dependencies
4. Update documentation as needed

---
*Generated by CORTEX Impact Analysis*
""",
        'planning-timeline': """
## Project Timeline: {plan_title}

**Start Date:** {start_date}
**End Date:** {end_date}

### Milestones

{milestones}

### Progress Tracking

Track progress against these milestones using the governance dashboard.

---
*Generated by CORTEX Planning System*
""",
        'planning-resource-allocation': """
## Resource Allocation Plan

### Available Resources

{resources}

### Assignments

{assignments}

### Capacity Analysis

Current capacity utilization: {capacity}%

---
*Generated by CORTEX Resource Planner*
""",
        'planning-risk-analysis': """
## Risk Analysis Report

### Identified Risks

{risks}

### Risk Matrix

| Risk | Probability | Impact | Score |
|------|-------------|--------|-------|
{risk_table}

### Mitigation Strategies

{mitigation}

---
*Generated by CORTEX Risk Analyzer*
""",
        'planning-milestone-tracker': """
## Milestone Tracker

### Milestones

{milestones}

### Status Summary

| Milestone | Status | Target Date |
|-----------|--------|-------------|
{milestone_table}

---
*Generated by CORTEX Milestone Tracker*
""",
        'planning-dependency-map': """
## Dependency Map

### Dependencies

{dependencies}

### Blocking Items

{blocking}

### Blocked By

{blocked_by}

---
*Generated by CORTEX Dependency Analyzer*
""",
        'planning-progress-report': """
## Progress Report

### Summary

- **Completed:** {completed}
- **In Progress:** {in_progress}
- **Blocked:** {blocked}
- **Overall Progress:** {percentage}%

### Details

Progress tracking for current phase implementation.

---
*Generated by CORTEX Progress Tracker*
""",
    }
    
    # Variable patterns for extraction
    VARIABLE_PATTERN = re.compile(r'\{(\w+)\}')
    
    def __init__(self, template_base_path: Optional[Path] = None):
        """
        Initialize template manager.
        
        Args:
            template_base_path: Base path for template files
        """
        if template_base_path is None:
            self.template_base_path = Path(__file__).parent.parent.parent / "cortex-brain" / "tier2"
        else:
            self.template_base_path = Path(template_base_path)
        
        self._cache: Dict[str, str] = {}
        self._metadata_cache: Dict[str, Dict[str, Any]] = {}
        
        # Import content strategy for template definitions
        from .content_strategy import ContentPopulationStrategy
        self._strategy = ContentPopulationStrategy(self.template_base_path)
    
    def get_domain_templates(self, domain: str) -> List[Dict[str, Any]]:
        """
        Get templates for a specific domain.
        
        Args:
            domain: Domain name
            
        Returns:
            List of template metadata
        """
        return self._strategy.get_domain_templates(domain)
    
    def get_template_content(self, template_id: str) -> Optional[str]:
        """
        Get template content by ID.
        
        Args:
            template_id: Template identifier
            
        Returns:
            Template content string or None
        """
        # Check cache first
        if template_id in self._cache:
            return self._cache[template_id]
        
        # Try to load from file
        content = self._load_template_from_file(template_id)
        if content:
            self._cache[template_id] = content
            return content
        
        # Fall back to default templates
        if template_id in self.DEFAULT_TEMPLATES:
            content = self.DEFAULT_TEMPLATES[template_id]
            self._cache[template_id] = content
            return content
        
        return None
    
    def _load_template_from_file(self, template_id: str) -> Optional[str]:
        """
        Load template content from file.
        
        Args:
            template_id: Template identifier
            
        Returns:
            Template content or None
        """
        # Get template metadata
        metadata = self._strategy.get_template_by_id(template_id)
        if not metadata:
            return None
        
        domain = metadata['domain']
        
        # Try different file locations
        possible_paths = [
            self.template_base_path / "domains" / domain / f"{template_id.replace(f'{domain}-', '')}.yaml",
            self.template_base_path / "domains" / domain / f"{template_id}.yaml",
            self.template_base_path / f"{template_id}.yaml",
        ]
        
        for path in possible_paths:
            if path.exists():
                try:
                    with open(path, 'r') as f:
                        data = yaml.safe_load(f)
                        if data and 'template' in data:
                            # Extract content from template structure
                            structure = data['template'].get('structure', [])
                            content_parts = []
                            for section in structure:
                                if 'format' in section:
                                    content_parts.append(section['format'])
                            return '\n'.join(content_parts)
                except Exception:
                    continue
        
        return None
    
    def render_template(
        self, 
        template_id: str, 
        variables: Dict[str, Any],
        strict: bool = True
    ) -> str:
        """
        Render template with variables.
        
        Args:
            template_id: Template identifier
            variables: Variables to substitute
            strict: If True, raise on missing required variables
            
        Returns:
            Rendered template content
            
        Raises:
            ValueError: If strict=True and required variables missing
        """
        content = self.get_template_content(template_id)
        if content is None:
            raise ValueError(f"Template not found: {template_id}")
        
        # Find all variables in template
        template_vars = set(self.VARIABLE_PATTERN.findall(content))
        
        # Check for missing variables
        missing = template_vars - set(variables.keys())
        
        if strict and missing:
            raise ValueError(f"Missing required variables: {', '.join(missing)}")
        
        # Substitute variables
        rendered = content
        for var_name, var_value in variables.items():
            placeholder = '{' + var_name + '}'
            
            # Convert value to string representation
            if isinstance(var_value, list):
                str_value = '\n'.join(f"- {item}" for item in var_value)
            elif isinstance(var_value, dict):
                str_value = yaml.dump(var_value, default_flow_style=False)
            else:
                str_value = str(var_value)
            
            rendered = rendered.replace(placeholder, str_value)
        
        # Replace any remaining variables with empty string if not strict
        if not strict:
            rendered = self.VARIABLE_PATTERN.sub('', rendered)
        
        return rendered
    
    def get_template_variables(self, template_id: str) -> List[str]:
        """
        Get list of variables in a template.
        
        Args:
            template_id: Template identifier
            
        Returns:
            List of variable names
        """
        content = self.get_template_content(template_id)
        if content is None:
            return []
        
        return list(set(self.VARIABLE_PATTERN.findall(content)))
    
    def clear_cache(self) -> None:
        """Clear template cache."""
        self._cache.clear()
        self._metadata_cache.clear()
    
    def preload_domain(self, domain: str) -> int:
        """
        Preload all templates for a domain into cache.
        
        Args:
            domain: Domain name
            
        Returns:
            Number of templates loaded
        """
        templates = self.get_domain_templates(domain)
        count = 0
        
        for template in templates:
            content = self.get_template_content(template['id'])
            if content:
                count += 1
        
        return count
