"""
LENS Synthesis Implementation - Phase 4 of LENS Protocol

AC-PROD-002-01: LENS Synthesis - Language→Examination→Navigation→Synthesis
Resolves ISSUE-002: LENS NOT integrated (Phase 4 only)

The LENS protocol provides 4-phase synthesis for comprehensive code analysis:
1. Language: Natural language understanding (existing in PHASE-07)
2. Examination: AST analysis (existing in PHASE-07)
3. Navigation: Domain knowledge traversal (existing in PHASE-07)
4. Synthesis: Combining insights (THIS IMPLEMENTATION)

This module integrates all LENS phases and produces coherent recommendations
for Stage 3 (Knowledge) of the Master Orchestrator workflow.

CORE Governance:
  - CORE-008: TDD (tests first)
  - CORE-011: Type hints mandatory
  - CORE-012: Google-style docstrings
  - CORE-013: Specific exception handling
  - CORE-027: Audit trail logging
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple

# Phase 51: Enhanced response template with semantic color coding
from cortex.agents.core.response_template_generator import ResponseTemplate
from cortex.brain.core.result import Err, Ok, Result
from cortex.infrastructure.enhanced_audit_logger import EnhancedAuditLogger
from cortex.orchestrators.decorators import inject_orchestrator_context


class SynthesisPhase(Enum):
    """
    LENS Synthesis processing phases.

    Attributes:
        LANGUAGE_ANALYSIS: Phase 1 - Natural language understanding
        CODE_EXAMINATION: Phase 2 - AST and code structure analysis
        DOMAIN_NAVIGATION: Phase 3 - Domain knowledge traversal
        SYNTHESIS: Phase 4 - Synthesis of all insights
    """
    LANGUAGE_ANALYSIS = "language"
    CODE_EXAMINATION = "examination"
    DOMAIN_NAVIGATION = "navigation"
    SYNTHESIS = "synthesis"


# Phase 65 S6: Use canonical LENSContext (CORE-035 compliance)
# Import from canonical location and re-export for backward compatibility
from cortex.lens.models.context import LENSContext  # noqa: F401


@dataclass
class SynthesisRecommendation:
    """
    Recommendation generated by LENS Synthesis.

    Attributes:
        source_phase: Which LENS phase generated this
        insight: The insight itself
        confidence: Confidence score (0-1)
        reasoning: Why this insight matters
        priority: Priority level (high, medium, low)
    """
    source_phase: str
    insight: str
    confidence: float = 0.75
    reasoning: str = ""
    priority: str = "medium"


class LENSSynthesis:
    """
    LENS Synthesis Phase 4 - Combines all LENS phases into recommendations.

    The LENS protocol provides comprehensive code analysis:
    1. Language: Extracts intent from natural language
    2. Examination: Analyzes code structure and patterns
    3. Navigation: Traverses domain knowledge graphs
    4. Synthesis (this module): Combines all insights

    Usage:
        synthesis = LENSSynthesis()
        context = LENSContext(
            operation="implement_feature",
            language_analysis={...},
            code_examination={...},
            domain_navigation={...}
        )
        result = synthesis.synthesize(context)
        recommendations = result.unwrap()

    CORE Governance:
      - CORE-008: TDD - tests created first
      - CORE-011: Type hints - all methods typed
      - CORE-012: Docstrings - Google style
      - CORE-027: Audit trail - AC_START/EXECUTE/COMPLETE
    """

    def __init__(self) -> None:
        """
        Initialize LENS Synthesis.

        Sets up:
        - Audit logger
        - Synthesis history
        - Phase weights for combining insights
        """
        self.logger: EnhancedAuditLogger = EnhancedAuditLogger.instance()
        self.synthesis_history: List[Dict[str, Any]] = []

        # Weights for combining phases (0-1, sum = 1.0)
        self.phase_weights: Dict[str, float] = {
            "language": 0.25,
            "examination": 0.35,
            "navigation": 0.40,
        }

        self.logger.log_operation_complete(
            ac_id="AC-PROD-002-01",
            operation="LENS_SYNTHESIS_INIT",
            success=True,
            details={"phase_weights": self.phase_weights}
        )

    def analyze_with_directive(
        self,
        code: str,
        directive: 'ExecutionDirective',
        context: Optional[Dict[str, Any]] = None
    ) -> Result[Dict[str, Any]]:
        """
        Execute LENS analysis with ExecutionDirective from Phase 52.

        AC-PHASE52-003: LENSSynthesis accepts ExecutionDirective

        Uses directive.context to scope analysis:
        - CORTEX_INTERNAL context → stricter rules
        - PRODUCTION_REPO context → standard rules

        Applies directive.rule_id to determine which rules to check.

        Args:
            code: Code to analyze
            directive: ExecutionDirective from AgentRulesInterpreter
            context: Optional execution context

        Returns:
            Result with analysis findings including:
                - security_results: Security analysis output
                - rule_violations: Violations by rule_id
                - context: Directive context used for scoping
        """
        try:
            # Log directive application
            self.logger.log_operation_start(
                ac_id="AC-PHASE52-003",
                operation="LENS_ANALYSIS_WITH_DIRECTIVE",
                details={
                    "agent_id": directive.agent_id,
                    "rules": directive.rule_id,
                    "context": directive.context.value if hasattr(directive.context, 'value') else str(directive.context),
                    "target_orchestrator": directive.target_orchestrator,
                }
            )

            # Store directive in context for analysis phases
            if context is None:
                context = {}
            context["_execution_directive"] = directive
            context["_rule_id_list"] = directive.rule_id.split("|") if directive.rule_id else []

            # Scope analysis based on context
            scope_rules = []
            if directive.context.value == "CORTEX_INTERNAL" if hasattr(directive.context, 'value') else False:
                # Stricter rules for CORTEX self-development
                scope_rules = ["CORE-008", "CORE-011", "CORE-012", "CORE-035"]
            else:
                # Standard rules for production
                scope_rules = directive.rule_id.split("|") if directive.rule_id else []

            # Execute LENS analysis (existing synthesize method)
            lens_context = LENSContext(
                operation="analysis_with_directive",
                language_analysis={"scope": directive.context.value if hasattr(directive.context, 'value') else str(directive.context)},
                code_examination={"rules_to_check": scope_rules},
            )

            synthesis_result = self.synthesize(lens_context)

            if synthesis_result.is_ok():
                result = synthesis_result.unwrap()
                result["directive_context"] = directive.context.value if hasattr(directive.context, 'value') else str(directive.context)
                result["rules_applied"] = scope_rules

                self.logger.log_operation_complete(
                    ac_id="AC-PHASE52-003",
                    operation="LENS_ANALYSIS_WITH_DIRECTIVE",
                    success=True,
                    details={
                        "rules_checked": len(scope_rules),
                        "scope": directive.context.value if hasattr(directive.context, 'value') else str(directive.context),
                    }
                )

                return Ok(result)
            else:
                return synthesis_result

        except Exception as e:
            self.logger.log_operation_complete(
                ac_id="AC-PHASE52-003",
                operation="LENS_ANALYSIS_WITH_DIRECTIVE",
                success=False,
                details={"error": str(e)}
            )
            return Err(f"LENS analysis with directive failed: {str(e)}")

    @inject_orchestrator_context
    def synthesize(
        self,
        context: LENSContext
    ) -> Result[Dict[str, Any]]:
        """
        Synthesize all LENS phases into recommendations.

        Combines outputs from Language analysis, Code examination,
        and Domain navigation into coherent recommendations for
        Stage 3 (Knowledge retrieval).

        Algorithm:
        1. Extract insights from each phase
        2. Weight insights by phase importance
        3. Score recommendation confidence
        4. Rank by priority
        5. Generate reasoning

        Args:
            context: LENSContext with Phase 1-3 outputs

        Returns:
            Result[Dict] with synthesis output containing:
                - recommendations: List of recommendations
                - combined_confidence: Overall confidence
                - timestamp: When synthesis was done
                - reasoning: Why these recommendations

        Raises:
            ValueError: If context is invalid
            Exception: If synthesis fails
        """
        try:
            # Log synthesis start (AC_START)
            self.logger.log_operation_start(
                ac_id="AC-PROD-002-01",
                operation="LENS_SYNTHESIS",
                details={
                    "operation": context.operation,
                    "turn_number": context.turn_number
                }
            )

            # Validate context
            validation = self._validate_context(context)
            if validation.is_err():
                self.logger.log_operation_complete(
                    ac_id="AC-PROD-002-01",
                    operation="LENS_SYNTHESIS",
                    success=False,
                    details={"error": validation.unwrap_err()}
                )
                return validation

            # Extract and score insights from all phases
            recommendations = self._generate_recommendations(context)

            # Calculate combined confidence
            combined_confidence = self._calculate_combined_confidence(recommendations)

            # Build synthesis output (AC_EXECUTE)
            synthesis_output: Dict[str, Any] = {
                "operation": context.operation,
                "recommendations": [
                    {
                        "source": rec.source_phase,
                        "insight": rec.insight,
                        "confidence": rec.confidence,
                        "priority": rec.priority,
                        "reasoning": rec.reasoning
                    }
                    for rec in recommendations
                ],
                "combined_confidence": combined_confidence,
                "phase_analysis": {
                    "language": context.language_analysis is not None,
                    "examination": context.code_examination is not None,
                    "navigation": context.domain_navigation is not None
                },
                "timestamp": datetime.now().isoformat(),
                "turn_number": context.turn_number
            }

            # Store in history
            self.synthesis_history.append(synthesis_output)

            # Store in context
            context.synthesis_output = synthesis_output

            # Log synthesis complete (AC_COMPLETE)
            self.logger.log_operation_complete(
                ac_id="AC-PROD-002-01",
                operation="LENS_SYNTHESIS",
                success=True,
                details={
                    "recommendations_count": len(recommendations),
                    "combined_confidence": combined_confidence,
                    "turn_number": context.turn_number
                }
            )

            return Ok(synthesis_output)

        except ValueError as e:
            self.logger.log_operation_complete(
                ac_id="AC-PROD-002-01",
                operation="LENS_SYNTHESIS",
                success=False,
                details={"error": str(e)}
            )
            return Err(f"Synthesis validation error: {str(e)}")

        except Exception as e:
            self.logger.log_operation_complete(
                ac_id="AC-PROD-002-01",
                operation="LENS_SYNTHESIS",
                success=False,
                details={"error": str(e)}
            )
            return Err(f"Synthesis failed: {str(e)}")

    def _validate_context(
        self,
        context: LENSContext
    ) -> Result[bool]:
        """
        Validate LENS context format.

        Args:
            context: Context to validate

        Returns:
            Result[bool]: Ok(True) if valid, Err(message) if invalid
        """
        try:
            if not isinstance(context, LENSContext):
                return Err("Context must be LENSContext instance")

            if not context.operation:
                return Err("Operation cannot be empty")

            # At least one phase output required
            has_phase = any([
                context.language_analysis,
                context.code_examination,
                context.domain_navigation
            ])

            if not has_phase:
                return Err("At least one LENS phase output required")

            return Ok(True)

        except Exception as e:
            return Err(f"Validation error: {str(e)}")

    def _generate_recommendations(
        self,
        context: LENSContext
    ) -> List[SynthesisRecommendation]:
        """
        Generate recommendations from all LENS phases.

        Extracts key insights from each phase and creates
        scored recommendations.

        Args:
            context: LENS context with phase outputs

        Returns:
            List of recommendations sorted by priority
        """
        recommendations: List[SynthesisRecommendation] = []

        # Phase 1: Language Analysis
        if context.language_analysis:
            insight = context.language_analysis.get("key_intent", "analyze")
            rec = SynthesisRecommendation(
                source_phase="language",
                insight=f"Detected intent: {insight}",
                confidence=context.language_analysis.get("confidence", 0.8),
                reasoning="From natural language understanding",
                priority="high"
            )
            recommendations.append(rec)

        # Phase 2: Code Examination
        if context.code_examination:
            pattern = context.code_examination.get("pattern", "unknown")
            rec = SynthesisRecommendation(
                source_phase="examination",
                insight=f"Code pattern: {pattern}",
                confidence=context.code_examination.get("confidence", 0.75),
                reasoning="From AST analysis",
                priority="medium"
            )
            recommendations.append(rec)

        # Phase 3: Domain Navigation
        if context.domain_navigation:
            knowledge = context.domain_navigation.get("knowledge", "unknown")
            rec = SynthesisRecommendation(
                source_phase="navigation",
                insight=f"Domain knowledge: {knowledge}",
                confidence=context.domain_navigation.get("confidence", 0.7),
                reasoning="From knowledge graph traversal",
                priority="medium"
            )
            recommendations.append(rec)

        # Sort by priority
        priority_order = {"high": 0, "medium": 1, "low": 2}
        recommendations.sort(
            key=lambda x: (priority_order.get(x.priority, 3), -x.confidence)
        )

        return recommendations

    def _calculate_combined_confidence(
        self,
        recommendations: List[SynthesisRecommendation]
    ) -> float:
        """
        Calculate combined confidence from all recommendations.

        Uses weighted average of recommendation confidences.

        Args:
            recommendations: List of recommendations

        Returns:
            Combined confidence score (0-1)
        """
        if not recommendations:
            return 0.0

        # Weight by source phase
        weighted_sum = 0.0
        total_weight = 0.0

        for rec in recommendations:
            weight = self.phase_weights.get(rec.source_phase, 0.33)
            weighted_sum += rec.confidence * weight
            total_weight += weight

        if total_weight == 0:
            return 0.0

        return min(1.0, weighted_sum / total_weight)

    def get_synthesis_history(self, limit: int = 10) -> List[Dict[str, Any]]:
        """
        Get recent synthesis results.

        Args:
            limit: Maximum number of results to return

        Returns:
            List of recent synthesis operations
        """
        return self.synthesis_history[-limit:]

    def get_statistics(self) -> Dict[str, Any]:
        """
        Get synthesis statistics.

        Returns:
            Dict with synthesis statistics
        """
        if not self.synthesis_history:
            return {
                "total_syntheses": 0,
                "average_confidence": 0.0,
                "phase_usage": {}
            }

        phase_counts: Dict[str, int] = {"language": 0, "examination": 0, "navigation": 0}
        total_confidence = 0.0

        for synthesis in self.synthesis_history:
            total_confidence += synthesis.get("combined_confidence", 0.0)

            for phase, used in synthesis.get("phase_analysis", {}).items():
                if used:
                    phase_counts[phase] += 1

        return {
            "total_syntheses": len(self.synthesis_history),
            "average_confidence": total_confidence / len(self.synthesis_history),
            "phase_usage": phase_counts
        }


# Module exports
__all__ = [
    "LENSSynthesis",
    "LENSContext",
    "SynthesisPhase",
    "SynthesisRecommendation",
]
