"""
Test for AC-REM-003-03: Copyright Notice in Chat Responses

This test verifies that copyright notices appear in all chat responses
generated by the CORTEX system.

Issue: ISSUE-003 (Response Verbosity & Header Injection)
AC-ID: AC-REM-003-03
Priority: HIGH
"""

import pytest
from src.api.chat_response_formatter import ChatResponseFormatter


class TestCopyrightNotice:
    """Test suite for copyright notice inclusion."""
    
    @pytest.fixture
    def formatter(self):
        """Create ChatResponseFormatter instance."""
        return ChatResponseFormatter()
    
    def test_copyright_in_single_response(self, formatter):
        """Verify copyright appears in formatted response."""
        response = formatter.format_response(
            content="Test content",
            operation="TEST",
            phase="PHASE-16",
            orchestrator="TestOrch"
        )
        
        assert "copyright" in response
        assert response["copyright"] == "Copyright © 2025-2026 Asif Hussain. All rights reserved."
    
    def test_copyright_matches_exact_format(self, formatter):
        """Verify copyright follows exact required format."""
        response = formatter.format_response(
            content="Test",
            operation="TEST",
            phase="PHASE-16",
            orchestrator="Test"
        )
        
        expected = "Copyright © 2025-2026 Asif Hussain. All rights reserved."
        assert response["copyright"] == expected
    
    def test_copyright_in_markdown_header(self, formatter):
        """Verify copyright appears in markdown header format."""
        markdown = formatter.format_response_with_header_markdown(
            content="Test content",
            operation="TEST",
            phase="PHASE-16",
            orchestrator="TestOrch"
        )
        
        assert "Copyright © 2025-2026 Asif Hussain" in markdown
    
    def test_copyright_includes_year_range(self, formatter):
        """Verify copyright includes full year range."""
        response = formatter.format_response(
            content="Test",
            operation="TEST",
            phase="PHASE-16",
            orchestrator="Test"
        )
        
        copyright_text = response["copyright"]
        assert "2025" in copyright_text
        assert "2026" in copyright_text
        assert "Asif Hussain" in copyright_text
    
    def test_copyright_in_batch_responses(self, formatter):
        """Verify copyright appears in all batch responses."""
        responses = formatter.format_batch_responses(
            contents=["Response 1", "Response 2", "Response 3"],
            operation="TEST",
            phase="PHASE-16",
            orchestrator="Test"
        )
        
        for response in responses:
            assert "copyright" in response
            assert "Copyright © 2025-2026 Asif Hussain" in response["copyright"]
    
    def test_copyright_consistency_across_calls(self, formatter):
        """Verify copyright is consistent across multiple calls."""
        response1 = formatter.format_response(
            content="Test 1",
            operation="OP1",
            phase="PHASE-16",
            orchestrator="Orch1"
        )
        
        response2 = formatter.format_response(
            content="Test 2",
            operation="OP2",
            phase="PHASE-15",
            orchestrator="Orch2"
        )
        
        # Copyright should be identical
        assert response1["copyright"] == response2["copyright"]
    
    def test_copyright_non_empty(self, formatter):
        """Verify copyright is never empty."""
        response = formatter.format_response(
            content="Test",
            operation="TEST",
            phase="PHASE-16",
            orchestrator="Test"
        )
        
        assert response["copyright"]
        assert len(response["copyright"]) > 0
        assert response["copyright"].strip() == response["copyright"]
    
    def test_copyright_immutable(self):
        """Verify copyright notice is consistent (immutable)."""
        formatter1 = ChatResponseFormatter()
        formatter2 = ChatResponseFormatter()
        
        assert formatter1.COPYRIGHT == formatter2.COPYRIGHT
        assert formatter1.COPYRIGHT == "Copyright © 2025-2026 Asif Hussain. All rights reserved."


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
