"""
CORTEX Agent Registry

Central registry for all CORTEX agents.

Auto-generated by: scripts/auto_wire_orchestrators.py
Updated: 2025-12-30 (Phase 4 Maintenance)
"""

from typing import Dict, Type

# Import agents (add as needed)
try:
    from src.cortex_agents.strategic.interactive_planner import InteractivePlanner
except ImportError:
    InteractivePlanner = None

AGENT_REGISTRY: Dict[str, Type] = {}

# Register interactive planning agent
if InteractivePlanner:
    AGENT_REGISTRY["interactive_planning"] = InteractivePlanner


def get_agent(agent_name: str):
    """Get agent by name."""
    return AGENT_REGISTRY.get(agent_name)


def list_agents() -> list:
    """List all registered agents."""
    return list(AGENT_REGISTRY.keys())
