mindmap
  root((23 Orchestrators))
    Core 7
      Interaction
      Intent Router
      Workflow
      TDD
      Enforcement
      Master
      Observation
    Domain 6
      Refactoring
      Planning
      Documentation
      PhaseExecutor
      Autonomous
      Conversation
    Support 11
      Onboarding
      Tool Discovery
      LENS
      Challenge Engine
      Duplication Detector
      Recommendation
      Domain Brain
      Governance
      Session Manager
      Total Recall
      Observation
